(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t110-01',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Czym jest tkanka?',
      opcje: [
        'Zespołem komórek o podobnej budowie i pochodzeniu, pełniących wspólną funkcję',
        'Pojedynczą, dużą komórką o specjalnym kształcie',
        'Narządem zbudowanym z kilku układów',
        'Substancją nieożywioną wypełniającą wnętrze organizmu',
      ],
      poprawna: 0,
      wyjasnienie: 'Tkanka to zespół komórek o podobnej budowie i pochodzeniu, które wspólnie pełnią określoną funkcję w organizmie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t110-02',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Krew zaliczana jest do tkanki łącznej.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — krew, mimo płynnej postaci, jest odmianą tkanki łącznej: jej komórki są rozproszone w obfitej istocie międzykomórkowej, czyli osoczu.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t110-03',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Która tkanka roślinna umożliwia roślinie wzrost przez całe życie?',
      opcje: ['Tkanka twórcza (merystematyczna)', 'Tkanka okrywająca', 'Tkanka miękiszowa', 'Tkanka wzmacniająca'],
      poprawna: 0,
      wyjasnienie: 'Tylko komórki tkanki twórczej zachowują zdolność do ciągłych podziałów, co umożliwia roślinie wzrost na długość i grubość przez całe życie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t110-04',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi nazwami tkanek przewodzących.',
      tekstZLuka: 'Tkanka {{luka1}} transportuje wodę i sole mineralne od korzeni do liści, a tkanka {{luka2}} transportuje produkty fotosyntezy do pozostałych części rośliny.',
      odpowiedziLuk: { luka1: ['przewodząca (ksylem)', 'ksylem', 'przewodząca'], luka2: ['przewodząca (floem)', 'floem', 'przewodząca'] },
      wyjasnienie: 'Ksylem (drewno) prowadzi wodę i sole mineralne w górę rośliny, a floem (łyko) transportuje substancje odżywcze wytworzone w fotosyntezie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t110-05',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Floem (łyko) transportuje wodę i sole mineralne od korzeni do liści.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — wodę i sole mineralne transportuje ksylem (drewno). Floem przewodzi produkty fotosyntezy wytworzone w liściach.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t110-06',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Która tkanka zwierzęca zbudowana jest z komórek zdolnych do odbierania i przewodzenia impulsów?',
      opcje: ['Tkanka nabłonkowa', 'Tkanka łączna', 'Tkanka mięśniowa', 'Tkanka nerwowa'],
      poprawna: 3,
      wyjasnienie: 'Tkanka nerwowa zbudowana jest z neuronów, które odbierają, przewodzą i przekazują impulsy nerwowe.',
      umiejetnosci: ['budowa-funkcja'],
    },
    {
      id: 'p-t110-07',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które struktury zaliczamy do tkanki łącznej? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Kość', 'Krew', 'Tkanka tłuszczowa', 'Naskórek'],
      poprawna: [0, 1, 2],
      wyjasnienie: 'Kość, krew i tkanka tłuszczowa to odmiany tkanki łącznej. Naskórek zbudowany jest z tkanki nabłonkowej.',
      umiejetnosci: ['analiza', 'wiedza'],
    },
    {
      id: 'p-t110-08',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj tkankę roślinną do jej głównej funkcji.',
      dopasowanie: {
        lewa: ['Tkanka twórcza', 'Tkanka okrywająca', 'Tkanka miękiszowa (asymilacyjna)', 'Tkanka przewodząca'],
        prawa: ['Ochrona przed utratą wody', 'Umożliwienie wzrostu rośliny', 'Transport wody i substancji odżywczych', 'Prowadzenie fotosyntezy'],
        pary: [1, 0, 3, 2],
      },
      wyjasnienie: 'Tkanka twórcza umożliwia wzrost, okrywająca chroni przed utratą wody, miękiszowa (asymilacyjna) prowadzi fotosyntezę, a przewodząca transportuje wodę i substancje odżywcze.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t110-09',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj etapy drogi wody pobranej przez roślinę — od pobrania do utraty w procesie transpiracji.',
      elementy: ['Pobranie wody przez korzeń', 'Transport wody przez ksylem w łodydze', 'Dotarcie wody do komórek liścia', 'Odparowanie wody przez aparaty szparkowe'],
      wyjasnienie: 'Woda pobrana przez korzeń wędruje w górę rośliny tkanką przewodzącą (ksylemem), dociera do komórek liścia, a nadmiar odparowuje przez aparaty szparkowe w procesie transpiracji.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t110-10',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Cienka warstwa komórek pokrywająca liść od zewnątrz, zawierająca aparaty szparkowe i chroniąca przed nadmierną utratą wody, to:',
      opcje: ['Tkanka twórcza', 'Tkanka okrywająca', 'Tkanka wzmacniająca', 'Tkanka przewodząca'],
      poprawna: 1,
      wyjasnienie: 'Opisana warstwa to tkanka okrywająca (skórka) — chroni roślinę i zawiera aparaty szparkowe umożliwiające wymianę gazową oraz kontrolę utraty wody.',
      umiejetnosci: ['analiza'],
    },
    {
      id: 'p-t110-11',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Tkanka mięśniowa zbudowana jest z komórek niezdolnych do zmiany kształtu.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — komórki tkanki mięśniowej są właśnie zdolne do kurczenia się (zmiany kształtu), co umożliwia ruch.',
      umiejetnosci: ['budowa-funkcja'],
    },
    {
      id: 'p-t110-12',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które zdania o tkance nabłonkowej są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Pokrywa ciało z zewnątrz i wyściela narządy wewnętrzne',
        'Jej komórki są ściśle do siebie przylegające',
        'Zawiera bardzo obfitą istotę międzykomórkową',
        'Może tworzyć gruczoły wydzielające substancje',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Tkanka nabłonkowa pokrywa ciało i wyściela narządy, ma ściśle przylegające komórki i tworzy gruczoły. Obfita istota międzykomórkowa jest cechą tkanki łącznej, nie nabłonkowej.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t110-13',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Wierzchołek pędu młodej rośliny został uszkodzony przez mróz. Który proces zostanie tym najbardziej ograniczony?',
      opcje: [
        'Fotosynteza we wszystkich liściach rośliny',
        'Wzrost pędu na długość',
        'Transport wody przez ksylem w korzeniu',
        'Magazynowanie substancji zapasowych w miękiszu',
      ],
      poprawna: 1,
      wyjasnienie: 'Na wierzchołkach pędów znajduje się tkanka twórcza (merystem wierzchołkowy), odpowiedzialna za wzrost pędu na długość. Jej uszkodzenie najsilniej ograniczy właśnie ten proces.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t110-14',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Dopasuj tkankę zwierzęcą do struktury, w której odgrywa główną rolę.',
      dopasowanie: {
        lewa: ['Tkanka nabłonkowa', 'Tkanka łączna', 'Tkanka mięśniowa', 'Tkanka nerwowa'],
        prawa: ['Naskórek', 'Kość', 'Serce', 'Mózg'],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Naskórek buduje tkanka nabłonkowa, kość — tkanka łączna, serce — głównie tkanka mięśniowa, a mózg — tkanka nerwowa.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t110-15',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie dotyczące funkcji tkanek roślinnych.',
      tekstZLuka: 'Tkanka {{luka1}} usztywnia organy rośliny i pozwala jej utrzymać kształt, natomiast tkanka {{luka2}} gromadzi materiały zapasowe, np. skrobię.',
      odpowiedziLuk: { luka1: ['wzmacniająca'], luka2: ['miękiszowa (spichrzowa)', 'miękiszowa', 'spichrzowa'] },
      wyjasnienie: 'Tkanka wzmacniająca nadaje roślinie sztywność i podporę, a miękisz spichrzowy magazynuje substancje zapasowe, takie jak skrobia.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t110-16',
      dzialId: 'd1',
      tematId: 't110',
      typ: 'ordering',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uporządkuj etapy powstawania wyspecjalizowanej komórki tkanki, zaczynając od komórki macierzystej.',
      elementy: ['Komórka macierzysta tkanki twórczej', 'Podział komórkowy', 'Różnicowanie (specjalizacja) komórki potomnej', 'Dojrzała komórka wyspecjalizowanej tkanki'],
      wyjasnienie: 'Komórki tkanki twórczej dzielą się, a powstałe komórki potomne różnicują się, czyli zmieniają budowę odpowiednio do pełnionej funkcji, stając się dojrzałymi komórkami określonej tkanki.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
  ]);
})();
