(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t204-tkanki-01',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Która tkanka roślinna jako jedyna zachowuje zdolność do intensywnych podziałów komórkowych i umożliwia wzrost rośliny?',
      opcje: ['Tkanka twórcza', 'Tkanka okrywająca', 'Tkanka miękiszowa', 'Tkanka wzmacniająca'],
      poprawna: 0,
      wyjasnienie: 'Tkanka twórcza (merystematyczna) jako jedyna intensywnie się dzieli. Pozostałe wymienione tkanki są tkankami stałymi.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-tkanki-02',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Aparaty szparkowe umożliwiają roślinie wymianę gazową i regulację utraty wody.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'Aparaty szparkowe, zbudowane z dwóch komórek szparkowych, otwierają się i zamykają, regulując wymianę gazową oraz transpirację (parowanie wody).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-tkanki-03',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Tkanka, która pokrywa powierzchnię rośliny i chroni ją przed nadmiernym parowaniem oraz urazami, to:',
      opcje: ['tkanka przewodząca', 'tkanka okrywająca', 'tkanka wzmacniająca', 'tkanka twórcza'],
      poprawna: 1,
      wyjasnienie: 'Tkanka okrywająca (epiderma, a u roślin drzewiastych korek) chroni roślinę od zewnątrz.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-tkanki-04',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie: Woda i sole mineralne płyną od korzeni do liści tkanką, którą nazywamy {{luka1}}. Produkty fotosyntezy rozprowadzane są po roślinie tkanką, którą nazywamy {{luka2}}.',
      tekstZLuka: 'Woda i sole mineralne płyną od korzeni do liści tkanką, którą nazywamy {{luka1}}. Produkty fotosyntezy rozprowadzane są po roślinie tkanką, którą nazywamy {{luka2}}.',
      odpowiedziLuk: { luka1: ['drewno', 'ksylem'], luka2: ['łyko', 'floem'] },
      wyjasnienie: 'Drewno (ksylem) transportuje wodę i sole mineralne, a łyko (floem) — produkty fotosyntezy.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-tkanki-05',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Merystemy wierzchołkowe u roślin odpowiadają przede wszystkim za:',
      opcje: ['wzrost rośliny na długość', 'magazynowanie skrobi', 'wymianę gazową', 'transport wody'],
      poprawna: 0,
      wyjasnienie: 'Merystemy wierzchołkowe znajdują się na szczytach pędów i korzeni i odpowiadają za wzrost długościowy. Za przyrost grubości odpowiada merystem boczny — kambium.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-tkanki-06',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Komórki budujące ksylem (drewno) są w większości żywe i aktywnie transportują wodę dzięki pracy własnych mitochondriów.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — dojrzałe komórki ksylemu są martwe. Woda przemieszcza się przez nie biernie, dzięki różnicy ciśnień powstającej m.in. wskutek parowania wody z liści (transpiracji).',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t204-tkanki-07',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj tkankę roślinną do jej głównej funkcji.',
      dopasowanie: {
        lewa: ['Tkanka twórcza', 'Tkanka okrywająca', 'Tkanka miękiszowa', 'Tkanka wzmacniająca'],
        prawa: ['Umożliwia podziały komórkowe i wzrost rośliny', 'Fotosynteza i magazynowanie substancji zapasowych', 'Usztywnia organy rośliny', 'Chroni przed parowaniem i urazami mechanicznymi'],
        pary: [0, 3, 1, 2],
      },
      wyjasnienie: 'Tkanka twórcza dzieli się i umożliwia wzrost, miękiszowa prowadzi fotosyntezę i magazynuje substancje, wzmacniająca usztywnia organy, a okrywająca chroni roślinę od zewnątrz.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-tkanki-08',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych tkanek zaliczamy do tkanek stałych (trwałych), niezdolnych już do intensywnych podziałów? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Tkanka twórcza (merystematyczna)', 'Tkanka okrywająca', 'Tkanka miękiszowa', 'Tkanka przewodząca'],
      poprawna: [1, 2, 3],
      wyjasnienie: 'Tkanki okrywająca, miękiszowa i przewodząca (a także wzmacniająca) to tkanki stałe. Jedynie tkanka twórcza zachowuje zdolność do podziałów.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t204-tkanki-09',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego drewno (ksylem) może skutecznie transportować wodę, mimo że jego dojrzałe komórki są martwe?',
      opcje: [
        'Ponieważ martwe, zdrewniałe komórki tworzą ciągłe rurki, którymi woda przemieszcza się biernie dzięki sile parowania z liści i włoskowatości',
        'Ponieważ martwe komórki aktywnie pompują wodę, wykorzystując energię z oddychania komórkowego',
        'Ponieważ woda jest transportowana przez dyfuzję przez cytoplazmę żywych komórek ksylemu',
        'Ponieważ ksylem zawiera specjalne pompy jonowe transportujące wodę pod ciśnieniem',
      ],
      poprawna: 0,
      wyjasnienie: 'Martwe komórki ksylemu tworzą puste, połączone ze sobą rurki. Woda jest w nich transportowana biernie — "ciągnięta" siłą parowania wody z liści (transpiracji) i wspomagana zjawiskiem włoskowatości, bez udziału procesów energetycznych samych komórek.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-tkanki-10',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj wymienione tkanki zgodnie z ich położeniem na przekroju poprzecznym typowej łodygi rośliny okrytonasiennej — od powierzchni (na zewnątrz) do środka.',
      elementy: ['Skórka (epiderma)', 'Kora (miękisz)', 'Łyko (floem)', 'Drewno (ksylem)', 'Rdzeń (miękisz rdzenia)'],
      wyjasnienie: 'Na typowym przekroju łodygi warstwy układają się od zewnątrz: skórka, kora, łyko, drewno, a w samym środku rdzeń — zgodnie ze schematem przekroju poprzecznego.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t204-tkanki-11',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'diagram',
      poziom: 'trudny',
      punkty: 2,
      diagramId: 'd-t204-tkanki-przekroj',
      tresc: 'Na schemacie przedstawiono uproszczony przekrój poprzeczny łodygi rośliny okrytonasiennej z ponumerowanymi warstwami tkanek (1 — najbardziej zewnętrzna, 5 — środek). Element oznaczony numerem 4 to tkanka transportująca wodę i sole mineralne od korzeni do liści. Jak się ona nazywa?',
      opcje: ['Łyko (floem)', 'Drewno (ksylem)', 'Kora (miękisz)', 'Skórka (epiderma)'],
      poprawna: 1,
      wyjasnienie: 'Numer 4, leżący bliżej środka łodygi niż łyko, oznacza drewno (ksylem) — tkankę transportującą wodę i sole mineralne od korzeni do liści.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-tkanki-12',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych stwierdzeń są prawdziwe dla tkanki wzmacniającej (kolenchymy i sklerenchymy)? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Usztywnia organy rośliny i pozwala jej utrzymać kształt',
        'Umożliwia intensywne podziały komórkowe',
        'Występuje m.in. w łodygach i ogonkach liściowych, gdzie zwiększa ich wytrzymałość mechaniczną',
        'Jest jedynym miejscem zachodzenia fotosyntezy w roślinie',
      ],
      poprawna: [0, 2],
      wyjasnienie: 'Tkanka wzmacniająca usztywnia organy rośliny i zwiększa ich wytrzymałość mechaniczną. Podziały komórkowe są domeną tkanki twórczej, a fotosynteza zachodzi głównie w miękiszu asymilacyjnym.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-tkanki-13',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Roślina rosnąca w miejscu silnie nasłonecznionym i suchym ma zwykle grubszą warstwę woskowej kutykuli na powierzchni epidermy liści niż roślina rosnąca w cieniu i wilgoci. Jak najlepiej wyjaśnić znaczenie adaptacyjne tej cechy?',
      opcje: [
        'Grubsza kutykula ogranicza nadmierne parowanie wody przez epidermę, co chroni roślinę przed utratą wody w suchym środowisku',
        'Grubsza kutykula zwiększa tempo fotosyntezy w komórkach miękiszu asymilacyjnego',
        'Grubsza kutykula umożliwia intensywniejsze podziały komórek tkanki twórczej',
        'Grubsza kutykula zastępuje aparaty szparkowe w wymianie gazowej',
      ],
      poprawna: 0,
      wyjasnienie: 'Kutykula to woskowa warstwa na powierzchni epidermy, ograniczająca parowanie wody. Jej pogrubienie u roślin siedlisk suchych i nasłonecznionych to przystosowanie zmniejszające utratę wody, a nie zmiana dotycząca fotosyntezy czy podziałów komórkowych.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t204-tkanki-14',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Kambium, będące merystemem bocznym, odpowiada za przyrost grubości łodygi i korzenia, wytwarzając nowe komórki drewna i łyka.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'Kambium to merystem boczny leżący między drewnem a łykiem; jego podziały wytwarzają nowe komórki drewna (do wewnątrz) i łyka (na zewnątrz), powodując przyrost grubości.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-tkanki-15',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie: Merystem znajdujący się na szczycie pędu lub korzenia to merystem {{luka1}}, natomiast merystem leżący wewnątrz łodygi i odpowiadający za przyrost na grubość to {{luka2}}.',
      tekstZLuka: 'Merystem znajdujący się na szczycie pędu lub korzenia to merystem {{luka1}}, natomiast merystem leżący wewnątrz łodygi i odpowiadający za przyrost na grubość to {{luka2}}.',
      odpowiedziLuk: { luka1: ['wierzchołkowy'], luka2: ['kambium', 'boczny'] },
      wyjasnienie: 'Merystem wierzchołkowy wydłuża pęd i korzeń, a merystem boczny (kambium) powoduje przyrost grubości.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-tkanki-16',
      dzialId: 'd2',
      tematId: 't204-tkanki',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dopasuj typ miękiszu do jego funkcji lub lokalizacji.',
      dopasowanie: {
        lewa: ['Miękisz asymilacyjny', 'Miękisz spichrzowy', 'Miękisz powietrzny'],
        prawa: ['Magazynuje substancje zapasowe, np. skrobię, w bulwach i nasionach', 'Bogaty w chloroplasty, prowadzi fotosyntezę, głównie w liściach', 'Zawiera duże przestrzenie międzykomórkowe wypełnione powietrzem, występuje u roślin wodnych i bagiennych'],
        pary: [1, 0, 2],
      },
      wyjasnienie: 'Miękisz asymilacyjny fotosyntetyzuje w liściach, spichrzowy magazynuje substancje zapasowe, a powietrzny ułatwia wymianę gazową u roślin wodnych i bagiennych.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
  ]);
})();
