(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t104-01',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Który z poniższych związków jest monosacharydem (cukrem prostym)?',
      opcje: ['Glukoza', 'Sacharoza', 'Skrobia', 'Glikogen'],
      poprawna: 0,
      wyjasnienie: 'Glukoza jest najważniejszym monosacharydem — najprostszym węglowodanem, który nie ulega dalszej hydrolizie na mniejsze cukry. Sacharoza to disacharyd, a skrobia i glikogen to polisacharydy.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t104-02',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Disacharydy powstają z połączenia dwóch cząsteczek monosacharydów wiązaniem glikozydowym.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — disacharydy (dwucukry), np. sacharoza, laktoza czy maltoza, powstają w reakcji kondensacji dwóch cząsteczek monosacharydów, połączonych wiązaniem glikozydowym z uwolnieniem cząsteczki wody.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t104-03',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Który związek jest podstawowym substratem (materiałem wyjściowym) oddychania komórkowego, dostarczającym energii komórkom?',
      opcje: ['Glukoza', 'Celuloza', 'Chityna', 'Sacharoza'],
      poprawna: 0,
      wyjasnienie: 'Glukoza jest podstawowym "paliwem" komórek — to główny substrat oddychania komórkowego, w którym uwalniana jest energia potrzebna do procesów życiowych.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t104-04',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które stwierdzenie o glikogenie jest prawdziwe?',
      opcje: [
        'Jest zapasowym polisacharydem zwierząt, magazynowanym głównie w wątrobie i mięśniach',
        'Jest budulcowym polisacharydem tworzącym ściany komórkowe grzybów',
        'Jest monosacharydem wykorzystywanym bezpośrednio w oddychaniu komórkowym',
        'Jest disacharydem obecnym w mleku ssaków',
      ],
      poprawna: 0,
      wyjasnienie: 'Glikogen to zapasowy polisacharyd zwierząt — zbudowany z cząsteczek glukozy, magazynowany głównie w wątrobie i mięśniach jako rezerwa energii, którą organizm może szybko wykorzystać.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t104-05',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Skrobia i celuloza są zbudowane z tych samych cząsteczek glukozy, ale skrobia jest zapasowym materiałem energetycznym trawionym przez człowieka, a celuloza buduje ścianę komórkową roślin i nie jest przez człowieka trawiona. Co jest bezpośrednią przyczyną tej różnicy?',
      opcje: [
        'Inny rodzaj wiązania glikozydowego łączącego cząsteczki glukozy',
        'Odmienna liczba atomów tlenu w cząsteczkach glukozy budujących oba związki',
        'Obecność azotu w cząsteczkach celulozy, którego nie ma w skrobi',
        'Rozpuszczalność skrobi w tłuszczach, w przeciwieństwie do celulozy',
      ],
      poprawna: 0,
      wyjasnienie: 'Skrobia i celuloza zbudowane są z identycznych cząsteczek glukozy, lecz połączonych innym rodzajem wiązania glikozydowego. Enzymy trawienne człowieka (np. amylaza) potrafią rozkładać wiązania obecne w skrobi, ale nie rozpoznają wiązań w celulozie — dlatego celuloza przechodzi przez układ pokarmowy nienaruszona jako błonnik.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t104-06',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z wymienionych związków są polisacharydami? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Skrobia', 'Sacharoza', 'Celuloza', 'Fruktoza', 'Glikogen'],
      poprawna: [0, 2, 4],
      wyjasnienie: 'Skrobia, celuloza i glikogen to polisacharydy — długie łańcuchy zbudowane z wielu cząsteczek glukozy. Sacharoza to disacharyd, a fruktoza to monosacharyd.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t104-07',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 3,
      tresc: 'Dopasuj polisacharyd do organizmu i funkcji, którą u niego pełni.',
      dopasowanie: {
        lewa: ['Skrobia', 'Glikogen', 'Celuloza', 'Chityna'],
        prawa: ['Materiał zapasowy zwierząt (wątroba, mięśnie)', 'Materiał zapasowy roślin (bulwy, nasiona)', 'Ściana komórkowa roślin', 'Pancerzyk stawonogów i ściany komórkowe grzybów'],
        pary: [1, 0, 2, 3],
      },
      wyjasnienie: 'Skrobia to materiał zapasowy roślin, glikogen — zapasowy polisacharyd zwierząt. Celuloza buduje ścianę komórkową roślin, a chityna — pancerzyki stawonogów i ściany komórkowe grzybów.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t104-08',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdania właściwymi pojęciami.',
      tekstZLuka: 'Cukry proste, które nie ulegają dalszej hydrolizie, nazywamy {{luka1}}. Połączenie dwóch cząsteczek cukru prostego wiązaniem glikozydowym tworzy {{luka2}}.',
      odpowiedziLuk: { luka1: ['monosacharydami', 'monosacharydy'], luka2: ['disacharyd', 'dwucukier', 'disacharydem', 'dwucukrem'] },
      wyjasnienie: 'Najprostsze węglowodany, nieulegające dalszej hydrolizie, to monosacharydy. Dwie połączone cząsteczki monosacharydów tworzą disacharyd (dwucukier).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t104-09',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj węglowodany od cząsteczki najprostszej do najbardziej złożonej.',
      elementy: ['Monosacharyd (np. glukoza)', 'Disacharyd (np. sacharoza)', 'Polisacharyd (np. skrobia)'],
      wyjasnienie: 'Monosacharydy to pojedyncze cząsteczki cukru prostego, disacharydy powstają z połączenia dwóch monosacharydów, a polisacharydy to długie łańcuchy wielu połączonych ze sobą monosacharydów.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t104-10',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Amylaza trawienna człowieka rozkłada wiązania glikozydowe w skrobi, ale nie potrafi rozłożyć takich samych rodzajowo wiązań w celulozie, mimo że oba związki zbudowane są z glukozy. Co ten fakt najlepiej pokazuje?',
      opcje: [
        'Enzymy rozpoznają konkretny, ściśle określony typ wiązania chemicznego, a nie tylko rodzaj połączonych nim cząsteczek',
        'Celuloza w ogóle nie zawiera atomów węgla',
        'Amylaza działa wyłącznie na disacharydy, a nigdy na polisacharydy',
        'Skrobia nie zawiera żadnych wiązań glikozydowych',
      ],
      poprawna: 0,
      wyjasnienie: 'Skrobia i celuloza są zbudowane z tych samych cząsteczek glukozy, ale połączonych innym rodzajem wiązania glikozydowego. To pokazuje, że enzymy działają w sposób wysoce specyficzny — rozpoznają konkretny kształt wiązania, a nie tylko skład chemiczny cząsteczek.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t104-11',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Które stwierdzenia o funkcjach węglowodanów są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Glukoza jest głównym substratem oddychania komórkowego',
        'Celuloza pełni funkcję budulcową u roślin',
        'Glikogen jest głównym budulcem ścian komórkowych zwierząt',
        'Skrobia jest materiałem zapasowym magazynowanym m.in. w bulwach i nasionach',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Glukoza jest głównym substratem oddychania, celuloza pełni funkcję budulcową (ściana komórkowa roślin), a skrobia jest materiałem zapasowym roślin. Komórki zwierzęce nie mają ścian komórkowych, więc glikogen (materiał zapasowy zwierząt) nie pełni takiej funkcji.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t104-12',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż polisacharyd, który u grzybów wchodzi w skład ściany komórkowej.',
      tabela: {
        tytul: 'Wybrane polisacharydy i ich rola biologiczna',
        kolumny: ['Polisacharyd', 'Organizm', 'Funkcja'],
        wiersze: [
          ['Skrobia', 'Rośliny', 'Zapasowa (bulwy, nasiona)'],
          ['Glikogen', 'Zwierzęta', 'Zapasowa (wątroba, mięśnie)'],
          ['Celuloza', 'Rośliny', 'Budulcowa (ściana komórkowa)'],
          ['Chityna', 'Stawonogi, grzyby', 'Budulcowa (pancerzyk, ściana komórkowa)'],
        ],
      },
      opcje: ['Skrobia', 'Glikogen', 'Celuloza', 'Chityna'],
      poprawna: 3,
      wyjasnienie: 'Zgodnie z tabelą chityna pełni funkcję budulcową u stawonogów (pancerzyki) i grzybów (ściana komórkowa) — jest jedynym z wymienionych polisacharydów wspólnym dla obu tych grup organizmów.',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t104-13',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'image',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na diagramie podziału węglowodanów grupa oznaczona numerem 3 obejmuje m.in. skrobię i celulozę. Jak nazywa się ta grupa węglowodanów?',
      diagramId: 'd-t104-podzial-cukrow',
      opcje: ['Monosacharydy', 'Disacharydy', 'Polisacharydy', 'Aminokwasy'],
      poprawna: 2,
      wyjasnienie: 'Skrobia, celuloza i glikogen to polisacharydy — na diagramie oznaczone numerem 3, jako grupa węglowodanów zbudowanych z bardzo wielu połączonych cząsteczek monosacharydów.',
      umiejetnosci: ['diagram', 'wiedza'],
    },
    {
      id: 'p-t104-14',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Osoba z nietolerancją laktozy nie wytwarza wystarczającej ilości enzymu rozkładającego laktozę na glukozę i galaktozę. Nierozłożona laktoza trafia do jelita grubego, gdzie jest fermentowana przez bakterie, co powoduje wzdęcia i biegunkę. Co to zjawisko najlepiej ilustruje?',
      opcje: [
        'Znaczenie hydrolizy wiązania glikozydowego dla wchłaniania węglowodanów w jelicie',
        'Fakt, że laktoza jest polisacharydem podobnym do skrobi',
        'Fakt, że bakterie jelitowe samodzielnie produkują skrobię',
        'Nietolerancja pokarmowa dotyczy wyłącznie tłuszczów',
      ],
      poprawna: 0,
      wyjasnienie: 'Laktoza (disacharyd) musi zostać rozłożona (hydroliza wiązania glikozydowego) na monosacharydy, by mogła zostać wchłonięta przez ścianę jelita cienkiego. Bez odpowiedniego enzymu nierozłożona laktoza pozostaje w przewodzie pokarmowym i jest fermentowana przez bakterie jelita grubego, co wywołuje objawy nietolerancji.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t104-15',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Błonnik pokarmowy (m.in. celuloza) nie dostarcza organizmowi człowieka energii, ale odgrywa ważną rolę w prawidłowym funkcjonowaniu układu pokarmowego.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda. Człowiek nie trawi celulozy, więc nie dostarcza ona energii, ale pobudza perystaltykę jelit i wspomaga prawidłowe funkcjonowanie układu pokarmowego, dlatego jest ważnym składnikiem diety mimo braku wartości energetycznej.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t104-16',
      dzialId: 'd1',
      tematId: 't104',
      typ: 'gapfill',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Uzupełnij zdanie dotyczące polisacharydów zapasowych.',
      tekstZLuka: 'U zwierząt zapasowym polisacharydem magazynowanym głównie w wątrobie i mięśniach jest {{luka1}}, natomiast u roślin analogiczną funkcję pełni {{luka2}}, magazynowana np. w bulwach i nasionach.',
      odpowiedziLuk: { luka1: ['glikogen'], luka2: ['skrobia'] },
      wyjasnienie: 'Glikogen to zapasowy polisacharyd zwierząt (wątroba, mięśnie), a jego roślinnym odpowiednikiem funkcjonalnym jest skrobia, magazynowana w bulwach i nasionach.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
  ]);
})();
