(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t204-paprociowe-01',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Paprocie, w odróżnieniu od mchów, są roślinami:',
      opcje: ['naczyniowymi (mają tkanki przewodzące)', 'nasiennymi', 'beznaczyniowymi', 'plechowymi'],
      poprawna: 0,
      wyjasnienie: 'Paprocie mają prawdziwe tkanki przewodzące (ksylem i floem), dlatego są roślinami naczyniowymi — w odróżnieniu od beznaczyniowych mchów.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-paprociowe-02',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Paprocie rozmnażają się za pomocą nasion.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — paprocie są roślinami zarodnikowymi i rozmnażają się za pomocą zarodników, a nie nasion.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-paprociowe-03',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Charakterystyczne skupienia zarodni widoczne na spodniej stronie liści paproci to:',
      opcje: ['sorusy', 'szyszki', 'kwiaty', 'bulwy'],
      poprawna: 0,
      wyjasnienie: 'Sorusy to skupienia zarodni na spodniej stronie liścia paproci, w których w wyniku mejozy powstają zarodniki.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-paprociowe-04',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie: Podziemna lub płożąca się łodyga paproci nazywana jest {{luka1}}, a wyrastające z niej korzenie to korzenie {{luka2}}.',
      tekstZLuka: 'Podziemna lub płożąca się łodyga paproci nazywana jest {{luka1}}, a wyrastające z niej korzenie to korzenie {{luka2}}.',
      odpowiedziLuk: { luka1: ['kłączem'], luka2: ['przybyszowe'] },
      wyjasnienie: 'Kłącze to podziemna łodyga paproci, z której wyrastają liście i korzenie przybyszowe.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-paprociowe-05',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dlaczego paprocie mogą osiągać większe rozmiary niż mchy?',
      opcje: [
        'Ponieważ mają tkanki przewodzące, które umożliwiają transport wody i substancji odżywczych na większe odległości',
        'Ponieważ rozmnażają się nasionami, a nie zarodnikami',
        'Ponieważ żyją wyłącznie w środowisku wodnym',
        'Ponieważ nie potrzebują wody do rozmnażania',
      ],
      poprawna: 0,
      wyjasnienie: 'Obecność tkanek przewodzących (ksylemu i floemu) pozwala paproci transportować wodę i substancje odżywcze na większe odległości, co umożliwia większy wzrost — w przeciwieństwie do beznaczyniowych mchów.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-paprociowe-06',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Widoczna, duża roślina paproci z liśćmi, którą spotykamy w lesie, to gametofit.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — widoczna roślina paproci z liśćmi to sporofit. Gametofit to małe, sercowate przedrośle.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-paprociowe-07',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj pojęcie do jego opisu.',
      dopasowanie: {
        lewa: ['Sporofit', 'Gametofit (przedrośle)', 'Sorus', 'Kłącze'],
        prawa: [
          'Dominujące pokolenie paproci, widoczne jako roślina z liśćmi',
          'Małe, sercowate pokolenie płciowe wytwarzające plemnie i rodnie',
          'Skupienie zarodni na spodniej stronie liścia',
          'Podziemna łodyga, z której wyrastają liście i korzenie przybyszowe',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Sporofit to dojrzała roślina z liśćmi, gametofit to przedrośle, sorus to skupienie zarodni, a kłącze to podziemna łodyga paproci.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-paprociowe-08',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które struktury lub cechy są typowe dla paproci? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Obecność tkanek przewodzących', 'Korzenie przybyszowe', 'Nasiona ukryte w owocu', 'Sorusy na spodniej stronie liści'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Paprocie mają tkanki przewodzące, korzenie przybyszowe i sorusy na liściach. Nie wytwarzają nasion ani owoców — są roślinami zarodnikowymi.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t204-paprociowe-09',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego rozmnażanie płciowe paproci, podobnie jak mchów, jest ściśle uzależnione od obecności wody?',
      opcje: [
        'Ponieważ plemniki wytwarzane w plemniach przedrośla muszą przepłynąć w wodzie do rodni, aby zapłodnić komórkę jajową',
        'Ponieważ zarodniki kiełkują wyłącznie pod powierzchnią wody',
        'Ponieważ korzenie przybyszowe pobierają wodę tylko w okresie rozmnażania',
        'Ponieważ sorusy otwierają się wyłącznie w wodzie',
      ],
      poprawna: 0,
      wyjasnienie: 'Plemniki paproci muszą aktywnie przepłynąć w cienkiej warstwie wody od plemni do rodni na przedroślu, aby doszło do zapłodnienia komórki jajowej.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t204-paprociowe-10',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Uporządkuj etapy cyklu rozwojowego paproci, zaczynając od dojrzałego sporofitu.',
      elementy: [
        'Dojrzały sporofit (paproć) wytwarza sorusy z zarodniami na spodniej stronie liści',
        'Powstanie zarodników w zarodniach w wyniku mejozy',
        'Kiełkowanie zarodnika w przedrośle (gametofit)',
        'Wytworzenie przez przedrośle plemni i rodni oraz zapłodnienie w obecności wody',
        'Rozwój nowego sporofitu z zapłodnionej komórki jajowej',
      ],
      wyjasnienie: 'Cykl rozwojowy paproci przebiega: sporofit z sorusami → zarodniki (mejoza) → przedrośle (gametofit) → zapłodnienie w wodzie → nowy sporofit.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t204-paprociowe-11',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Paprocie zaliczamy do roślin zarodnikowych naczyniowych. Co oznacza określenie „naczyniowe”?',
      opcje: [
        'Mają prawdziwe tkanki przewodzące (ksylem i floem)',
        'Żyją wyłącznie w środowisku wodnym',
        'Mają kwiaty i owoce',
        'Rozmnażają się wyłącznie wegetatywnie',
      ],
      poprawna: 0,
      wyjasnienie: 'Rośliny naczyniowe to takie, które mają wykształcone tkanki przewodzące — ksylem (drewno) i floem (łyko).',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-paprociowe-12',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych stwierdzeń dotyczących paproci są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Dominującym pokoleniem jest sporofit', 'Gametofit to małe, zielone przedrośle', 'Paprocie wytwarzają szyszki', 'Zarodniki powstają w sorusach w wyniku mejozy'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'U paproci dominuje sporofit, gametofitem jest przedrośle, a zarodniki powstają w zarodniach (sorusach) w wyniku mejozy. Szyszki są charakterystyczne dla roślin nagonasiennych, nie paproci.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-paprociowe-13',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'W wilgotnym, cienistym lesie liczne paprocie rosną obficie pod okapem drzew, natomiast na suchej, nasłonecznionej polanie w pobliżu ich liczba gwałtownie maleje. Co najlepiej to tłumaczy?',
      opcje: [
        'Zależność rozmnażania płciowego paproci od wody (potrzebnej plemnikom do dotarcia do rodni) oraz silne parowanie wody z dużych liści w suchym, nasłonecznionym miejscu',
        'Paprocie rosnące w lesie i na polanie to zupełnie inne, niespokrewnione gatunki',
        'Paprocie potrzebują wyłącznie bezpośredniego, silnego światła słonecznego do fotosyntezy',
        'Korzenie przybyszowe paproci nie potrafią pobierać wody z gleby',
      ],
      poprawna: 0,
      wyjasnienie: 'Rozmnażanie płciowe paproci wymaga wody dla ruchu plemników, a duże liście silnie parują wodę w warunkach suchych i nasłonecznionych — dlatego paprocie preferują wilgotne, cieniste środowiska.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t204-paprociowe-14',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Skamieniałości paproci i innych roślin zarodnikowych z okresu karbonu są związane z powstawaniem pokładów węgla kamiennego.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'Obumierające warstwami, olbrzymie rośliny zarodnikowe (w tym paprocie) z lasów karbońskich, gromadząc się w warunkach niedoboru tlenu, z czasem przekształciły się w węgiel kamienny.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t204-paprociowe-15',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie: Młode liście paproci są charakterystycznie zwinięte w strukturę zwaną {{luka1}}, a wyrastają z podziemnej łodygi zwanej {{luka2}}.',
      tekstZLuka: 'Młode liście paproci są charakterystycznie zwinięte w strukturę zwaną {{luka1}}, a wyrastają z podziemnej łodygi zwanej {{luka2}}.',
      odpowiedziLuk: { luka1: ['ślimacznicą', 'ślimacznica'], luka2: ['kłączem', 'kłącze'] },
      wyjasnienie: 'Młody liść paproci jest zwinięty w ślimacznicę i rozwija się stopniowo, wyrastając z kłącza.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-paprociowe-16',
      dzialId: 'd2',
      tematId: 't204-paprociowe',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dopasuj etap cyklu rozwojowego paproci do jego opisu.',
      dopasowanie: {
        lewa: ['Sporofit (paproć)', 'Zarodniki', 'Gametofit (przedrośle)', 'Zygota'],
        prawa: [
          'Dojrzała roślina wytwarzająca sorusy z zarodniami na liściach',
          'Haploidalne komórki powstałe w zarodni w wyniku mejozy, kiełkujące w przedrośle',
          'Małe, sercowate pokolenie płciowe wytwarzające plemnie i rodnie',
          'Komórka powstała z połączenia plemnika i komórki jajowej, z której rozwija się nowy sporofit',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Sporofit wytwarza zarodniki, te kiełkują w gametofit (przedrośle), który wytwarza gamety — ich połączenie daje zygotę, z której rozwija się nowy sporofit.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
  ]);
})();
