(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t117-k1',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Które zdanie poprawnie opisuje homeostazę?',
      opcje: [
        'To zdolność organizmu do utrzymywania stałych warunków środowiska wewnętrznego mimo zmian zachodzących w otoczeniu',
        'To jednorazowa, szybka reakcja organizmu na pojedynczy bodziec',
        'To zdolność wyłącznie roślin do wzrostu w stronę światła',
        'To proces występujący tylko u organizmów jednokomórkowych',
      ],
      poprawna: 0,
      wyjasnienie:
        'Homeostaza to zdolność organizmu do utrzymywania względnie stałych warunków środowiska wewnętrznego (np. temperatury ciała, stężenia glukozy we krwi) niezależnie od zmian zachodzących w otoczeniu. To proces ciągły, a nie pojedyncze zdarzenie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t117-k2',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Termoregulacja jest jedynym mechanizmem homeostazy występującym u organizmów.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie:
        'Fałsz — termoregulacja (utrzymywanie stałej temperatury ciała) to tylko jeden z mechanizmów homeostazy. Obejmuje ona również m.in. regulację ilości wody w organizmie oraz stężenia glukozy i innych substancji we krwi.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t117-03',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Które z poniższych jest przykładem receptora odbierającego bodziec świetlny?',
      opcje: ['Mięsień ramienia', 'Oko', 'Gruczoł potowy', 'Rdzeń kręgowy'],
      poprawna: 1,
      wyjasnienie:
        'Oko jest narządem zmysłu (receptorem) odbierającym światło i zamieniającym jego energię na impuls nerwowy. Mięsień i gruczoł to przykłady efektorów, a rdzeń kręgowy to ośrodek nerwowy.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t117-04',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdania dotyczące łuku odruchowego.',
      tekstZLuka:
        'Droga, jaką przebywa impuls nerwowy podczas odruchu, nazywana jest {{luka1}}. Narząd wykonujący reakcję na bodziec, np. mięsień, to {{luka2}}.',
      odpowiedziLuk: { luka1: ['łukiem odruchowym', 'łuk odruchowy'], luka2: ['efektor', 'efektorem'] },
      wyjasnienie:
        'Łuk odruchowy to droga przewodzenia impulsu nerwowego podczas odruchu (receptor → ośrodek nerwowy → efektor), a efektor to narząd wykonujący reakcję organizmu na bodziec.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t117-05',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc:
        'Uczeń dotknął gorącego żelazka i natychmiast cofnął rękę, zanim jeszcze świadomie poczuł ból. Co najlepiej to tłumaczy?',
      opcje: [
        'Reakcja przebiegła drogą łuku odruchowego przez rdzeń kręgowy, co pozwoliło na bardzo szybką odpowiedź, zanim sygnał bólu dotarł do mózgu i został świadomie odebrany',
        'Uczeń świadomie zaplanował ruch cofnięcia ręki, zanim dotknął żelazka',
        'Ból nie został w ogóle odebrany przez żaden receptor',
        'To przykład homeostazy, a nie odruchu',
      ],
      poprawna: 0,
      wyjasnienie:
        'Odruchy przebiegają drogą łuku odruchowego, w którym impuls z receptora dociera do rdzenia kręgowego i niemal natychmiast jest przekazywany do efektora (mięśnia) — to znacznie szybsze niż droga przez mózg i świadome odczucie bólu.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t117-06',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Zaznacz wszystkie elementy wchodzące w skład łuku odruchowego.',
      opcje: ['Receptor', 'Ośrodek nerwowy', 'Efektor', 'Tropizm', 'Gameta'],
      poprawna: [0, 1, 2],
      wyjasnienie:
        'Łuk odruchowy tworzą: receptor (odbiera bodziec), ośrodek nerwowy (przetwarza sygnał) i efektor (wykonuje reakcję). Tropizm to reakcja wzrostowa roślin, a gameta to komórka rozrodcza — nie są elementami łuku odruchowego.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t117-07',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj pojęcie do jego definicji.',
      dopasowanie: {
        lewa: ['Bodziec', 'Receptor', 'Efektor', 'Homeostaza'],
        prawa: [
          'Utrzymywanie stałych warunków wewnętrznych organizmu',
          'Czynnik wywołujący reakcję organizmu',
          'Narząd wykonujący reakcję, np. mięsień',
          'Komórka lub narząd odbierający bodziec',
        ],
        pary: [1, 3, 2, 0],
      },
      wyjasnienie:
        'Bodziec to czynnik wywołujący reakcję, receptor odbiera bodziec, efektor wykonuje reakcję (np. skurcz mięśnia), a homeostaza to utrzymywanie stałych warunków wewnętrznych organizmu.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t117-08',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj etapy przebiegu odruchu drogą łuku odruchowego.',
      elementy: [
        'Bodziec pobudza receptor',
        'Impuls nerwowy dociera do ośrodka nerwowego',
        'Sygnał przekazywany jest do efektora',
        'Efektor wykonuje reakcję (np. skurcz mięśnia)',
      ],
      wyjasnienie:
        'Prawidłowa kolejność: bodziec pobudza receptor → impuls dociera do ośrodka nerwowego → sygnał trafia do efektora → efektor wykonuje reakcję.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t117-09',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc:
        'Dlaczego pocenie się i rozszerzanie naczyń krwionośnych skóry w czasie upału jest przykładem homeostazy, a nie zwykłej, jednorazowej reakcji na bodziec?',
      opcje: [
        'Ponieważ zachodzi tylko raz, natychmiast po zadziałaniu bodźca',
        'Ponieważ jest to ciągły, powtarzalny proces służący utrzymaniu stałej temperatury ciała mimo zmieniającej się temperatury otoczenia, a nie pojedyncza odpowiedź na jeden bodziec',
        'Ponieważ dotyczy wyłącznie roślin',
        'Ponieważ nie wymaga udziału żadnych receptorów',
      ],
      poprawna: 1,
      wyjasnienie:
        'Termoregulacja (np. pocenie się, rozszerzanie naczyń krwionośnych) to nieustanny, powtarzalny proces korygowania temperatury ciała w odpowiedzi na stale zmieniające się warunki otoczenia, co odróżnia ją od jednorazowej, krótkotrwałej reakcji na pojedynczy bodziec.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t117-10',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Fototropizm jest przykładem reakcji zwierząt na bodziec świetlny, analogicznej do odruchu.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie:
        'Fałsz — fototropizm to ukierunkowany wzrost części rośliny w stronę światła. Rośliny nie mają układu nerwowego i nie wykonują odruchów — reagują na bodźce znacznie wolniej, poprzez tropizmy związane ze wzrostem.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t117-11',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych są przykładami mechanizmów homeostazy? Zaznacz wszystkie poprawne.',
      opcje: [
        'Pocenie się w upale',
        'Rozszerzanie naczyń krwionośnych skóry w upale',
        'Cofnięcie ręki po dotknięciu gorącego przedmiotu',
        'Dreszcze i zwężanie naczyń krwionośnych w chłodzie',
        'Mrugnięcie okiem po dostrzeżeniu owada lecącego w jego stronę',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie:
        'Pocenie się, rozszerzanie naczyń krwionośnych w upale oraz dreszcze i zwężanie naczyń w chłodzie to mechanizmy termoregulacji służące utrzymaniu stałej temperatury ciała, czyli homeostazie. Cofnięcie ręki i mrugnięcie okiem to szybkie, jednorazowe odruchy obronne, a nie procesy utrzymujące stałość środowiska wewnętrznego.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t117-12',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli porównującej odruch i homeostazę wskaż zdanie prawdziwe.',
      tabela: {
        tytul: 'Odruch a homeostaza',
        kolumny: ['Cecha', 'Odruch', 'Homeostaza'],
        wiersze: [
          ['Czas trwania', 'Krótkotrwały, jednorazowy', 'Ciągły, długotrwały proces'],
          ['Charakter', 'Szybka, pojedyncza reakcja', 'Stałe monitorowanie i korygowanie'],
          ['Przykład', 'Cofnięcie ręki od gorącego przedmiotu', 'Utrzymywanie stałej temperatury ciała'],
        ],
      },
      opcje: [
        'Odruch jest procesem ciągłym trwającym przez całe życie organizmu',
        'Homeostaza polega na pojedynczej, krótkotrwałej reakcji na bodziec',
        'Odruch to szybka, pojedyncza reakcja, a homeostaza to ciągły proces utrzymywania stałości warunków wewnętrznych',
        'Oba procesy są tożsame i zawsze przebiegają w ten sam sposób',
      ],
      poprawna: 2,
      wyjasnienie:
        'Zgodnie z tabelą odruch jest krótkotrwałą, pojedynczą reakcją (np. cofnięcie ręki), a homeostaza to ciągły proces stałego monitorowania i korygowania warunków wewnętrznych organizmu (np. temperatury ciała).',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t117-13',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc:
        'Podczas infekcji organizm może podnieść temperaturę ciała (gorączka), a po ustąpieniu infekcji temperatura wraca do normy. Jak najlepiej opisać ten proces w kontekście homeostazy?',
      opcje: [
        'Gorączka dowodzi, że organizm utracił zdolność do homeostazy',
        'Organizm celowo, tymczasowo przesuwa punkt regulacji temperatury w górę jako reakcję obronną, a mechanizmy homeostazy przywracają normę po ustąpieniu przyczyny — co pokazuje, że homeostaza polega na regulacji, a nie na sztywnej, niezmiennej wartości',
        'Gorączka nie ma żadnego związku z temperaturą ciała',
        'Homeostaza dotyczy wyłącznie stężenia glukozy we krwi, a nie temperatury ciała',
      ],
      poprawna: 1,
      wyjasnienie:
        'Homeostaza nie oznacza, że wartości wewnętrzne organizmu są zawsze identyczne — to zdolność do ich regulacji wokół optymalnego zakresu. Podczas infekcji organizm czasowo podnosi temperaturę (gorączka), co utrudnia namnażanie patogenów, a mechanizmy regulacyjne przywracają normę, gdy infekcja ustępuje. To pokazuje dynamiczny, regulacyjny charakter homeostazy.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t117-14',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dopasuj przykład reakcji organizmu do właściwej kategorii.',
      dopasowanie: {
        lewa: [
          'Cofnięcie ręki po ukłuciu igłą',
          'Utrzymywanie stałego stężenia glukozy we krwi',
          'Wzrost pędu rośliny doniczkowej w stronę okna',
          'Zwężenie źrenicy pod wpływem silnego światła',
        ],
        prawa: [
          'Homeostaza (regulacja wewnętrzna)',
          'Odruch (szybka reakcja przez łuk odruchowy)',
          'Tropizm rośliny (fototropizm)',
          'Odruch (reakcja receptora oka na bodziec świetlny)',
        ],
        pary: [1, 0, 2, 3],
      },
      wyjasnienie:
        'Cofnięcie ręki i zwężenie źrenicy to odruchy przebiegające drogą łuku odruchowego. Utrzymywanie stałego stężenia glukozy we krwi to mechanizm homeostazy. Wzrost pędu rośliny w stronę światła to fototropizm — reakcja wzrostowa niezwiązana z układem nerwowym.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t117-15',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdania precyzyjnymi pojęciami biologicznymi.',
      tekstZLuka:
        'Zdolność organizmu do odbierania bodźców z otoczenia i reagowania na nie nazywamy {{luka1}}. Ukierunkowany wzrost części rośliny w stronę bodźca, np. światła, nazywamy {{luka2}}.',
      odpowiedziLuk: { luka1: ['drażliwością', 'drażliwość', 'pobudliwością', 'pobudliwość'], luka2: ['tropizmem', 'tropizm', 'fototropizmem', 'fototropizm'] },
      wyjasnienie:
        'Drażliwość (pobudliwość) to zdolność odbierania bodźców i reagowania na nie. Tropizm (a konkretnie fototropizm w przypadku reakcji na światło) to ukierunkowany wzrost części rośliny wywołany bodźcem.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t117-16',
      dzialId: 'd1',
      tematId: 't117',
      typ: 'diagram',
      poziom: 'konkursowy',
      punkty: 2,
      diagramId: 'd-t117-luk-odruchowy',
      tresc: 'Na diagramie przedstawiono przebieg łuku odruchowego. Które zdanie poprawnie opisuje przedstawiony schemat?',
      opcje: [
        'Impuls nerwowy przemieszcza się od efektora do receptora',
        'Bodziec pobudza receptor, sygnał trafia do ośrodka nerwowego, a stamtąd do efektora, który wywołuje reakcję',
        'Ośrodek nerwowy jest ostatnim elementem schematu, po którym nic już nie następuje',
        'Receptor i efektor to ten sam element schematu',
      ],
      poprawna: 1,
      wyjasnienie:
        'Diagram pokazuje kierunek przepływu impulsu nerwowego: bodziec pobudza receptor, który przesyła sygnał do ośrodka nerwowego, a stamtąd impuls trafia do efektora wywołującego reakcję organizmu.',
      umiejetnosci: ['diagram', 'analiza'],
    },
  ]);
})();
