(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t101-k1',
      dzialId: 'd1',
      tematId: 't101',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Która kolejność poziomów organizacji życia jest prawidłowa?',
      opcje: ['Tkanka → komórka → narząd → układ → organizm', 'Komórka → tkanka → narząd → układ narządów → organizm', 'Narząd → tkanka → komórka → organizm → układ', 'Komórka → narząd → tkanka → organizm → układ'],
      poprawna: 1,
      wyjasnienie: 'Poziomy organizacji życia układają się od najprostszego do najbardziej złożonego: komórka → tkanka → narząd → układ narządów → organizm.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t101-k2',
      dzialId: 'd1',
      tematId: 't101',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Każdy organizm żywy zbudowany jest z tkanek.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — organizmy jednokomórkowe, np. bakterie, składają się z pojedynczej komórki i nie mają tkanek. Tkanki występują tylko u organizmów wielokomórkowych o zróżnicowanych komórkach.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t101-03',
      dzialId: 'd1',
      tematId: 't101',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Żołądek zbudowany jest z kilku różnych tkanek (nabłonkowej, mięśniowej, łącznej) współpracujących ze sobą. Na jakim poziomie organizacji znajduje się żołądek?',
      opcje: ['Komórka', 'Tkanka', 'Narząd', 'Układ narządów'],
      poprawna: 2,
      wyjasnienie: 'Struktura zbudowana z różnych tkanek pełniąca określoną funkcję (np. trawienie pokarmu) to narząd.',
      umiejetnosci: ['analiza'],
    },
    {
      id: 'p-t101-04',
      dzialId: 'd1',
      tematId: 't101',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych organizmów NIE mają tkanek? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Bakteria', 'Człowiek', 'Ameba (organizm jednokomórkowy)', 'Dąb (drzewo)'],
      poprawna: [0, 2],
      wyjasnienie: 'Bakteria i ameba to organizmy jednokomórkowe — nie mają tkanek, ponieważ tkanka to zespół wielu komórek. Człowiek i dąb to organizmy wielokomórkowe, zbudowane z tkanek.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t101-05',
      dzialId: 'd1',
      tematId: 't101',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj poziomy organizacji życia od najprostszego do najbardziej złożonego.',
      elementy: ['Komórka', 'Tkanka', 'Narząd', 'Układ narządów', 'Organizm'],
      wyjasnienie: 'Prawidłowa kolejność to: komórka → tkanka → narząd → układ narządów → organizm.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t101-06',
      dzialId: 'd1',
      tematId: 't101',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj poziom organizacji do właściwego przykładu.',
      dopasowanie: {
        lewa: ['Tkanka', 'Narząd', 'Układ narządów', 'Organizm'],
        prawa: ['Człowiek', 'Serce', 'Tkanka mięśniowa', 'Układ krwionośny'],
        pary: [2, 1, 3, 0],
      },
      wyjasnienie: 'Tkanka mięśniowa to tkanka, serce to narząd, układ krwionośny to układ narządów, a człowiek to cały organizm.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t101-07',
      dzialId: 'd1',
      tematId: 't101',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Najmniejszą jednostką budującą organizmy żywe jest {{luka1}}. Zespół komórek o podobnej budowie i wspólnej funkcji tworzy {{luka2}}.',
      odpowiedziLuk: { luka1: ['komórka'], luka2: ['tkanka', 'tkankę'] },
      wyjasnienie: 'Podstawową jednostką życia jest komórka, a zespół komórek o podobnej budowie i funkcji to tkanka.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t101-08',
      dzialId: 'd1',
      tematId: 't101',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Wirus wywołujący grypę nie ma budowy komórkowej i nie może samodzielnie się rozmnażać poza komórką gospodarza. Co to oznacza dla klasyfikacji wirusów w kontekście poziomów organizacji życia?',
      opcje: [
        'Wirusy są organizmami jednokomórkowymi, tak jak bakterie',
        'Wirusy nie mieszczą się w typowej hierarchii poziomów organizacji życia, ponieważ nie mają budowy komórkowej',
        'Wirusy są tkanką, ponieważ zawierają materiał genetyczny',
        'Wirusy są organizmami wielokomórkowymi o uproszczonej budowie',
      ],
      poprawna: 1,
      wyjasnienie: 'Wirusy są bezkomórkowymi formami materii — nie mają komórki, więc klasyczna hierarchia (komórka → tkanka → narząd...) ich nie obejmuje. To jedna z cech, która odróżnia je od organizmów żywych w ścisłym sensie.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
  ]);
})();
