(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t102-01',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Z ilu i jakich atomów zbudowana jest cząsteczka wody?',
      opcje: ['Z jednego atomu tlenu i dwóch atomów wodoru', 'Z dwóch atomów tlenu i jednego atomu wodoru', 'Z jednego atomu tlenu i jednego atomu wodoru', 'Z dwóch atomów tlenu i dwóch atomów wodoru'],
      poprawna: 0,
      wyjasnienie: 'Cząsteczka wody (H2O) zbudowana jest z jednego atomu tlenu połączonego wiązaniami kowalencyjnymi z dwoma atomami wodoru.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t102-02',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Cząsteczka wody jest elektrycznie obojętna wewnątrz — nie ma na niej żadnych ładunków cząstkowych.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz. Choć cząsteczka wody jako całość jest obojętna, atom tlenu ma cząstkowy ładunek ujemny, a atomy wodoru — cząstkowy ładunek dodatni. To właśnie ta polarność decyduje o wielu właściwościach wody.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t102-03',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Które zjawisko jest bezpośrednim skutkiem znacznej utraty wody przez komórki rośliny?',
      opcje: ['Więdnięcie rośliny', 'Przyspieszony wzrost rośliny', 'Intensywniejsza fotosynteza', 'Szybsze kwitnienie'],
      poprawna: 0,
      wyjasnienie: 'Utrata wody z wakuoli obniża ciśnienie turgorowe wywierane na ścianę komórkową, przez co komórki tracą jędrność, a roślina więdnie.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t102-04',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdania właściwymi pojęciami.',
      tekstZLuka:
        'Jędrność komórki roślinnej wywołaną naciskiem wody wypełniającej wakuolę na ścianę komórkową nazywamy {{luka1}}. Cząsteczka wody ma budowę {{luka2}} — jeden jej biegun jest naładowany ujemnie, a drugi dodatnio.',
      odpowiedziLuk: { luka1: ['turgor', 'turgorem'], luka2: ['polarną', 'polarna', 'dwubiegunową', 'dwubiegunowa'] },
      wyjasnienie: 'Nacisk wody na ścianę komórkową to turgor, a nierównomierny rozkład ładunku w cząsteczce wody to polarność (dwubiegunowość).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t102-05',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dlaczego woda ma stosunkowo wysoką temperaturę wrzenia jak na tak małą cząsteczkę?',
      opcje: ['Ponieważ między jej cząsteczkami tworzy się bardzo dużo wiązań wodorowych', 'Ponieważ cząsteczka wody ma bardzo dużą masę', 'Ponieważ woda zawiera rozpuszczone sole mineralne', 'Ponieważ atomy wodoru w wodzie nie mają elektronów walencyjnych'],
      poprawna: 0,
      wyjasnienie: 'Liczne wiązania wodorowe między cząsteczkami wody trzeba dodatkowo rozerwać przy przejściu w stan gazowy, co wymaga dostarczenia dużej ilości energii — stąd wysoka jak na tak małą cząsteczkę temperatura wrzenia.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t102-06',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych pierwiastków są makroelementami? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Wapń', 'Żelazo', 'Potas', 'Jod', 'Sód'],
      poprawna: [0, 2, 4],
      wyjasnienie: 'Wapń, potas i sód to makroelementy — organizm potrzebuje ich w dużych ilościach. Żelazo i jod to mikroelementy, potrzebne w ilościach śladowych.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t102-07',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 3,
      tresc: 'Dopasuj pierwiastek do skutku jego wyraźnego niedoboru w organizmie.',
      dopasowanie: {
        lewa: ['Żelazo', 'Jod', 'Wapń', 'Fluor'],
        prawa: ['Wole tarczycowe', 'Osłabienie kości i zębów', 'Anemia (niedokrwistość)', 'Nasilona próchnica zębów'],
        pary: [2, 0, 1, 3],
      },
      wyjasnienie: 'Niedobór żelaza upośledza produkcję hemoglobiny i prowadzi do anemii. Niedobór jodu zaburza pracę tarczycy i powoduje wole. Niedobór wapnia osłabia kości i zęby. Niedobór fluoru sprzyja próchnicy.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t102-08',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj wymienione struktury od tej o największej do tej o najmniejszej procentowej zawartości wody.',
      elementy: ['Meduza (ciało parasola)', 'Ciało dorosłego człowieka', 'Suche nasiono rośliny w stanie spoczynku'],
      wyjasnienie: 'Ciało meduzy zbudowane jest niemal w całości z wody (najwyższa zawartość), ciało człowieka to około 60-70% wody, a suche nasiono w stanie spoczynku zawiera bardzo mało wody — to jedno z przystosowań do przetrwania niekorzystnych warunków.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t102-09',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Świeży liść sałaty ważył 10 g. Po całkowitym wysuszeniu w suszarce jego masa spadła do około 0,6 g. Co najlepiej tłumaczy tak dużą różnicę masy?',
      opcje: ['Liść stracił zawartą w nim wodę, która stanowiła większość jego masy', 'Liść stracił większość zawartych w nim soli mineralnych', 'Liść stracił całą zawartą w nim celulozę', 'W liściu zaszła intensywna fotosynteza podczas suszenia'],
      poprawna: 0,
      wyjasnienie: 'Tkanki roślinne w dużej mierze zbudowane są z wody. Suszenie usuwa wodę, natomiast substancje organiczne i mineralne (tzw. sucha masa) pozostają — stąd tak duży ubytek masy po wysuszeniu.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t102-10',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Które stwierdzenia o wiązaniach wodorowych między cząsteczkami wody są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Powstają między atomem wodoru jednej cząsteczki a atomem tlenu innej cząsteczki',
        'Są silniejsze niż wiązania kowalencyjne wewnątrz cząsteczki wody',
        'Odpowiadają między innymi za wysokie napięcie powierzchniowe wody',
        'Powstają wyłącznie w lodzie, a w wodzie ciekłej nie występują',
      ],
      poprawna: [0, 2],
      wyjasnienie: 'Wiązania wodorowe łączą atom wodoru jednej cząsteczki z atomem tlenu cząsteczki sąsiedniej i odpowiadają m.in. za napięcie powierzchniowe. Są wyraźnie słabsze od wiązań kowalencyjnych i występują zarówno w wodzie ciekłej, jak i w lodzie (w lodzie tworzą bardziej uporządkowaną sieć).',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t102-11',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'image',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na schemacie dwóch cząsteczek wody numerem 3 oznaczono element wskazany linią przerywaną. Co on przedstawia?',
      diagramId: 'd-t102-czasteczka-wody',
      opcje: ['Wiązanie kowalencyjne O-H wewnątrz cząsteczki', 'Wiązanie wodorowe między cząsteczkami wody', 'Jon wodorowy oderwany od cząsteczki', 'Wolną parę elektronową atomu tlenu'],
      poprawna: 1,
      wyjasnienie: 'Linia przerywana między dodatnio naładowanym atomem wodoru jednej cząsteczki a ujemnie naładowanym atomem tlenu drugiej cząsteczki przedstawia wiązanie wodorowe — słabsze niż wiązanie kowalencyjne, ale liczne i wpływowe na właściwości wody.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t102-12',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż, niedobór którego pierwiastka najbardziej bezpośrednio zaburza transport tlenu we krwi.',
      tabela: {
        tytul: 'Wybrane pierwiastki i skutki ich wyraźnego niedoboru',
        kolumny: ['Pierwiastek', 'Główna rola w organizmie', 'Skutek wyraźnego niedoboru'],
        wiersze: [
          ['Wapń', 'Budowa kości i zębów, krzepnięcie krwi', 'Osłabienie kości, kruchość zębów'],
          ['Żelazo', 'Składnik hemoglobiny transportującej tlen', 'Anemia (niedokrwistość), łatwe męczenie się'],
          ['Jod', 'Budowa hormonów tarczycy', 'Wole tarczycowe, spowolniony metabolizm'],
          ['Potas', 'Przewodzenie impulsów nerwowych, praca mięśni', 'Osłabienie mięśni, zaburzenia rytmu serca'],
        ],
      },
      opcje: ['Wapń', 'Żelazo', 'Jod', 'Potas'],
      poprawna: 1,
      wyjasnienie: 'Żelazo jest składnikiem hemoglobiny — białka krwinek czerwonych odpowiedzialnego za wiązanie i transport tlenu. Jego niedobór ogranicza zdolność krwi do przenoszenia tlenu, co prowadzi do anemii.',
      umiejetnosci: ['tabela', 'analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t102-13',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Podczas upałów organizm człowieka intensywnie się poci. Dlaczego parowanie potu z powierzchni skóry skutecznie obniża temperaturę ciała?',
      opcje: [
        'Ponieważ parowanie wody pochłania dużą ilość energii cieplnej, którą pot pobiera z powierzchni skóry',
        'Ponieważ sól zawarta w pocie chemicznie chłodzi skórę',
        'Ponieważ parowanie potu zwęża naczynia krwionośne w skórze',
        'Ponieważ pot rozpuszcza nadmiar ciepła w organizmie',
      ],
      poprawna: 0,
      wyjasnienie: 'Zamiana wody z cieczy w parę wymaga zerwania licznych wiązań wodorowych, co pochłania dużo energii cieplnej. Energię tę pot pobiera z powierzchni skóry, dzięki czemu skóra i organizm się ochładzają — to bezpośredni skutek wysokiej pojemności cieplnej i ciepła parowania wody.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t102-14',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Roślina rosnąca w glebie zupełnie pozbawionej związków azotu może mimo to prawidłowo budować swoje białka, korzystając wyłącznie z węgla, wodoru i tlenu pobranych z wody i dwutlenku węgla.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz. Aminokwasy, z których zbudowane są białka, zawierają oprócz węgla, wodoru i tlenu również azot. Bez azotu pobieranego z gleby (w postaci związków mineralnych) roślina nie jest w stanie zbudować pełnowartościowych białek, niezależnie od dostępu do wody i CO2.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t102-15',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dwie identyczne rośliny doniczkowe podlewano taką samą ilością wody przy identycznym oświetleniu: roślinę A wodą destylowaną, a roślinę B wodą z rozpuszczonym nawozem mineralnym. Po miesiącu roślina A rosła wyraźnie słabiej. Co ten wynik najlepiej pokazuje?',
      opcje: [
        'Sama woda nie wystarcza do prawidłowego wzrostu — roślina potrzebuje też soli mineralnych pobieranych z podłoża',
        'Woda destylowana jest toksyczna dla korzeni roślin',
        'Rośliny w ogóle nie potrzebują wody do wzrostu',
        'Nawóz mineralny całkowicie zastępuje potrzebę podlewania wodą',
      ],
      poprawna: 0,
      wyjasnienie: 'Skoro obie rośliny miały identyczny dostęp do wody i światła, a różniły się tylko obecnością soli mineralnych, różnica we wzroście dowodzi, że sole mineralne są niezbędnym, niezastępowalnym przez wodę składnikiem odżywczym roślin.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe', 'doswiadczenie'],
    },
    {
      id: 'p-t102-16',
      dzialId: 'd1',
      tematId: 't102',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Uzupełnij zdanie dotyczące zależności między budową a funkcją wody.',
      tekstZLuka:
        'Dzięki licznym {{luka1}} między cząsteczkami woda ma wysoką pojemność cieplną, dzięki czemu skutecznie {{luka2}} temperaturę wnętrza organizmu i jego bezpośredniego środowiska.',
      odpowiedziLuk: { luka1: ['wiązaniom wodorowym', 'wiązania wodorowe'], luka2: ['stabilizuje', 'reguluje', 'wyrównuje'] },
      wyjasnienie: 'To klasyczny przykład zależności budowa-funkcja: liczne, choć pojedynczo słabe wiązania wodorowe sumarycznie wymagają dużo energii do zerwania, co przekłada się na zdolność wody do stabilizowania temperatury.',
      umiejetnosci: ['budowa-funkcja', 'przyczynowo-skutkowe'],
    },
  ]);
})();
