(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t203-01',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Bakteria jest organizmem o budowie:',
      opcje: ['Prokariotycznej', 'Eukariotycznej', 'Wielokomórkowej tkankowej', 'Bezkomórkowej'],
      poprawna: 0,
      wyjasnienie: 'Bakteria to organizm prokariotyczny — jej komórka nie ma jądra komórkowego otoczonego błoną, w odróżnieniu od komórek eukariotycznych.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t203-02',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Komórka bakteryjna ma jądro komórkowe otoczone błoną jądrową.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — bakteria jest organizmem prokariotycznym, jej DNA znajduje się luźno w cytoplazmie, w miejscu zwanym nukleoidem, bez otoczki błonowej.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t203-03',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jak nazywa się miejsce w cytoplazmie komórki bakteryjnej, w którym znajduje się jej DNA?',
      opcje: ['Nukleoid', 'Jądro komórkowe', 'Kapsyd', 'Wakuola'],
      poprawna: 0,
      wyjasnienie: 'DNA bakterii znajduje się w cytoplazmie, w obszarze zwanym nukleoidem, który nie jest otoczony błoną jądrową.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t203-04',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka:
        'Komórkę bakteryjną otacza {{luka1}}, która nadaje jej kształt, a pod nią leży {{luka2}}, kontrolująca wymianę substancji z otoczeniem.',
      odpowiedziLuk: { luka1: ['ściana komórkowa'], luka2: ['błona komórkowa'] },
      wyjasnienie: 'Ścianę komórkową bakterii — sztywną warstwę nadającą kształt — otacza od zewnątrz, a bezpośrednio pod nią leży błona komórkowa kontrolująca wymianę substancji.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t203-05',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które struktury występują w każdej komórce bakteryjnej? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Ściana komórkowa', 'Cytoplazma', 'Rybosomy', 'Wić', 'Otoczka śluzowa'],
      poprawna: [0, 1, 2],
      wyjasnienie: 'Ściana komórkowa, cytoplazma i rybosomy występują u każdej bakterii. Wić i otoczka śluzowa to struktury dodatkowe, obecne tylko u niektórych gatunków bakterii.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t203-06',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj element budowy komórki bakteryjnej do jego funkcji.',
      dopasowanie: {
        lewa: ['Ściana komórkowa', 'Błona komórkowa', 'Rybosomy', 'Wić'],
        prawa: ['Umożliwia aktywne poruszanie się komórki', 'Nadaje komórce kształt i chroni ją', 'Kontroluje wymianę substancji z otoczeniem', 'Odpowiadają za produkcję białek'],
        pary: [1, 2, 3, 0],
      },
      wyjasnienie: 'Ściana komórkowa nadaje kształt i chroni komórkę, błona komórkowa kontroluje wymianę substancji, rybosomy odpowiadają za produkcję białek, a wić umożliwia aktywne poruszanie się bakterii.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t203-07',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Bakterie o kulistym kształcie komórki nazywamy:',
      opcje: ['Ziarniakami', 'Pałeczkami', 'Krętkami', 'Nitkowcami'],
      poprawna: 0,
      wyjasnienie: 'Ziarniaki to bakterie o kształcie kulistym. Pałeczki są podłużne, a krętki mają kształt spiralnie skręcony.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t203-08',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'diagram',
      poziom: 'sredni',
      punkty: 2,
      diagramId: 'd-t203-budowa-bakterii',
      tresc: 'Na schemacie budowy komórki bakteryjnej numer 5 wskazuje obszar cytoplazmy zawierający DNA bakterii, bez otoczki błonowej. Jak nazywa się ta struktura?',
      opcje: ['Nukleoid', 'Jądro komórkowe', 'Rybosom', 'Wakuola'],
      poprawna: 0,
      wyjasnienie: 'Numer 5 oznacza nukleoid — obszar w cytoplazmie, gdzie znajduje się DNA bakterii, nieotoczony błoną jądrową, co odróżnia go od prawdziwego jądra komórkowego.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t203-09',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'image',
      poziom: 'trudny',
      punkty: 2,
      diagramId: 'd-t203-budowa-bakterii',
      tresc: 'Na schemacie struktury oznaczone numerami 1 i 7 (otoczka śluzowa i wić) narysowano jako elementy dodatkowe, w odróżnieniu od struktur 2, 3, 4, 5 i 6. Co to oznacza biologicznie?',
      opcje: [
        'Otoczka śluzowa i wić występują tylko u niektórych bakterii, a pozostałe struktury (ściana, błona, cytoplazma, nukleoid, rybosomy) ma każda komórka bakteryjna',
        'Otoczka śluzowa i wić są jedynymi strukturami wspólnymi dla wszystkich bakterii',
        'Bakterie bez wici i otoczki śluzowej nie są w stanie żyć',
        'Struktury 1 i 7 znajdują się wewnątrz nukleoidu',
      ],
      poprawna: 0,
      wyjasnienie: 'Otoczka śluzowa i wić to struktury dodatkowe, występujące tylko u niektórych gatunków bakterii (np. ułatwiają ruch lub dodatkową ochronę). Ściana komórkowa, błona komórkowa, cytoplazma, nukleoid i rybosomy to elementy obecne w każdej komórce bakteryjnej, niezależnie od gatunku.',
      umiejetnosci: ['diagram', 'analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t203-10',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Bakterie żyjące w symbiozie z korzeniami koniczyny i grochu, wiążące azot z powietrza, nazywamy:',
      opcje: ['Bakteriami brodawkowymi', 'Bakteriami saprotroficznymi', 'Bakteriami pasożytniczymi', 'Bakteriami chemosyntetyzującymi'],
      poprawna: 0,
      wyjasnienie: 'Bakterie brodawkowe żyją w symbiozie z korzeniami roślin motylkowych (np. koniczyny, grochu), wiążąc azot atmosferyczny i użyźniając glebę w związki azotowe.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t203-11',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj poniższe struktury komórki bakteryjnej od najbardziej zewnętrznej do najbardziej wewnętrznej (w kierunku środka komórki).',
      elementy: ['Otoczka śluzowa', 'Ściana komórkowa', 'Błona komórkowa', 'Cytoplazma z nukleoidem'],
      wyjasnienie: 'Patrząc od zewnątrz komórki do jej wnętrza: otoczka śluzowa (u niektórych bakterii) → ściana komórkowa → błona komórkowa → cytoplazma, w której znajduje się nukleoid z DNA.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t203-12',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych stwierdzeń o znaczeniu bakterii są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Bakterie saprotroficzne rozkładają martwą materię organiczną, umożliwiając krążenie materii w przyrodzie',
        'Bakterie brodawkowe wzbogacają glebę w związki azotowe',
        'Wszystkie bakterie są chorobotwórcze dla człowieka',
        'Człowiek wykorzystuje niektóre bakterie do produkcji jogurtów i serów',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Bakterie saprotroficzne rozkładają martwą materię organiczną, bakterie brodawkowe wzbogacają glebę w azot, a niektóre bakterie wykorzystuje się do produkcji jogurtów i serów. Nieprawdą jest, że wszystkie bakterie są chorobotwórcze — większość bakterii jest pożyteczna lub obojętna dla człowieka.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t203-13',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego antybiotyki są skuteczne w leczeniu chorób bakteryjnych, ale nie działają na wirusy?',
      opcje: [
        'Ponieważ antybiotyki niszczą struktury typowe dla komórki bakteryjnej (np. ścianę komórkową), a wirus, nie będąc komórką, takich struktur nie posiada',
        'Ponieważ bakterie są znacznie mniejsze od wirusów',
        'Ponieważ wirusy są odporne na wszystkie leki bez wyjątku',
        'Ponieważ antybiotyki działają wyłącznie na organizmy wielokomórkowe',
      ],
      poprawna: 0,
      wyjasnienie: 'Antybiotyki działają na struktury charakterystyczne dla komórki bakteryjnej, np. ścianę komórkową. Wirus nie jest komórką i takich struktur nie ma, dlatego antybiotyki są wobec niego całkowicie nieskuteczne.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t203-14',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'matching',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Dopasuj sposób odżywiania się bakterii do jego opisu.',
      dopasowanie: {
        lewa: ['Bakterie samożywne', 'Bakterie saprotroficzne', 'Bakterie pasożytnicze'],
        prawa: ['Żerują na żywym organizmie, wywołując choroby', 'Same wytwarzają związki organiczne, np. w fotosyntezie', 'Rozkładają martwą materię organiczną'],
        pary: [1, 2, 0],
      },
      wyjasnienie: 'Bakterie samożywne same wytwarzają związki organiczne (np. w procesie fotosyntezy lub chemosyntezy). Bakterie saprotroficzne rozkładają martwą materię organiczną, a bakterie pasożytnicze żerują na żywym organizmie, wywołując choroby.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t203-15',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Rybosomy komórki bakteryjnej są zbudowane inaczej niż rybosomy komórek eukariotycznych, co jest wykorzystywane przez niektóre antybiotyki działające wybiórczo tylko na bakterie.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — różnice w budowie rybosomów bakteryjnych i eukariotycznych pozwalają niektórym antybiotykom (np. blokującym syntezę białek) działać selektywnie na bakterie, nie uszkadzając komórek człowieka.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t203-16',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'W glebie żyzniejszej po uprawie roślin motylkowych (np. koniczyny) rośliny zbożowe uprawiane w kolejnym sezonie rosną zwykle lepiej niż po uprawie zbóż. Co najlepiej to wyjaśnia?',
      opcje: [
        'Bakterie brodawkowe żyjące w symbiozie z korzeniami roślin motylkowych wiążą azot atmosferyczny i wzbogacają glebę w związki azotowe potrzebne kolejnym uprawom',
        'Rośliny motylkowe niszczą wszystkie bakterie chorobotwórcze w glebie',
        'Korzenie roślin motylkowych rozpulchniają glebę mechanicznie, co jest jedynym powodem lepszego wzrostu',
        'Bakterie brodawkowe pobierają azot z gleby i przekazują go do atmosfery',
      ],
      poprawna: 0,
      wyjasnienie: 'Bakterie brodawkowe żyjące w symbiozie z korzeniami roślin motylkowych wiążą azot z powietrza i wzbogacają glebę w związki azotowe, z których korzystają rośliny uprawiane w kolejnym sezonie — to podstawa stosowanego w rolnictwie płodozmianu.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t203-17',
      dzialId: 'd2',
      tematId: 't203',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Uzupełnij zdania dotyczące bakterii.',
      tekstZLuka:
        'Bakterie odżywiające się martwą materią organiczną i rozkładające ją na prostsze związki nazywamy bakteriami {{luka1}}. Bakterie zdolne do samodzielnego wytwarzania związków organicznych, np. w procesie fotosyntezy, nazywamy bakteriami {{luka2}}.',
      odpowiedziLuk: { luka1: ['saprotroficznymi', 'saprotrofami'], luka2: ['samożywnymi', 'autotroficznymi'] },
      wyjasnienie: 'Bakterie rozkładające martwą materię organiczną to bakterie saprotroficzne, a bakterie samodzielnie wytwarzające związki organiczne to bakterie samożywne (autotroficzne).',
      umiejetnosci: ['wiedza', 'analiza'],
    },
  ]);
})();
