(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-plazince-01',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jaki kształt ciała jest charakterystyczny dla płazińców?',
      opcje: ['Kuliste', 'Spłaszczone grzbietowo-brzusznie', 'Walcowate, nitkowate', 'Segmentowane, pierścieniowate'],
      poprawna: 1,
      wyjasnienie: 'Płazińce mają ciało silnie spłaszczone grzbietowo-brzusznie, co odróżnia je od np. walcowatych nicieni czy segmentowanych pierścienic.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-plazince-02',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Tasiemiec ma w pełni wykształcony przewód pokarmowy.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — tasiemiec nie ma przewodu pokarmowego. Pokarm strawiony przez żywiciela wchłania całą powierzchnią ciała.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-plazince-03',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'W jaki sposób tasiemiec pobiera substancje odżywcze?',
      opcje: [
        'Za pomocą wysuwanej gardzieli',
        'Całą powierzchnią ciała, z jelita żywiciela',
        'Za pomocą układu krwionośnego żywiciela',
        'Filtrując wodę przez skrzela',
      ],
      poprawna: 1,
      wyjasnienie: 'Tasiemiec żyje w jelicie cienkim żywiciela otoczony strawionym pokarmem i wchłania go całą powierzchnią ciała pokrytą odporną na trawienie okrywą.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-plazince-04',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które struktury umożliwiają tasiemcowi przyczepienie się do ściany jelita żywiciela? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Przyssawki', 'Haczyki (u niektórych gatunków)', 'Skrzela', 'Szczecinki'],
      poprawna: [0, 1],
      wyjasnienie: 'Tasiemiec przytwierdza się do jelita żywiciela za pomocą przyssawek na skoleksie, a niektóre gatunki (np. tasiemiec uzbrojony) mają dodatkowo haczyki.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-plazince-05',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj organizm do jego trybu życia.',
      dopasowanie: {
        lewa: ['Wypławek', 'Tasiemiec', 'Przywra wątrobowa'],
        prawa: ['Pasożyt jelita cienkiego, bez przewodu pokarmowego', 'Wolno żyjący drapieżnik wodny, ma gardziel i jelito', 'Pasożyt przewodów żółciowych wątroby'],
        pary: [1, 0, 2],
      },
      wyjasnienie: 'Wypławek to forma wolno żyjąca, tasiemiec pasożytuje w jelicie i nie ma przewodu pokarmowego, a przywra wątrobowa pasożytuje w drogach żółciowych wątroby.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-plazince-06',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Przedni odcinek ciała tasiemca, zaopatrzony w przyssawki, nazywamy {{luka1}}. Ciało tasiemca zbudowane jest z licznych, powtarzalnych człon(k)ów zwanych {{luka2}}.',
      odpowiedziLuk: { luka1: ['skoleksem', 'skoleks', 'główką'], luka2: ['proglotydami', 'proglotydy', 'człony'] },
      wyjasnienie: 'Skoleks to głowa tasiemca z narządami przyczepnymi, a proglotydy to powtarzalne, samodzielne pod względem rozrodczym segmenty jego ciała.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-plazince-07',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj etapy cyklu rozwojowego tasiemca uzbrojonego, zaczynając od wydalenia jaj z kałem człowieka.',
      elementy: [
        'Dojrzałe proglotydy z jajami wydalane są z kałem człowieka',
        'Świnia (żywiciel pośredni) połyka jaja wraz z pokarmem',
        'W mięśniach świni rozwija się larwalne stadium — wągier',
        'Człowiek spożywa surowe lub niedogotowane mięso wieprzowe z wągrami',
        'W jelicie cienkim człowieka z wągra rozwija się dorosły tasiemiec',
      ],
      wyjasnienie: 'Cykl zamyka się: jaja z kałem trafiają do środowiska, są połykane przez świnię, w jej mięśniach powstają wągry, człowiek zaraża się jedząc surowe mięso, a w jego jelicie rozwija się dorosły tasiemiec.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-plazince-08',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'diagram',
      poziom: 'sredni',
      punkty: 2,
      diagramId: 'd-t206-plazince-tasiemiec',
      tresc: 'Na diagramie budowy tasiemca element oznaczony numerem 4 to dojrzały proglotyd. Jaka jest jego funkcja?',
      opcje: [
        'Przyczepianie się do ściany jelita żywiciela',
        'Przechowywanie i uwalnianie tysięcy jaj, które są wydalane z kałem',
        'Pobieranie tlenu z krwi żywiciela',
        'Trawienie pokarmu żywiciela',
      ],
      poprawna: 1,
      wyjasnienie: 'Dojrzały proglotyd jest wypełniony tysiącami jaj; odrywa się od ciała tasiemca i zostaje wydalony z kałem żywiciela, co umożliwia rozprzestrzenianie pasożyta.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-plazince-09',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'image',
      poziom: 'latwy',
      punkty: 1,
      diagramId: 'd-t206-plazince-wyplawek',
      tresc: 'Na diagramie budowy wypławka element oznaczony numerem 2 (środek ciała) to gardziel. Do czego służy?',
      opcje: ['Do wykrywania światła', 'Do pobierania pokarmu', 'Do wymiany gazowej', 'Do rozmnażania'],
      poprawna: 1,
      wyjasnienie: 'Gardziel wypławka to wysuwany narząd służący do pobierania pokarmu, który następnie trafia do rozgałęzionego jelita.',
      umiejetnosci: ['diagram', 'wiedza'],
    },
    {
      id: 'p-t206-plazince-10',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego tasiemiec, w przeciwieństwie do wypławka, nie potrzebuje własnego przewodu pokarmowego?',
      opcje: [
        'Bo żyje w wodzie, gdzie pokarm jest łatwo dostępny',
        'Bo żyje w jelicie żywiciela, otoczony już strawionym pokarmem, który może wchłaniać całą powierzchnią ciała',
        'Bo odżywia się wyłącznie tlenem rozpuszczonym w płynach ustrojowych żywiciela',
        'Bo jest organizmem samożywnym i sam wytwarza pokarm',
      ],
      poprawna: 1,
      wyjasnienie: 'Środowisko życia tasiemca — jelito cienkie żywiciela — dostarcza mu gotowego, strawionego pokarmu, dlatego ewolucyjnie zredukował własny układ pokarmowy na rzecz wchłaniania całą powierzchnią ciała.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-plazince-11',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego spłaszczony kształt ciała jest ważny dla płazińców, które nie mają układu krwionośnego?',
      opcje: [
        'Ułatwia im pływanie w toni wodnej',
        'Zwiększa powierzchnię ciała względem jego objętości, co ułatwia dyfuzję gazów i substancji do wszystkich komórek',
        'Chroni je przed drapieżnikami dzięki maskowaniu',
        'Umożliwia im szybsze poruszanie się po dnie',
      ],
      poprawna: 1,
      wyjasnienie: 'Bez układu krwionośnego transport tlenu i substancji odbywa się na drodze dyfuzji. Spłaszczenie ciała skraca drogę dyfuzji do wnętrza i zwiększa powierzchnię wymiany względem objętości.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-plazince-12',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Wypławki żyją najczęściej w czystych wodach słodkich.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'Wypławki są wrażliwe na zanieczyszczenia i najczęściej spotyka się je w czystych zbiornikach i ciekach wód słodkich.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-plazince-13',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Czym różni się wągier od dojrzałego tasiemca?',
      opcje: [
        'Wągier to postać dorosła żyjąca w jelicie człowieka, a dojrzały tasiemiec to jego jajo',
        'Wągier to pęcherzykowate stadium larwalne w mięśniach żywiciela pośredniego, a dojrzały tasiemiec to postać dorosła żyjąca w jelicie żywiciela ostatecznego',
        'Wągier i dojrzały tasiemiec to dwie różne, niespokrewnione grupy pasożytów',
        'Wągier żyje w wodzie, a dojrzały tasiemiec na lądzie',
      ],
      poprawna: 1,
      wyjasnienie: 'Wągier (cysticerkus) to stadium larwalne rozwijające się w mięśniach żywiciela pośredniego (np. świni), natomiast dojrzały tasiemiec to postać dorosła, zdolna do rozmnażania, bytująca w jelicie żywiciela ostatecznego.',
      umiejetnosci: ['analiza', 'wiedza'],
    },
    {
      id: 'p-t206-plazince-14',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych są przykładami płazińców pasożytujących w organizmie człowieka? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Tasiemiec uzbrojony', 'Wypławek biały', 'Tasiemiec nieuzbrojony', 'Przywra wątrobowa'],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Tasiemiec uzbrojony, tasiemiec nieuzbrojony i przywra wątrobowa to pasożyty człowieka. Wypławek biały jest formą wolno żyjącą i nie pasożytuje w człowieku.',
      umiejetnosci: ['analiza', 'wiedza'],
    },
    {
      id: 'p-t206-plazince-15',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Dlaczego spożywanie surowego lub niedogotowanego mięsa wieprzowego niesie ryzyko zarażenia się tasiemcem uzbrojonym?',
      opcje: [
        'Bo świnie same wytwarzają jaja tasiemca we krwi',
        'Bo mięso takie może zawierać wągry, czyli larwalne stadium tasiemca, które w jelicie człowieka rozwija się w postać dorosłą',
        'Bo surowe mięso zawiera toksyny wytwarzane przez tasiemca',
        'Bo wysoka temperatura gotowania nie ma wpływu na przeżywalność pasożytów',
      ],
      poprawna: 1,
      wyjasnienie: 'Świnia jest żywicielem pośrednim tasiemca uzbrojonego — w jej mięśniach rozwijają się wągry. Odpowiednia obróbka termiczna mięsa niszczy wągry, dlatego surowe lub niedogotowane mięso jest źródłem zarażenia.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-plazince-16',
      dzialId: 'd2',
      tematId: 't206-plazince',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Które zwierzę NIE należy do płazińców?',
      opcje: ['Tasiemiec uzbrojony', 'Wypławek biały', 'Przywra wątrobowa', 'Glista ludzka'],
      poprawna: 3,
      wyjasnienie: 'Glista ludzka to przedstawiciel nicieni, a nie płazińców — ma niesegmentowane, nitkowate (walcowate) ciało, a nie spłaszczone.',
      umiejetnosci: ['wiedza'],
    },
  ]);
})();
