(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-stawonogi-01',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Która cecha jest wspólna dla wszystkich stawonogów?',
      opcje: ['Muszla okrywająca ciało', 'Chitynowy szkielet zewnętrzny i odnóża członowane', 'Ciało spłaszczone grzbietowo-brzusznie', 'Zamknięty układ krwionośny'],
      poprawna: 1,
      wyjasnienie: 'Wszystkie stawonogi mają twardy, chitynowy szkielet zewnętrzny (egzoszkielet) oraz odnóża zbudowane z ruchomo połączonych członów — stąd nazwa typu.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-stawonogi-02',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Owady mają trzy pary odnóży.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — owady mają trzy pary odnóży osadzonych na tułowiu (sześć nóg łącznie).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-stawonogi-03',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Pająki są owadami.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — pająki należą do pajęczaków. Mają cztery pary odnóży (osiem nóg) i nie mają czułków, w przeciwieństwie do owadów.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-stawonogi-04',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka:
        'Ciało stawonogów okrywa twardy, chitynowy {{luka1}}. Ponieważ nie rośnie on razem z ciałem, stawonogi muszą go okresowo zrzucać w procesie zwanym {{luka2}}.',
      odpowiedziLuk: { luka1: ['szkielet zewnętrzny', 'egzoszkielet', 'pancerz'], luka2: ['linieniem', 'linienie'] },
      wyjasnienie: 'Sztywny egzoszkielet ogranicza wzrost ciała, dlatego stawonóg musi go okresowo zrzucić (linienie), aby móc urosnąć, zanim nowy pancerz stwardnieje.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-stawonogi-05',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Dlaczego stawonogi muszą okresowo zrzucać egzoszkielet (linieć)?',
      opcje: [
        'Bo sztywny egzoszkielet nie rośnie wraz z ciałem i ogranicza jego powiększanie się',
        'Bo egzoszkielet co jakiś czas traci kolor i trzeba go odnowić',
        'Bo linienie jest sposobem oddychania stawonogów',
        'Bo stary egzoszkielet staje się źródłem pokarmu dla innych osobników',
      ],
      poprawna: 0,
      wyjasnienie: 'Chitynowy egzoszkielet jest sztywny i nie powiększa się razem z rosnącym ciałem, dlatego musi być okresowo zrzucany, aby zwierzę mogło urosnąć.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-stawonogi-06',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 3,
      tresc: 'Dopasuj grupę stawonogów do liczby odnóży i cech charakterystycznych budowy ciała.',
      dopasowanie: {
        lewa: ['Owady', 'Pajęczaki', 'Skorupiaki', 'Wije'],
        prawa: [
          '4 pary odnóży, ciało: głowotułów i odwłok, brak czułków',
          '3 pary odnóży, ciało: głowa, tułów i odwłok, 1 para czułków, często skrzydła',
          'Liczne pary odnóży (po 1–2 na segment), ciało wydłużone, żyją głównie w glebie i ściółce',
          'Liczne odnóża pełniące różne funkcje, 2 pary czułków, oddychanie skrzelami, głównie środowisko wodne',
        ],
        pary: [1, 0, 3, 2],
      },
      wyjasnienie: 'Owady mają 3 pary odnóży i 1 parę czułków, pajęczaki 4 pary odnóży i brak czułków, skorupiaki liczne odnóża i 2 pary czułków oraz oddychają skrzelami, a wije mają wydłużone ciało z licznymi parami odnóży.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-stawonogi-07',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych cech są typowe dla owadów? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Trzy pary odnóży', 'Jedna para czułków', 'Cztery pary odnóży', 'Ciało podzielone na głowę, tułów i odwłok'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Owady mają trzy pary odnóży, jedną parę czułków i ciało podzielone na głowę, tułów i odwłok. Cztery pary odnóży mają pajęczaki, a nie owady.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-stawonogi-08',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'diagram',
      poziom: 'sredni',
      punkty: 2,
      diagramId: 'd-t206-stawonogi-owad',
      tresc: 'Na diagramie budowy owada element oznaczony numerem 2 to czułki. Jaką funkcję pełnią?',
      opcje: ['Narząd dotyku i węchu', 'Narząd wzroku', 'Narząd oddechowy', 'Narząd rozrodczy'],
      poprawna: 0,
      wyjasnienie: 'Czułki to para narządów zmysłów osadzonych na głowie owada, służących głównie do dotyku i wykrywania zapachów.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-stawonogi-09',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'image',
      poziom: 'sredni',
      punkty: 1,
      diagramId: 'd-t206-stawonogi-owad',
      tresc: 'Na diagramie budowy owada element oznaczony numerem 4 to odnóża (3 pary). Do którego odcinka ciała są przyczepione?',
      opcje: ['Do głowy', 'Do tułowia', 'Do odwłoka', 'Do czułków'],
      poprawna: 1,
      wyjasnienie: 'U owadów wszystkie trzy pary odnóży są osadzone na tułowiu — to jedna z cech odróżniających owady od innych grup stawonogów.',
      umiejetnosci: ['diagram', 'wiedza'],
    },
    {
      id: 'p-t206-stawonogi-10',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego otwarty układ krwionośny stawonogów jest mniej wydajny niż zamknięty układ krwionośny pierścienic?',
      opcje: [
        'Bo hemolimfa swobodnie wypełnia jamę ciała, więc jej przepływ do poszczególnych narządów jest trudniejszy do kontrolowania niż krwi płynącej w naczyniach',
        'Bo stawonogi w ogóle nie mają serca',
        'Bo hemolimfa u stawonogów nie zawiera żadnych składników odżywczych',
        'Bo otwarty układ krwionośny działa wyłącznie w spoczynku',
      ],
      poprawna: 0,
      wyjasnienie: 'W otwartym układzie krwionośnym hemolimfa częściowo swobodnie omywa narządy w jamie ciała (hemocelu), zamiast płynąć wyłącznie w naczyniach — utrudnia to precyzyjną kontrolę kierunku i tempa jej przepływu.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-stawonogi-11',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj etapy przeobrażenia zupełnego motyla, zaczynając od jaja.',
      elementy: ['Jajo', 'Larwa (gąsienica)', 'Poczwarka', 'Owad dorosły (postać dojrzała)'],
      wyjasnienie: 'Przeobrażenie zupełne przebiega przez cztery kolejne stadia: jajo, larwę o budowie zupełnie innej niż postać dorosła, poczwarkę, w której zachodzi przebudowa ciała, oraz owada dorosłego.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-stawonogi-12',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Czym różni się przeobrażenie niezupełne od przeobrażenia zupełnego?',
      opcje: [
        'W przeobrażeniu niezupełnym brak jest stadium poczwarki, a larwa (nimfa) przypomina wyglądem postać dorosłą',
        'W przeobrażeniu niezupełnym brak jest stadium jaja',
        'Przeobrażenie niezupełne dotyczy wyłącznie owadów wodnych',
        'Przeobrażenie niezupełne trwa zawsze dłużej niż zupełne',
      ],
      poprawna: 0,
      wyjasnienie: 'W przeobrażeniu niezupełnym (np. u konika polnego) nie występuje stadium poczwarki, a wykluta z jaja larwa (nimfa) z wyglądu przypomina miniaturową postać dorosłą.',
      umiejetnosci: ['analiza', 'wiedza'],
    },
    {
      id: 'p-t206-stawonogi-13',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Większość skorupiaków oddycha za pomocą skrzeli.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — skorupiaki żyją głównie w środowisku wodnym i oddychają za pomocą skrzeli, w przeciwieństwie do lądowych owadów, które mają tchawki.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-stawonogi-14',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Dlaczego kleszcze mają duże znaczenie dla zdrowia człowieka?',
      opcje: [
        'Bo są roślinożerne i niszczą uprawy',
        'Bo mogą być wektorami (przenosicielami) groźnych chorób, np. boreliozy i kleszczowego zapalenia mózgu',
        'Bo zapylają rośliny uprawne',
        'Bo produkują jedwab wykorzystywany w przemyśle',
      ],
      poprawna: 1,
      wyjasnienie: 'Kleszcze żywią się krwią kręgowców i podczas żerowania mogą przenosić na człowieka bakterie wywołujące boreliozę oraz wirusy kleszczowego zapalenia mózgu (KZM).',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-stawonogi-15',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'multiple',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Które z poniższych zwierząt należą do pajęczaków? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Pająk krzyżak', 'Kleszcz', 'Rak rzeczny', 'Skorpion'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Pająk krzyżak, kleszcz i skorpion to pajęczaki (4 pary odnóży, głowotułów i odwłok). Rak rzeczny należy do skorupiaków.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-stawonogi-16',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Jakie znaczenie mają owady zapylające, np. pszczoły, dla przyrody i rolnictwa?',
      opcje: [
        'Umożliwiają zapylanie kwiatów, co warunkuje zawiązywanie się nasion i owoców u wielu roślin',
        'Rozkładają martwą materię organiczną w glebie',
        'Chronią rośliny przed suszą, magazynując wodę',
        'Produkują tlen w procesie fotosyntezy',
      ],
      poprawna: 0,
      wyjasnienie: 'Owady zapylające przenoszą pyłek między kwiatami, co umożliwia zapłodnienie roślin i powstawanie nasion oraz owoców — ma to ogromne znaczenie dla przyrody i produkcji rolnej.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-stawonogi-17',
      dzialId: 'd2',
      tematId: 't206-stawonogi',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Czym różni się budowa ciała wij od budowy ciała owadów?',
      opcje: [
        'Wije mają wydłużone, segmentowane ciało z licznymi parami odnóży na kolejnych segmentach, podczas gdy owady mają tylko trzy pary odnóży osadzone na tułowiu',
        'Wije, w przeciwieństwie do owadów, nie mają czułków',
        'Wije mają skrzydła, a owady nigdy ich nie mają',
        'Wije mają zewnętrzną muszlę, a owady egzoszkielet chitynowy',
      ],
      poprawna: 0,
      wyjasnienie: 'Wije (np. stonoga, krocionóg) mają wydłużone ciało z liczną liczbą segmentów, z których niemal każdy niesie parę (lub dwie) odnóży, podczas gdy owady mają tylko trzy pary odnóży osadzone na tułowiu.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
  ]);
})();
