(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t113-01',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Które słowne równanie poprawnie opisuje fotosyntezę?',
      opcje: [
        'Glukoza + tlen → dwutlenek węgla + woda + energia',
        'Dwutlenek węgla + woda + energia świetlna → glukoza + tlen',
        'Glukoza + woda → dwutlenek węgla + tlen',
        'Tlen + woda → glukoza + dwutlenek węgla',
      ],
      poprawna: 1,
      wyjasnienie: 'W fotosyntezie z dwutlenku węgla i wody, przy udziale energii świetlnej i chlorofilu, powstaje glukoza oraz uwalniany jest tlen.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t113-02',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Tlen jest produktem ubocznym fotosyntezy.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — głównym produktem fotosyntezy jest glukoza, a tlen powstaje jako produkt uboczny, uwalniany do atmosfery.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t113-03',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'W jakim organellum komórkowym zachodzi fotosynteza?',
      opcje: ['W mitochondrium', 'W chloroplaście', 'W jądrze komórkowym', 'W wakuoli'],
      poprawna: 1,
      wyjasnienie: 'Fotosynteza zachodzi w chloroplastach — organellach zawierających zielony barwnik, chlorofil.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t113-04',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie opisujące substraty i produkty fotosyntezy.',
      tekstZLuka: 'Substratami fotosyntezy są dwutlenek węgla i {{luka1}}, a jej produktami są glukoza i {{luka2}}.',
      odpowiedziLuk: { luka1: ['woda'], luka2: ['tlen'] },
      wyjasnienie: 'Fotosynteza przekształca dwutlenek węgla i wodę w glukozę i tlen, przy udziale energii świetlnej i chlorofilu.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t113-05',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Rośliny zielone oddychają komórkowo tylko w nocy, a w dzień wyłącznie fotosyntetyzują.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — rośliny oddychają komórkowo przez całą dobę, także w dzień. W dzień fotosynteza po prostu przeważa ilościowo nad oddychaniem, dlatego efekt netto to pobieranie CO2 i wydzielanie O2.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t113-06',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Dlaczego liście roślin są zazwyczaj zielone?',
      opcje: [
        'Ponieważ chlorofil pochłania głównie światło zielone',
        'Ponieważ chlorofil pochłania głównie światło czerwone i niebieskie, a odbija światło zielone',
        'Ponieważ liście nie zawierają żadnych barwników',
        'Ponieważ zielony kolor powstaje w wyniku oddychania komórkowego',
      ],
      poprawna: 1,
      wyjasnienie: 'Chlorofil najsilniej pochłania światło czerwone i niebieskie, a odbija światło zielone — dlatego rośliny wydają się nam zielone.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t113-07',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które czynniki wpływają na intensywność fotosyntezy? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Natężenie światła', 'Stężenie dwutlenku węgla', 'Temperatura', 'Kolor kwiatów rośliny'],
      poprawna: [0, 1, 2],
      wyjasnienie: 'Intensywność fotosyntezy zależy od natężenia światła, stężenia CO2 i temperatury. Kolor kwiatów nie ma związku z przebiegiem fotosyntezy, która zachodzi głównie w zielonych liściach.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t113-08',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj element budowy liścia do jego roli w fotosyntezie.',
      dopasowanie: {
        lewa: ['Aparat szparkowy', 'Chloroplast', 'Tkanka przewodząca (ksylem)', 'Miękisz asymilacyjny'],
        prawa: ['Dostarczanie wody do komórek liścia', 'Miejsce zachodzenia reakcji fotosyntezy', 'Pobieranie dwutlenku węgla z powietrza', 'Tkanka bogata w chloroplasty'],
        pary: [2, 1, 0, 3],
      },
      wyjasnienie: 'Aparaty szparkowe umożliwiają pobór CO2, chloroplasty są miejscem fotosyntezy, ksylem dostarcza wodę, a miękisz asymilacyjny to tkanka bogata w chloroplasty, w której intensywnie zachodzi fotosynteza.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t113-09',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'chart',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na wykresie przedstawiono zależność intensywności fotosyntezy od natężenia światła padającego na roślinę. Na podstawie wykresu określ, co dzieje się z intensywnością fotosyntezy po przekroczeniu natężenia światła około 60 jednostek.',
      wykres: {
        typ: 'liniowy',
        tytul: 'Intensywność fotosyntezy w zależności od natężenia światła',
        jednostka: 'j. wzgl.',
        dane: [
          { etykieta: '0 lx', wartosc: 0 },
          { etykieta: '20 lx', wartosc: 15 },
          { etykieta: '40 lx', wartosc: 28 },
          { etykieta: '60 lx', wartosc: 30 },
          { etykieta: '80 lx', wartosc: 30 },
          { etykieta: '100 lx', wartosc: 30 },
        ],
      },
      opcje: [
        'Nadal rośnie proporcjonalnie do natężenia światła',
        'Pozostaje na stałym poziomie — ograniczać ją zaczyna inny czynnik, np. stężenie CO2',
        'Gwałtownie spada do zera',
        'Roślina przestaje oddychać komórkowo',
      ],
      poprawna: 1,
      wyjasnienie: 'Po przekroczeniu pewnego natężenia światła intensywność fotosyntezy przestaje rosnąć i utrzymuje się na stałym poziomie — światło przestało być czynnikiem ograniczającym, a jego rolę przejmuje inny czynnik, np. stężenie CO2 lub temperatura.',
      umiejetnosci: ['wykres', 'analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t113-10',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj etapy drogi dwutlenku węgla podczas fotosyntezy, od pobrania z powietrza do powstania glukozy.',
      elementy: ['Dwutlenek węgla wnika do liścia przez aparat szparkowy', 'CO2 dociera do komórek miękiszu asymilacyjnego', 'CO2 trafia do chloroplastu', 'W chloroplaście powstaje glukoza'],
      wyjasnienie: 'Dwutlenek węgla dostaje się do liścia przez aparaty szparkowe, dociera do komórek miękiszu asymilacyjnego, następnie do chloroplastów, gdzie w procesie fotosyntezy zostaje przekształcony w glukozę.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t113-11',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Podczas suszy roślina zamyka aparaty szparkowe, aby ograniczyć utratę wody. Jaki będzie najbardziej prawdopodobny skutek tego zjawiska dla fotosyntezy?',
      opcje: [
        'Fotosynteza przyspieszy, bo roślina zaoszczędzi wodę',
        'Fotosynteza spowolni, bo ograniczony zostanie dopływ dwutlenku węgla do liścia',
        'Fotosynteza nie zmieni się, bo CO2 nie jest jej potrzebny',
        'Roślina zacznie prowadzić chemosyntezę zamiast fotosyntezy',
      ],
      poprawna: 1,
      wyjasnienie: 'Zamknięcie aparatów szparkowych ogranicza dopływ dwutlenku węgla do wnętrza liścia, a CO2 jest niezbędnym substratem fotosyntezy — jej intensywność zatem spadnie.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t113-12',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Fotosynteza może zachodzić w całkowitej ciemności, jeśli tylko temperatura jest wystarczająco wysoka.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — fotosynteza wymaga energii świetlnej jako niezbędnego czynnika; bez światła nie zajdzie niezależnie od temperatury.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t113-13',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'chart',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Na wykresie przedstawiono zależność intensywności fotosyntezy od stężenia dwutlenku węgla w powietrzu, przy stałym, wysokim natężeniu światła. O ile jednostek wzrosła intensywność fotosyntezy przy zwiększeniu stężenia CO2 z 0,03% do 0,10%?',
      wykres: {
        typ: 'liniowy',
        tytul: 'Intensywność fotosyntezy w zależności od stężenia CO2',
        jednostka: 'j. wzgl.',
        dane: [
          { etykieta: '0,01%', wartosc: 5 },
          { etykieta: '0,03%', wartosc: 20 },
          { etykieta: '0,06%', wartosc: 32 },
          { etykieta: '0,10%', wartosc: 38 },
          { etykieta: '0,15%', wartosc: 38 },
        ],
      },
      opcje: ['6 jednostek', '18 jednostek', '38 jednostek', '20 jednostek'],
      poprawna: 1,
      wyjasnienie: 'Przy 0,03% CO2 intensywność wynosiła 20 jednostek, a przy 0,10% CO2 — 38 jednostek. Różnica wynosi 38 − 20 = 18 jednostek. Powyżej 0,10% wykres się wypłaszcza — CO2 przestaje być czynnikiem ograniczającym.',
      umiejetnosci: ['wykres', 'analiza'],
    },
    {
      id: 'p-t113-14',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Dopasuj sytuację doświadczalną do jej najbardziej prawdopodobnego skutku dla fotosyntezy.',
      dopasowanie: {
        lewa: ['Przeniesienie rośliny do ciemnego pomieszczenia', 'Zwiększenie stężenia CO2 przy silnym świetle', 'Podniesienie temperatury znacznie powyżej optimum', 'Ograniczenie dostępu wody do korzeni'],
        prawa: ['Fotosynteza może wzrosnąć, jeśli CO2 był czynnikiem ograniczającym', 'Fotosynteza ustaje z powodu braku światła', 'Fotosynteza spada wskutek zamykania aparatów szparkowych i ograniczenia dopływu CO2', 'Enzymy fotosyntezy ulegają uszkodzeniu, fotosynteza spada'],
        pary: [1, 0, 3, 2],
      },
      wyjasnienie: 'Brak światła zatrzymuje fotosyntezę, wzrost CO2 może ją przyspieszyć, gdy było ono czynnikiem ograniczającym, zbyt wysoka temperatura uszkadza enzymy, a niedobór wody prowadzi do zamykania aparatów szparkowych i spadku dopływu CO2.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t113-15',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie dotyczące czynnika ograniczającego fotosyntezę.',
      tekstZLuka: 'Tempo fotosyntezy jest zawsze ograniczane przez ten czynnik środowiskowy, który w danym momencie jest {{luka1}} dostępny, nawet jeśli pozostałe czynniki, np. {{luka2}}, występują w nadmiarze.',
      odpowiedziLuk: { luka1: ['najmniej', 'w niedoborze'], luka2: ['światło', 'CO2', 'dwutlenek węgla', 'temperatura'] },
      wyjasnienie: 'Zgodnie z prawem czynnika ograniczającego, tempo fotosyntezy wyznacza ten czynnik (np. światło, CO2 lub temperatura), którego jest akurat najmniej — nawet gdy inne czynniki są dostępne w nadmiarze.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t113-16',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Roślinę doniczkową trzymano w pomieszczeniu bez dostępu do naturalnego światła, oświetlaną wyłącznie słabą lampką przez kilka minut dziennie. Po miesiącu roślina wyraźnie osłabła i przestała rosnąć. Co jest najbardziej prawdopodobną przyczyną?',
      opcje: [
        'Zbyt niska intensywność fotosyntezy nie zapewniała rośliny w wystarczającą ilość glukozy',
        'Roślina przestała oddychać komórkowo z powodu braku światła',
        'Chlorofil w liściach uległ denaturacji z powodu braku światła',
        'Roślina zaczęła prowadzić wyłącznie oddychanie beztlenowe',
      ],
      poprawna: 0,
      wyjasnienie: 'Przy bardzo słabym oświetleniu intensywność fotosyntezy jest bardzo niska, więc roślina wytwarza za mało glukozy, by pokryć zapotrzebowanie energetyczne (w tym potrzeby oddychania komórkowego, które zachodzi niezależnie od światła) i budulcowe — dlatego osłabła i przestała rosnąć.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t113-17',
      dzialId: 'd1',
      tematId: 't113',
      typ: 'multiple',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Które stwierdzenia dotyczące fotosyntezy są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Fotosynteza zachodzi tylko w komórkach zawierających chloroplasty',
        'Fotosynteza jest przykładem procesu anabolicznego',
        'Produktem fotosyntezy jest wyłącznie tlen',
        'Fotosynteza dostarcza materii organicznej będącej podstawą łańcuchów pokarmowych',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Fotosynteza zachodzi wyłącznie w komórkach z chloroplastami, jest procesem anabolicznym (budowanie glukozy z prostszych związków) i dostarcza materii organicznej dla łańcuchów pokarmowych. Jej głównym produktem jest glukoza, a tlen — produktem ubocznym, więc stwierdzenie o wyłączności tlenu jest błędne.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
  ]);
})();
