(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t204-nagonasienne-01',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Do roślin nagonasiennych zaliczamy przede wszystkim:',
      opcje: ['drzewa i krzewy iglaste (szpilkowe), np. sosnę, świerk, jodłę', 'trawy i zboża', 'mchy i wątrobowce', 'paprocie i skrzypy'],
      poprawna: 0,
      wyjasnienie: 'Nagonasienne to głównie drzewa i krzewy iglaste, np. sosna, świerk, jodła, modrzew i cis.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-nagonasienne-02',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Nagonasienne rozmnażają się za pomocą zarodników, tak jak paprocie.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — nagonasienne są roślinami nasiennymi i rozmnażają się za pomocą nasion, a nie zarodników.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-nagonasienne-03',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Liście nagonasiennych są zwykle zredukowane do:',
      opcje: ['igieł lub łusek', 'wielkich, pierzastych blaszek', 'pływających liści', 'nagonasienne nie mają w ogóle liści'],
      poprawna: 0,
      wyjasnienie: 'Liście nagonasiennych mają postać wąskich igieł lub drobnych łusek, pokrytych grubą kutykulą.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-nagonasienne-04',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie: Pyłek nagonasiennych jest przenoszony głównie przez {{luka1}}, a nasiona leżą {{luka2}} na powierzchni łuski szyszki.',
      tekstZLuka: 'Pyłek nagonasiennych jest przenoszony głównie przez {{luka1}}, a nasiona leżą {{luka2}} na powierzchni łuski szyszki.',
      odpowiedziLuk: { luka1: ['wiatr'], luka2: ['odsłonięte', 'nieosłonięte', 'nagie'] },
      wyjasnienie: 'Zapylenie nagonasiennych jest anemogamiczne (za pośrednictwem wiatru), a nasiona leżą odsłonięte na łusce szyszki.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-nagonasienne-05',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dlaczego gruba kutykula pokrywająca igły nagonasiennych jest ważnym przystosowaniem?',
      opcje: [
        'Ogranicza parowanie wody, co pomaga przetrwać zimę i suszę fizjologiczną',
        'Umożliwia fotosyntezę w ciemności',
        'Chroni przed nadmiernym nasłonecznieniem wyłącznie latem',
        'Zwiększa masę liścia, by nie został zerwany przez wiatr',
      ],
      poprawna: 0,
      wyjasnienie: 'Gruba kutykula ogranicza utratę wody przez parowanie, co jest kluczowe zimą, gdy zamarznięta gleba utrudnia pobieranie wody przez korzenie (susza fizjologiczna).',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-nagonasienne-06',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Nagonasienne są roślinami jednopiennymi — na tym samym drzewie wytwarzają szyszki męskie i żeńskie.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — np. sosna wytwarza na tym samym drzewie zarówno szyszki męskie, jak i żeńskie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-nagonasienne-07',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj pojęcie do jego opisu.',
      dopasowanie: {
        lewa: ['Szyszka męska', 'Szyszka żeńska', 'Zalążek', 'Igła'],
        prawa: [
          'Wytwarza pyłek roznoszony przez wiatr',
          'Zbudowana z łusek, na których leżą nieosłonięte zalążki (a później nasiona)',
          'Struktura, z której po zapłodnieniu rozwija się nasiono',
          'Zredukowany liść pokryty grubą kutykulą',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Szyszka męska wytwarza pyłek, szyszka żeńska zawiera zalążki na łuskach, z zalążka po zapłodnieniu rozwija się nasiono, a igła to zredukowany liść.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-nagonasienne-08',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które cechy są typowe dla roślin nagonasiennych? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Nasiona leżą odsłonięte na łuskach szyszki', 'Zapylenie odbywa się głównie za pośrednictwem wiatru', 'Wytwarzają kwiaty i owoce', 'Liście są zwykle zredukowane do igieł'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Nagonasienne mają nieosłonięte nasiona, są zapylane głównie przez wiatr, a ich liście to zwykle igły. Nie wytwarzają kwiatów ani owoców — to cecha okrytonasiennych.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t204-nagonasienne-09',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego zapylenie wiatrem (anemogamiczne) u nagonasiennych wymaga wytwarzania bardzo dużych ilości pyłku?',
      opcje: [
        'Ponieważ przypadkowy transport pyłku przez wiatr jest mało precyzyjny i tylko niewielka jego część trafia na szyszki żeńskie',
        'Ponieważ pyłek nagonasiennych szybko traci zdolność do zapłodnienia',
        'Ponieważ każdy zalążek wymaga zapylenia przez wiele różnych roślin jednocześnie',
        'Ponieważ owady zjadają większość wytworzonego pyłku',
      ],
      poprawna: 0,
      wyjasnienie: 'W przeciwieństwie do celowanego przenoszenia pyłku przez owady, wiatr rozprasza pyłek przypadkowo, więc rośliny muszą go wytwarzać bardzo dużo, by zwiększyć szansę trafienia na szyszki żeńskie.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t204-nagonasienne-10',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Uporządkuj etapy powstawania nasiona u sosny (rośliny nagonasiennej).',
      elementy: [
        'Szyszka męska wytwarza ziarna pyłku',
        'Pyłek przenoszony jest przez wiatr na szyszkę żeńską (zapylenie)',
        'Zapłodnienie zalążka leżącego odsłonięte na łusce szyszki żeńskiej',
        'Rozwój nasiona nieosłoniętego na powierzchni łuski',
        'Dojrzała szyszka rozchyla łuski i uwalnia nasiona roznoszone przez wiatr',
      ],
      wyjasnienie: 'Kolejność: pyłek w szyszce męskiej → zapylenie (wiatr) → zapłodnienie zalążka → rozwój nieosłoniętego nasiona → uwolnienie nasion z dojrzałej szyszki.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t204-nagonasienne-11',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Cechą wspólną roślin nagonasiennych i okrytonasiennych, odróżniającą je od mchów i paproci, jest:',
      opcje: [
        'rozmnażanie się za pomocą nasion, niezależne od wody w środowisku zewnętrznym',
        'brak jakichkolwiek tkanek przewodzących',
        'wytwarzanie zarodników w sorusach',
        'życie wyłącznie w środowisku wodnym',
      ],
      poprawna: 0,
      wyjasnienie: 'Zarówno nagonasienne, jak i okrytonasienne to rośliny nasienne — rozmnażają się za pomocą nasion, a proces zapylenia nie wymaga wody, w przeciwieństwie do mchów i paproci.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-nagonasienne-12',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych stwierdzeń o nagonasiennych są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Nasiona nie są ukryte wewnątrz owocu',
        'Zdecydowana większość gatunków to drzewa lub krzewy iglaste',
        'Do zapłodnienia niezbędna jest obecność wody w otoczeniu, tak jak u mchów',
        'Modrzew, w przeciwieństwie do większości nagonasiennych, zrzuca igły na zimę',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Nasiona nagonasiennych są nieosłonięte, większość gatunków to drzewa i krzewy iglaste, a modrzew zrzuca igły na zimę. Zapłodnienie u nagonasiennych nie wymaga wody — pyłek dociera do zalążka przez łagiewkę pyłkową.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-nagonasienne-13',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Lasy iglaste (nagonasienne) potrafią rosnąć na ubogich, piaszczystych glebach i w chłodnym klimacie, w warunkach trudnych dla wielu innych roślin. Które przystosowanie ma z tym największy związek?',
      opcje: [
        'Gruba kutykula na igłach ograniczająca utratę wody oraz rozmnażanie za pomocą nasion i pyłku przenoszonego przez wiatr, niezależne od wody w otoczeniu',
        'Brak jakichkolwiek tkanek przewodzących, co zmniejsza zapotrzebowanie na wodę',
        'Wytwarzanie kwiatów o silnym zapachu przyciągającym owady zapylające',
        'Rozmnażanie wyłącznie za pomocą zarodników rozsiewanych przez wiatr',
      ],
      poprawna: 0,
      wyjasnienie: 'Ograniczenie parowania wody dzięki grubej kutykuli oraz niezależność rozmnażania płciowego od wody w otoczeniu pozwalają nagonasiennym przetrwać w trudnych, ubogich w wodę warunkach.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t204-nagonasienne-14',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Szyszka żeńska sosny jest strukturą powstającą — podobnie jak owoc rośliny okrytonasiennej — z zalążni kwiatu.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — nagonasienne nie wytwarzają kwiatów ani zalążni. Szyszka żeńska to zdrewniały organ zbudowany z łusek, na których leżą odsłonięte nasiona, zupełnie inaczej niż owoc powstający z zalążni.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-nagonasienne-15',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie: Ponieważ nasiona nagonasiennych leżą {{luka1}} na powierzchni łuski szyszki, a nie wewnątrz owocu, rośliny te nazywane są {{luka2}}.',
      tekstZLuka: 'Ponieważ nasiona nagonasiennych leżą {{luka1}} na powierzchni łuski szyszki, a nie wewnątrz owocu, rośliny te nazywane są {{luka2}}.',
      odpowiedziLuk: { luka1: ['odsłonięte', 'nieosłonięte', 'nagie'], luka2: ['nagonasiennymi', 'rośliny nagonasienne'] },
      wyjasnienie: 'Nieosłonięte („nagie”) nasiono leżące na łusce szyszki to cecha decydująca o nazwie grupy.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-nagonasienne-16',
      dzialId: 'd2',
      tematId: 't204-nagonasienne',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dopasuj pojęcie do jego opisu.',
      dopasowanie: {
        lewa: ['Igła', 'Szyszka żeńska', 'Nasiono nieosłonięte', 'Zapylenie anemogamiczne'],
        prawa: [
          'Zredukowany liść z grubą kutykulą, ograniczający parowanie wody',
          'Organ zbudowany z łusek, na których rozwijają się nasiona',
          'Nasiono leżące odsłonięte na powierzchni łuski, bez osłony w postaci owocu',
          'Przenoszenie pyłku za pośrednictwem wiatru',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Igła to zredukowany liść, szyszka żeńska to organ z łuskami, nasiono nieosłonięte leży na łusce, a zapylenie anemogamiczne to przenoszenie pyłku przez wiatr.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
  ]);
})();
