(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t105-01',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Z jakich dwóch składników zbudowany jest tłuszcz właściwy (triacyloglicerol)?',
      opcje: ['Z glicerolu i trzech kwasów tłuszczowych', 'Z dwóch cząsteczek glukozy i wody', 'Z aminokwasów połączonych wiązaniem peptydowym', 'Z cukru pięciowęglowego i zasady azotowej'],
      poprawna: 0,
      wyjasnienie: 'Tłuszcz właściwy zbudowany jest z jednej cząsteczki glicerolu (trójwęglowego alkoholu) połączonej wiązaniami estrowymi z trzema cząsteczkami kwasów tłuszczowych.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t105-02',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Lipidy dobrze rozpuszczają się w wodzie.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — lipidy są nierozpuszczalne w wodzie, a dobrze rozpuszczają się w rozpuszczalnikach organicznych. To jedna z ich charakterystycznych cech chemicznych.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t105-03',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Który lipid jest głównym składnikiem błon komórkowych?',
      opcje: ['Fosfolipid', 'Tłuszcz właściwy', 'Skrobia', 'Kwas nukleinowy'],
      poprawna: 0,
      wyjasnienie: 'Fosfolipidy budują dwuwarstwę lipidową, która stanowi podstawę wszystkich błon komórkowych.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t105-04',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Czym różnią się kwasy tłuszczowe nasycone od nienasyconych?',
      opcje: [
        'Nienasycone mają co najmniej jedno wiązanie podwójne między atomami węgla, nasycone go nie mają',
        'Nasycone zawierają azot, a nienasycone go nie zawierają',
        'Nienasycone występują wyłącznie w organizmach zwierzęcych',
        'Nasycone rozpuszczają się w wodzie, a nienasycone nie',
      ],
      poprawna: 0,
      wyjasnienie: 'Kluczową różnicą w budowie jest obecność wiązań podwójnych między atomami węgla — nienasycone kwasy tłuszczowe mają co najmniej jedno takie wiązanie, nasycone nie mają żadnego.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t105-05',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Oliwa z oliwek jest ciekła w temperaturze pokojowej, natomiast smalec pozostaje w tych warunkach stały. Co jest główną przyczyną tej różnicy?',
      opcje: [
        'Oliwa zawiera głównie nienasycone kwasy tłuszczowe, a smalec — głównie nasycone',
        'Oliwa jest lżejsza od smalcu, dlatego pozostaje płynna',
        'Smalec zawiera więcej wody niż oliwa',
        'Oliwa nie zawiera glicerolu, a smalec zawiera',
      ],
      poprawna: 0,
      wyjasnienie: 'Tłuszcze roślinne, jak oliwa, zawierają przeważnie nienasycone kwasy tłuszczowe i są ciekłe w temperaturze pokojowej. Tłuszcze zwierzęce, jak smalec, zawierają głównie nasycone kwasy tłuszczowe i są w tych warunkach stałe.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t105-06',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych są funkcjami tłuszczów w organizmie? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Zapasowa (energetyczna)', 'Izolacyjna (termoizolacyjna)', 'Przenoszenie informacji genetycznej', 'Budulcowa (błony komórkowe)', 'Ochronna (amortyzująca narządy)'],
      poprawna: [0, 1, 3, 4],
      wyjasnienie: 'Tłuszcze pełnią funkcje zapasową, izolacyjną, budulcową (fosfolipidy w błonach) i ochronną. Przenoszenie informacji genetycznej to funkcja kwasów nukleinowych, a nie lipidów.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t105-07',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 3,
      tresc: 'Dopasuj rodzaj lipidu do pełnionej przez niego głównej funkcji.',
      dopasowanie: {
        lewa: ['Tłuszcz właściwy', 'Fosfolipid', 'Steroid (np. cholesterol)', 'Tkanka tłuszczowa pod skórą'],
        prawa: ['Funkcja izolacyjna (ochrona przed utratą ciepła)', 'Funkcja regulacyjna (np. substrat hormonów)', 'Funkcja budulcowa błon komórkowych', 'Funkcja zapasowa (magazyn energii)'],
        pary: [3, 2, 1, 0],
      },
      wyjasnienie: 'Tłuszcz właściwy magazynuje energię, fosfolipid buduje błony komórkowe, steroidy (np. cholesterol) pełnią funkcje regulacyjne, a tkanka tłuszczowa pod skórą chroni przed utratą ciepła.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t105-08',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdania właściwymi pojęciami.',
      tekstZLuka: 'Reakcja łączenia glicerolu z kwasami tłuszczowymi nazywa się {{luka1}}. Powstałe w niej wiązanie chemiczne to wiązanie {{luka2}}.',
      odpowiedziLuk: { luka1: ['estryfikacją', 'estryfikacja'], luka2: ['estrowe'] },
      wyjasnienie: 'Glicerol łączy się z kwasami tłuszczowymi w reakcji estryfikacji, tworząc wiązanie estrowe.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t105-09',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj poniższe struktury od tej, która zawiera najmniej tkanki tłuszczowej pełniącej funkcję izolacyjną, do tej, która zawiera jej najwięcej.',
      elementy: ['Chudy ptak wróblowaty żyjący w cieplejszym klimacie', 'Człowiek żyjący w klimacie umiarkowanym', 'Wieloryb żyjący w zimnych wodach oceanicznych'],
      wyjasnienie: 'Grubość warstwy izolacyjnej tkanki tłuszczowej rośnie wraz z potrzebą ochrony przed utratą ciepła w chłodnym środowisku — najwięcej tłuszczu izolacyjnego mają zwierzęta żyjące w bardzo zimnych warunkach, jak wieloryby.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t105-10',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Osoba na restrykcyjnej diecie zupełnie beztłuszczowej ma trudności z prawidłowym wchłanianiem witamin A, D, E i K, mimo że spożywa je w odpowiedniej ilości. Co najlepiej to tłumaczy?',
      opcje: [
        'Witaminy A, D, E i K są rozpuszczalne w tłuszczach i wymagają jego obecności do wchłonięcia w jelicie',
        'Tłuszcz niszczy chemicznie te witaminy, więc ich brak powinien ułatwiać wchłanianie',
        'Witaminy te są rozpuszczalne wyłącznie w wodzie',
        'Brak tłuszczu nie ma żadnego wpływu na wchłanianie witamin',
      ],
      poprawna: 0,
      wyjasnienie: 'Witaminy A, D, E i K są rozpuszczalne w tłuszczach — do ich prawidłowego wchłonięcia w jelicie niezbędna jest obecność tłuszczu w pożywieniu. Dieta zupełnie beztłuszczowa upośledza ich przyswajanie, nawet jeśli są dostarczane w pokarmie.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t105-11',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Które stwierdzenia o tłuszczach zwierzęcych i roślinnych są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Tłuszcze zwierzęce zawierają przeważnie nasycone kwasy tłuszczowe',
        'Wszystkie tłuszcze roślinne są ciekłe w temperaturze pokojowej bez wyjątków',
        'Oleje roślinne zawierają przeważnie nienasycone kwasy tłuszczowe',
        'Olej kokosowy, mimo pochodzenia roślinnego, zawiera dużo nasyconych kwasów tłuszczowych',
      ],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Tłuszcze zwierzęce zawierają głównie kwasy nasycone, a oleje roślinne — głównie nienasycone. Istnieją jednak wyjątki, jak olej kokosowy czy palmowy, które mimo pochodzenia roślinnego zawierają dużo nasyconych kwasów tłuszczowych i są półstałe.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t105-12',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż produkt, który dostarcza najwięcej energii w przeliczeniu na 100 g.',
      tabela: {
        tytul: 'Wartość energetyczna wybranych składników odżywczych (na 100 g czystego składnika)',
        kolumny: ['Składnik', 'Wartość energetyczna (kcal/100 g)'],
        wiersze: [
          ['Czysty tłuszcz', '~900 kcal'],
          ['Czyste białko', '~400 kcal'],
          ['Czysty węglowodan (skrobia)', '~400 kcal'],
        ],
      },
      opcje: ['Czysty tłuszcz', 'Czyste białko', 'Czysty węglowodan (skrobia)', 'Wszystkie dostarczają tyle samo energii'],
      poprawna: 0,
      wyjasnienie: 'Tłuszcz jest najbardziej skoncentrowanym źródłem energii — dostarcza około dwa razy więcej kalorii na gram niż białka czy węglowodany, co widać w tabeli.',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t105-13',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'image',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na diagramie budowy tłuszczu wiązania łączące glicerol z kwasami tłuszczowymi opisano jako "wiązanie estrowe". W jakiej reakcji chemicznej powstają te wiązania?',
      diagramId: 'd-t105-budowa-tluszczu',
      opcje: ['W reakcji estryfikacji, z uwolnieniem cząsteczek wody', 'W reakcji hydrolizy, z pochłonięciem cząsteczek wody', 'W reakcji fotosyntezy', 'W reakcji denaturacji'],
      poprawna: 0,
      wyjasnienie: 'Wiązania estrowe między glicerolem a kwasami tłuszczowymi powstają w reakcji estryfikacji — podobnie jak przy tworzeniu innych wiązań łączących monomery w związkach organicznych, towarzyszy jej uwolnienie cząsteczek wody.',
      umiejetnosci: ['diagram', 'wiedza'],
    },
    {
      id: 'p-t105-14',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Foki i wieloryby żyjące w zimnych wodach oceanicznych mają bardzo grubą warstwę tkanki tłuszczowej pod skórą, znacznie grubszą niż zwierzęta lądowe podobnej wielkości żyjące w klimacie umiarkowanym. Jak najlepiej wyjaśnić to przystosowanie?',
      opcje: [
        'Gruba warstwa tłuszczu pełni funkcję izolacyjną, ograniczając utratę ciepła w zimnej wodzie, która odprowadza ciepło znacznie szybciej niż powietrze',
        'Tłuszcz jest zwierzętom morskim potrzebny wyłącznie do unoszenia się na wodzie, bez znaczenia termicznego',
        'Zwierzęta morskie magazynują w ten sposób wyłącznie nadmiar wody',
        'Gruba warstwa tłuszczu chroni wyłącznie przed drapieżnikami, nie ma związku z temperaturą',
      ],
      poprawna: 0,
      wyjasnienie: 'Woda odprowadza ciepło z organizmu znacznie szybciej niż powietrze, dlatego zwierzęta morskie żyjące w zimnych wodach potrzebują znacznie grubszej warstwy izolacyjnej tkanki tłuszczowej niż zwierzęta lądowe, by utrzymać stałą temperaturę ciała.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t105-15',
      dzialId: 'd1',
      tematId: 't105',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Cholesterol jest wyłącznie szkodliwym produktem ubocznym przemiany materii i nie pełni żadnej pożytecznej funkcji w organizmie człowieka.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz. Cholesterol jest niezbędnym składnikiem błon komórkowych zwierząt i substratem do produkcji niektórych hormonów (np. płciowych). Szkodliwy dla zdrowia jest dopiero jego nadmiar w organizmie, a nie sama jego obecność.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
  ]);
})();
