(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-mieczaki-01',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Z jakich głównych części zbudowane jest ciało typowego mięczaka?',
      opcje: ['Głowa, tułów, odwłok', 'Głowa, noga, tułów trzewiowy okryty płaszczem', 'Głowotułów i odwłok', 'Segmenty z parami odnóży'],
      poprawna: 1,
      wyjasnienie: 'Ciało mięczaków zbudowane jest z głowy, mięsistej nogi (narządu ruchu) i tułowia trzewiowego mieszczącego narządy wewnętrzne, okrytego płaszczem.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-mieczaki-02',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Wszystkie mięczaki mają widoczną z zewnątrz muszlę.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — u głowonogów (np. ośmiornicy) muszla jest zredukowana, ukryta pod skórą lub całkowicie zanikła.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-mieczaki-03',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka:
        'Fałd skóry okrywający ciało mięczaka, wydzielający zwykle muszlę, nazywamy {{luka1}}. Narząd w jamie gębowej ślimaków, pokryty drobnymi ząbkami i służący do zeskrobywania pokarmu, to {{luka2}}.',
      odpowiedziLuk: { luka1: ['płaszczem', 'płaszcz'], luka2: ['tarka', 'tarką', 'radula', 'radulą'] },
      wyjasnienie: 'Płaszcz to fałd skóry wydzielający muszlę, a tarka (radula) to narząd służący do zeskrobywania pokarmu, np. glonów z podłoża.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-mieczaki-04',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'image',
      poziom: 'latwy',
      punkty: 1,
      diagramId: 'd-t206-mieczaki-slimak',
      tresc: 'Na diagramie budowy ślimaka element oznaczony numerem 4 to noga. Do czego służy?',
      opcje: ['Do chwytania pokarmu', 'Do pełzania po podłożu', 'Do wymiany gazowej', 'Do wykrywania dźwięków'],
      poprawna: 1,
      wyjasnienie: 'Noga to mięsisty, szeroki narząd ruchu ślimaka, dzięki falistym skurczom którego zwierzę przesuwa się po podłożu.',
      umiejetnosci: ['diagram', 'wiedza'],
    },
    {
      id: 'p-t206-mieczaki-05',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Czym różni się sposób odżywiania małża od sposobu odżywiania ślimaka?',
      opcje: [
        'Małż jest filtratorem i odfiltrowuje cząstki pokarmowe z wody za pomocą skrzeli, a ślimak zeskrobuje pokarm tarką',
        'Małż poluje aktywnie za pomocą macek, a ślimak jest filtratorem',
        'Oba odżywiają się wyłącznie fotosyntezą',
        'Małż zeskrobuje pokarm tarką, a ślimak filtruje wodę skrzelami',
      ],
      poprawna: 0,
      wyjasnienie: 'Małże nie mają tarki ani wyodrębnionej głowy — filtrują wodę za pomocą skrzeli, odfiltrowując z niej drobne cząstki pokarmowe. Ślimaki zeskrobują pokarm tarką znajdującą się w jamie gębowej.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-mieczaki-06',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych cech są prawdziwe dla głowonogów? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Mają zredukowaną lub niewidoczną muszlę',
        'Poruszają się dzięki napędowi odrzutowemu',
        'Mają otwarty układ krwionośny, tak jak większość mięczaków',
        'Mają chromatofory umożliwiające zmianę barwy ciała',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Głowonogi mają zredukowaną muszlę, poruszają się dzięki napędowi odrzutowemu i mają chromatofory. W odróżnieniu od większości mięczaków, mają zamknięty, a nie otwarty układ krwionośny.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-mieczaki-07',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj grupę mięczaków do cechy jej budowy.',
      dopasowanie: {
        lewa: ['Ślimaki', 'Małże', 'Głowonogi'],
        prawa: [
          'Muszla dwuczęściowa (dwie klapy), brak głowy i tarki, filtratory',
          'Zredukowana lub niewidoczna muszla, macki, napęd odrzutowy',
          'Zwykle jedna, spiralnie skręcona muszla, wyraźna głowa z czułkami, tarka',
        ],
        pary: [2, 0, 1],
      },
      wyjasnienie: 'Ślimaki mają jedną, spiralną muszlę i tarkę, małże mają muszlę dwuczęściową i są filtratorami bez głowy, a głowonogi mają zredukowaną muszlę i poruszają się dzięki napędowi odrzutowemu.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-mieczaki-08',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'diagram',
      poziom: 'sredni',
      punkty: 2,
      diagramId: 'd-t206-mieczaki-glowonog',
      tresc: 'Na diagramie budowy głowonoga element oznaczony numerem 4 to lejek. Jaką pełni funkcję?',
      opcje: [
        'Wytwarza muszlę',
        'Wyrzuca strumień wody, umożliwiając napęd odrzutowy',
        'Służy do wykrywania światła',
        'Pełni funkcję tarki do rozdrabniania pokarmu',
      ],
      poprawna: 1,
      wyjasnienie: 'Lejek u głowonogów służy do gwałtownego wyrzucania strumienia wody z jamy płaszczowej, co napędza zwierzę w przeciwnym kierunku (napęd odrzutowy).',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-mieczaki-09',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego głowonogi, w przeciwieństwie do większości mięczaków, mają zamknięty układ krwionośny?',
      opcje: [
        'Bo żyją wyłącznie na lądzie i potrzebują szybszego metabolizmu',
        'Bo prowadzą aktywny tryb życia (szybkie polowanie, ucieczka przed drapieżnikami), co wymaga wydajniejszego, kontrolowanego transportu tlenu do tkanek',
        'Bo nie mają wcale układu krwionośnego',
        'Bo ich ciało jest okryte twardą muszlą, która wymaga innego rodzaju krążenia',
      ],
      poprawna: 1,
      wyjasnienie: 'Aktywny tryb życia głowonogów — szybkie pływanie, polowanie, ucieczka przed drapieżnikami — wymaga sprawnego dostarczania tlenu do mięśni, co zapewnia zamknięty układ krwionośny lepiej niż otwarty.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-mieczaki-10',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Do czego głowonogom służą chromatofory w skórze?',
      opcje: [
        'Do trawienia pokarmu',
        'Do szybkiej zmiany barwy ciała, np. w celu maskowania się lub komunikacji',
        'Do filtrowania wody z pokarmem',
        'Do wytwarzania muszli',
      ],
      poprawna: 1,
      wyjasnienie: 'Chromatofory to komórki barwnikowe w skórze głowonogów, które umożliwiają im szybką zmianę koloru ciała — np. w celu ukrycia się przed drapieżnikiem.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-mieczaki-11',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Ślimaki lądowe, takie jak ślimak winniczek, oddychają płucem.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — ślimaki lądowe mają uproszczone płuco (jamę płaszczową przystosowaną do oddychania powietrzem), w przeciwieństwie do ślimaków wodnych, które oddychają skrzelami.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-mieczaki-12',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj etapy powstawania perły w małżu, zaczynając od dostania się ciała obcego.',
      elementy: [
        'Ciało obce (np. ziarnko piasku) dostaje się między płaszcz a muszlę',
        'Płaszcz zaczyna otaczać ciało obce kolejnymi warstwami substancji budującej muszlę',
        'Warstwy narastają wokół ciała obcego przez dłuższy czas',
        'Powstaje twarda, lśniąca perła',
      ],
      wyjasnienie: 'Perła powstaje, gdy płaszcz małża otacza ciało obce kolejnymi warstwami tej samej substancji, z której budowana jest muszla — proces ten trwa zwykle wiele miesięcy lub lat.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-mieczaki-13',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Jakie znaczenie mają małże dla czystości zbiorników wodnych?',
      opcje: [
        'Zanieczyszczają wodę, wydzielając toksyny',
        'Filtrując duże ilości wody w poszukiwaniu pokarmu, oczyszczają ją i mogą służyć jako bioindykator czystości wody',
        'Nie mają żadnego wpływu na jakość wody',
        'Pochłaniają cały tlen rozpuszczony w wodzie, szkodząc innym organizmom',
      ],
      poprawna: 1,
      wyjasnienie: 'Małże, filtrując wodę w poszukiwaniu pokarmu, usuwają z niej zawieszone cząstki, co przyczynia się do jej oczyszczania — dlatego są wykorzystywane jako bioindykatory czystości wód.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-mieczaki-14',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'multiple',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Które z poniższych zwierząt są przedstawicielami głowonogów? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Ośmiornica', 'Ślimak winniczek', 'Kałamarnica', 'Mątwa'],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Ośmiornica, kałamarnica i mątwa to głowonogi. Ślimak winniczek należy do ślimaków (gastropoda), a nie do głowonogów.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-mieczaki-15',
      dzialId: 'd2',
      tematId: 't206-mieczaki',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Dlaczego u ślimaków tarka (radula) uznawana jest za cechę budowa-funkcja typową dla trybu odżywiania tej grupy?',
      opcje: [
        'Bo umożliwia zeskrobywanie i rozdrabnianie pokarmu (np. glonów) z podłoża, co jest podstawowym sposobem żerowania wielu ślimaków',
        'Bo służy wyłącznie do obrony przed drapieżnikami',
        'Bo umożliwia filtrowanie wody, tak jak u małży',
        'Bo jest narządem oddechowym, a nie pokarmowym',
      ],
      poprawna: 0,
      wyjasnienie: 'Tarka pokryta drobnymi, chitynowymi ząbkami służy ślimakom (i głowonogom) do zeskrobywania i rozdrabniania pokarmu, np. glonów porastających podłoże — jest to bezpośrednie przystosowanie budowy do funkcji pobierania pokarmu.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
  ]);
})();
