(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t111-01',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Czym jest enzym?',
      opcje: [
        'Białkiem przyspieszającym reakcje chemiczne w komórce',
        'Rodzajem cukru zapasowego',
        'Nośnikiem energii magazynowanym w komórce',
        'Produktem ubocznym oddychania komórkowego',
      ],
      poprawna: 0,
      wyjasnienie: 'Enzym to białko, które przyspiesza (katalizuje) przebieg reakcji chemicznej w komórce, samo się przy tym nie zużywając.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t111-02',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Enzym zużywa się w trakcie reakcji, którą katalizuje.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — enzym po zakończeniu reakcji uwalnia się w niezmienionej postaci i może katalizować kolejne cząsteczki substratu.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t111-03',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Reakcje, w których z prostych związków powstają związki bardziej złożone, a energia jest pochłaniana, to:',
      opcje: ['Katabolizm', 'Anabolizm', 'Denaturacja', 'Specyficzność substratowa'],
      poprawna: 1,
      wyjasnienie: 'Anabolizm to reakcje syntezy złożonych związków z prostszych, przebiegające z pochłanianiem energii, np. fotosynteza.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t111-04',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Substancja, na którą działa enzym, to {{luka1}}, a substancja powstająca w wyniku reakcji to {{luka2}}.',
      odpowiedziLuk: { luka1: ['substrat'], luka2: ['produkt'] },
      wyjasnienie: 'Enzym przekształca substrat w produkt, łącząc się z nim w miejscu aktywnym.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t111-05',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Fotosynteza jest przykładem reakcji katabolicznej.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — fotosynteza jest przykładem anabolizmu, ponieważ z prostych związków (CO2 i wody) powstaje bardziej złożony związek — glukoza — z pochłonięciem energii świetlnej.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t111-06',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Co dzieje się z aktywnością enzymu w temperaturze znacznie wyższej niż jego temperatura optymalna?',
      opcje: [
        'Aktywność rośnie jeszcze bardziej',
        'Aktywność pozostaje bez zmian',
        'Aktywność gwałtownie spada na skutek denaturacji białka',
        'Enzym zamienia się w substrat',
      ],
      poprawna: 2,
      wyjasnienie: 'Zbyt wysoka temperatura prowadzi do denaturacji, czyli trwałego zniszczenia struktury przestrzennej białka enzymatycznego, przez co traci ono zdolność katalizowania reakcji.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t111-07',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych procesów są przykładami katabolizmu? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Oddychanie komórkowe', 'Fotosynteza', 'Trawienie skrobi do cukrów prostych', 'Budowanie białka z aminokwasów'],
      poprawna: [0, 2],
      wyjasnienie: 'Oddychanie komórkowe i trawienie skrobi to rozkład złożonych związków na prostsze (katabolizm). Fotosynteza i budowanie białka to synteza złożonych związków (anabolizm).',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t111-08',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj pojęcie do jego definicji.',
      dopasowanie: {
        lewa: ['Enzym', 'Substrat', 'Produkt', 'ATP'],
        prawa: ['Substancja powstająca w wyniku reakcji', 'Uniwersalny nośnik energii w komórce', 'Białko katalizujące reakcję chemiczną', 'Substancja, na którą działa enzym'],
        pary: [2, 3, 0, 1],
      },
      wyjasnienie: 'Enzym to białko katalizujące reakcję, substrat to substancja przekształcana, produkt to jej efekt, a ATP to nośnik energii w komórce.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t111-09',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj etapy działania enzymu — od kontaktu z substratem do uwolnienia produktu.',
      elementy: ['Substrat zbliża się do miejsca aktywnego enzymu', 'Powstaje kompleks enzym–substrat', 'Substrat zostaje przekształcony w produkt', 'Enzym uwalnia produkt i pozostaje niezmieniony'],
      wyjasnienie: 'Enzym łączy się z substratem w miejscu aktywnym, tworząc kompleks enzym–substrat, katalizuje przekształcenie substratu w produkt, po czym uwalnia produkt i może działać ponownie.',
      umiejetnosci: ['analiza'],
    },
    {
      id: 'p-t111-10',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Ugotowane (poddane wysokiej temperaturze) białko jaja kurzego trwale zmienia swoją strukturę i konsystencję. Jakim procesem to zjawisko najlepiej wyjaśnić w kontekście działania enzymów?',
      opcje: ['Specyficznością substratową', 'Denaturacją białka', 'Obniżeniem energii aktywacji', 'Powstaniem kompleksu enzym–substrat'],
      poprawna: 1,
      wyjasnienie: 'Wysoka temperatura powoduje denaturację białek, czyli trwałe zniszczenie ich struktury przestrzennej. Ten sam mechanizm sprawia, że enzymy tracą aktywność w wysokiej temperaturze.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t111-11',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Każdy enzym może katalizować dowolną reakcję chemiczną w komórce, niezależnie od rodzaju substratu.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — enzymy wykazują specyficzność substratową, czyli działają zwykle tylko na jeden rodzaj substratu lub wąską grupę podobnych substancji, dzięki dopasowaniu kształtu miejsca aktywnego.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t111-12',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'W doświadczeniu zmierzono szybkość reakcji katalizowanej przez pewien enzym w różnych temperaturach. Na podstawie danych w tabeli określ, w jakiej przybliżonej temperaturze enzym działał najskuteczniej.',
      tabela: {
        tytul: 'Szybkość reakcji enzymatycznej w zależności od temperatury',
        kolumny: ['Temperatura (°C)', 'Szybkość reakcji (jednostki umowne)'],
        wiersze: [
          ['10', '10'],
          ['20', '35'],
          ['37', '100'],
          ['50', '20'],
          ['70', '0'],
        ],
      },
      opcje: ['10°C', '20°C', '37°C', '70°C'],
      poprawna: 2,
      wyjasnienie: 'Szybkość reakcji jest największa przy 37°C — to temperatura optymalna dla tego enzymu. Powyżej niej szybkość gwałtownie spada na skutek postępującej denaturacji białka.',
      umiejetnosci: ['analiza', 'tabela'],
    },
    {
      id: 'p-t111-13',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Podczas wysokiej gorączki (powyżej 41–42°C) funkcjonowanie organizmu człowieka jest poważnie zagrożone. Co jest najbardziej prawdopodobną biochemiczną przyczyną tego zagrożenia?',
      opcje: [
        'Enzymy w komórkach ulegają nieodwracalnej denaturacji i przestają działać',
        'Wzrasta stężenie substratów, co spowalnia wszystkie reakcje',
        'Komórki przestają produkować ATP z powodu braku tlenu',
        'Enzymy zmieniają substraty na produkty w odwrotnym kierunku',
      ],
      poprawna: 0,
      wyjasnienie: 'Enzymy są białkami, więc bardzo wysoka temperatura powoduje ich denaturację — trwałą utratę struktury i aktywności. Skutkiem jest zaburzenie przebiegu kluczowych reakcji metabolicznych w komórkach.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t111-14',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Dopasuj rodzaj enzymu trawiennego do substratu, na który działa.',
      dopasowanie: {
        lewa: ['Amylaza', 'Lipaza', 'Proteaza'],
        prawa: ['Białka', 'Skrobia (cukry złożone)', 'Tłuszcze'],
        pary: [1, 2, 0],
      },
      wyjasnienie: 'Amylaza rozkłada skrobię do cukrów prostszych, lipaza rozkłada tłuszcze, a proteaza rozkłada białka — nazwa enzymu zwykle wskazuje na rodzaj substratu, na który działa.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t111-15',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie dotyczące roli enzymów w reakcjach chemicznych.',
      tekstZLuka: 'Enzymy przyspieszają reakcje chemiczne, ponieważ obniżają {{luka1}} potrzebną do jej rozpoczęcia, dzięki czemu reakcja może zajść znacznie {{luka2}}.',
      odpowiedziLuk: { luka1: ['energię aktywacji', 'energia aktywacji'], luka2: ['szybciej'] },
      wyjasnienie: 'Enzymy obniżają energię aktywacji reakcji, czyli ilość energii potrzebną do jej zapoczątkowania, dzięki czemu reakcja przebiega znacznie szybciej niż bez ich udziału.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t111-16',
      dzialId: 'd1',
      tematId: 't111',
      typ: 'ordering',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uporządkuj zmiany szybkości reakcji enzymatycznej wraz ze wzrostem temperatury od 0°C do 80°C.',
      elementy: [
        'Bardzo powolna reakcja w temperaturze bliskiej 0°C',
        'Stopniowy wzrost szybkości reakcji wraz z ogrzewaniem',
        'Maksymalna szybkość reakcji w temperaturze optymalnej',
        'Gwałtowny spadek aktywności na skutek denaturacji enzymu',
      ],
      wyjasnienie: 'Przy niskiej temperaturze reakcje enzymatyczne przebiegają wolno. Wraz ze wzrostem temperatury szybkość rośnie aż do temperatury optymalnej, po przekroczeniu której następuje denaturacja enzymu i gwałtowny spadek jego aktywności.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
  ]);
})();
