(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t116-k1',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Które zdanie poprawnie opisuje różnicę między wzrostem a rozwojem organizmu?',
      opcje: [
        'Wzrost to trwały przyrost masy i wielkości ciała, a rozwój to zmiany jakościowe prowadzące do osiągnięcia dojrzałości',
        'Wzrost i rozwój to dokładnie to samo zjawisko',
        'Rozwój to wyłącznie zwiększanie liczby komórek, a wzrost dotyczy tylko zmian w zachowaniu',
        'Wzrost zachodzi tylko u roślin, a rozwój tylko u zwierząt',
      ],
      poprawna: 0,
      wyjasnienie:
        'Wzrost to ilościowy, trwały przyrost masy i rozmiarów ciała (np. dzięki podziałom i powiększaniu się komórek), natomiast rozwój to zmiany jakościowe — różnicowanie komórek, kształtowanie narządów i funkcji — prowadzące organizm od stadium młodocianego do dojrzałości.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t116-k2',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Rozwój organizmu polega wyłącznie na zwiększaniu jego masy i rozmiarów ciała.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie:
        'Fałsz — to opis wzrostu. Rozwój obejmuje przede wszystkim zmiany jakościowe: różnicowanie się komórek i tkanek, kształtowanie narządów oraz zmiany funkcji organizmu w kolejnych stadiach życia.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t116-03',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc:
        'U motyla larwa (gąsienica) różni się bardzo wyglądem od postaci dorosłej, a między tymi stadiami występuje nieruchome stadium poczwarki. Jak nazywamy taki typ rozwoju?',
      opcje: ['Rozwój prosty', 'Przeobrażenie niezupełne', 'Przeobrażenie zupełne', 'Wzrost prosty'],
      poprawna: 2,
      wyjasnienie:
        'To przeobrażenie (metamorfoza) zupełne — obejmuje cztery stadia: jajo, larwę, poczwarkę i postać dorosłą (imago), przy czym larwa wyraźnie różni się budową od dorosłego owada.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t116-04',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij nazwy stadiów rozwoju owada z przeobrażeniem zupełnym.',
      tekstZLuka:
        'Z jaja wykluwa się {{luka1}}, która po okresie żerowania i wzrostu przechodzi w nieruchome stadium {{luka2}}, z którego wykształca się postać dorosła.',
      odpowiedziLuk: { luka1: ['larwa'], luka2: ['poczwarki', 'poczwarka'] },
      wyjasnienie: 'Kolejność stadiów przy przeobrażeniu zupełnym to: jajo → larwa → poczwarka → postać dorosła (imago).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t116-05',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc:
        'Konik polny wykluwa się z jaja jako młody osobnik przypominający wyglądem postać dorosłą (brak skrzydeł, mniejsze rozmiary), a w kolejnych wylinkach stopniowo upodabnia się do dorosłego owada, bez stadium poczwarki. Jaki to typ rozwoju?',
      opcje: ['Przeobrażenie zupełne', 'Przeobrażenie niezupełne', 'Rozwój prosty, taki jak u ssaków', 'Rozmnażanie bezpłciowe'],
      poprawna: 1,
      wyjasnienie:
        'To przeobrażenie niezupełne — młody osobnik (nimfa) przypomina wyglądem postać dorosłą, brakuje stadium poczwarki, a dojrzewanie następuje stopniowo poprzez kolejne wylinki.',
      umiejetnosci: ['analiza'],
    },
    {
      id: 'p-t116-06',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Zaznacz cechy charakterystyczne dla przeobrażenia zupełnego.',
      opcje: [
        'Występuje stadium poczwarki',
        'Larwa wygląda bardzo podobnie do postaci dorosłej',
        'Larwa (np. gąsienica) różni się budową od postaci dorosłej',
        'Rozwój obejmuje cztery stadia: jajo, larwę, poczwarkę i postać dorosłą',
        'Brak jakichkolwiek przeobrażeń w cyklu życiowym',
      ],
      poprawna: [0, 2, 3],
      wyjasnienie:
        'Przeobrażenie zupełne charakteryzuje się obecnością stadium poczwarki, dużymi różnicami w budowie między larwą a postacią dorosłą oraz czterema stadiami rozwoju: jajo, larwa, poczwarka, postać dorosła.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t116-07',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj nazwę stadium rozwojowego do jego opisu.',
      dopasowanie: {
        lewa: ['Larwa', 'Poczwarka', 'Imago (postać dorosła)', 'Nimfa'],
        prawa: [
          'Stadium zdolne do rozmnażania, w pełni ukształtowane',
          'Ruchliwe stadium żerujące, znacznie różniące się od dorosłego owada (przeobrażenie zupełne)',
          'Nieruchome stadium przejściowe, w którym zachodzi przebudowa ciała',
          'Młody osobnik przypominający dorosłego, typowy dla przeobrażenia niezupełnego',
        ],
        pary: [1, 2, 0, 3],
      },
      wyjasnienie:
        'Larwa to ruchliwe, żerujące stadium różniące się od dorosłego (przeobrażenie zupełne). Poczwarka to nieruchome stadium przejściowe. Imago to w pełni ukształtowana, zdolna do rozmnażania postać dorosła. Nimfa to młody osobnik przypominający dorosłego, charakterystyczny dla przeobrażenia niezupełnego.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t116-08',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj stadia rozwoju motyla (przeobrażenie zupełne) w prawidłowej kolejności.',
      elementy: ['Jajo', 'Larwa (gąsienica)', 'Poczwarka', 'Postać dorosła (imago)'],
      wyjasnienie: 'Rozwój motyla przebiega w kolejności: jajo → larwa (gąsienica) → poczwarka → postać dorosła (imago).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t116-09',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc:
        'Dlaczego u owadów z przeobrażeniem zupełnym larwa i postać dorosła zwykle różnią się znacznie budową ciała i sposobem odżywiania?',
      opcje: [
        'Ponieważ larwa i postać dorosła to w rzeczywistości dwa różne gatunki żyjące razem',
        'Ponieważ różnice w budowie i trybie życia pozwalają larwie i postaci dorosłej korzystać z innych źródeł pokarmu i unikać wzajemnej konkurencji o zasoby środowiska',
        'Ponieważ larwa nie ma jeszcze materiału genetycznego',
        'Ponieważ poczwarka zmienia gatunek owada',
      ],
      poprawna: 1,
      wyjasnienie:
        'Duże różnice w budowie ciała między larwą a postacią dorosłą (np. gąsienica żerująca na liściach i motyl odżywiający się nektarem) sprawiają, że oba stadia nie konkurują ze sobą o ten sam pokarm ani przestrzeń życiową — to zwiększa szanse przeżycia gatunku.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t116-10',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc:
        'Nimfa u owadów z przeobrażeniem niezupełnym przypomina wyglądem postać dorosłą, ale nie ma jeszcze w pełni wykształconych skrzydeł i narządów rozrodczych.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie:
        'Prawda — nimfa jest miniaturową, niedojrzałą wersją postaci dorosłej; brakuje jej w pełni wykształconych skrzydeł i zdolności do rozmnażania, które osiąga stopniowo po kolejnych wylinkach.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t116-11',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które stwierdzenia dotyczące rozwoju złożonego (z przeobrażeniem) są prawdziwe? Zaznacz wszystkie poprawne.',
      opcje: [
        'Przeobrażenie zupełne obejmuje stadium poczwarki, a niezupełne nie',
        'Wszystkie owady przechodzą przeobrażenie zupełne',
        'Nimfa jest charakterystyczna dla przeobrażenia niezupełnego',
        'W przeobrażeniu niezupełnym młody osobnik przypomina wyglądem postać dorosłą bardziej niż w przeobrażeniu zupełnym',
        'Ssaki, w tym człowiek, przechodzą typowe przeobrażenie zupełne',
      ],
      poprawna: [0, 2, 3],
      wyjasnienie:
        'Przeobrażenie zupełne ma stadium poczwarki, którego brak w niezupełnym. Nimfa to stadium typowe dla przeobrażenia niezupełnego i przypomina dorosłego bardziej niż larwa w przeobrażeniu zupełnym. Nie wszystkie owady przechodzą przeobrażenie zupełne (np. konik polny — niezupełne), a ssaki mają rozwój prosty, bez przeobrażenia.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t116-12',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli porównującej oba typy przeobrażenia wskaż zdanie prawdziwe.',
      tabela: {
        tytul: 'Przeobrażenie zupełne a niezupełne',
        kolumny: ['Cecha', 'Przeobrażenie zupełne', 'Przeobrażenie niezupełne'],
        wiersze: [
          ['Liczba stadiów', '4 (jajo, larwa, poczwarka, dorosły)', '3 (jajo, nimfa, dorosły)'],
          ['Obecność poczwarki', 'Tak', 'Nie'],
          ['Podobieństwo larwy/nimfy do dorosłego', 'Małe', 'Duże'],
          ['Przykład', 'Motyl, chrząszcz, mucha', 'Konik polny, ważka, pluskwiak'],
        ],
      },
      opcje: [
        'Przeobrażenie niezupełne obejmuje stadium poczwarki',
        'W przeobrażeniu zupełnym młode stadium jest bardzo podobne do postaci dorosłej',
        'Przeobrażenie zupełne obejmuje cztery stadia rozwojowe, w tym poczwarkę',
        'Konik polny jest przykładem owada z przeobrażeniem zupełnym',
      ],
      poprawna: 2,
      wyjasnienie:
        'Zgodnie z tabelą przeobrażenie zupełne obejmuje cztery stadia (jajo, larwa, poczwarka, postać dorosła) i występuje np. u motyli. Przeobrażenie niezupełne nie ma poczwarki, a młode stadium (nimfa) przypomina dorosłego, co dotyczy np. konika polnego.',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t116-13',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc:
        'Jaka jest główna ewolucyjna korzyść z rozdzielenia funkcji między różniące się od siebie stadia larwalne i postać dorosłą u owadów z przeobrażeniem zupełnym?',
      opcje: [
        'Larwa i postać dorosła mogą wykorzystywać różne środowiska i źródła pokarmu, co zmniejsza konkurencję wewnątrzgatunkową o zasoby',
        'Poczwarka pozwala owadowi zmienić gatunek na lepiej przystosowany',
        'Larwa nigdy nie potrzebuje pokarmu, więc oszczędza energię całej populacji',
        'Przeobrażenie zupełne skraca cykl życiowy owada do jednego dnia',
      ],
      poprawna: 0,
      wyjasnienie:
        'Rozdzielenie funkcji odżywiania (larwa) i rozmnażania/rozprzestrzeniania (postać dorosła), połączone z wykorzystywaniem odmiennych siedlisk i pokarmu przez oba stadia, ogranicza konkurencję o zasoby w obrębie tego samego gatunku i zwiększa szanse przetrwania populacji.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t116-14',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dopasuj organizm do typu jego rozwoju osobniczego.',
      dopasowanie: {
        lewa: ['Pies domowy', 'Motyl', 'Konik polny', 'Żaba trawna'],
        prawa: [
          'Rozwój prosty (młode przypomina dorosłego od urodzenia)',
          'Rozwój złożony z przeobrażeniem zupełnym',
          'Rozwój złożony z przeobrażeniem niezupełnym',
          'Rozwój złożony z przeobrażeniem (metamorfoza larwy wodnej w formę lądową)',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie:
        'Pies ma rozwój prosty — młode od urodzenia przypomina dorosłego. Motyl przechodzi przeobrażenie zupełne (z poczwarką). Konik polny — przeobrażenie niezupełne (nimfa). Żaba przechodzi przeobrażenie związane ze zmianą środowiska życia — kijanka (forma wodna, oddychająca skrzelami) przekształca się w dorosłą żabę przystosowaną do życia lądowego.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t116-15',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdania dotyczące rozwoju owadów precyzyjnymi pojęciami.',
      tekstZLuka:
        'Owady, u których młody osobnik od wyklucia przypomina wyglądem postać dorosłą i nie występuje stadium poczwarki, przechodzą przeobrażenie {{luka1}}. Młode stadium takiego owada nazywamy {{luka2}}.',
      odpowiedziLuk: { luka1: ['niezupełne'], luka2: ['nimfą', 'nimfa'] },
      wyjasnienie: 'Przeobrażenie niezupełne nie ma stadium poczwarki, a młody osobnik, przypominający dorosłego, to nimfa.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t116-16',
      dzialId: 'd1',
      tematId: 't116',
      typ: 'diagram',
      poziom: 'konkursowy',
      punkty: 2,
      diagramId: 'd-t116-przeobrazenie',
      tresc: 'Na diagramie przedstawiono dwa cykle rozwojowe owadów. Które zdanie poprawnie opisuje różnicę między nimi?',
      opcje: [
        'Górny cykl (przeobrażenie zupełne) ma o jedno stadium więcej niż dolny (zawiera poczwarkę), której brakuje w przeobrażeniu niezupełnym',
        'Oba cykle mają dokładnie taką samą liczbę stadiów',
        'Dolny cykl (przeobrażenie niezupełne) zawiera stadium poczwarki, a górny nie',
        'W obu cyklach młode stadium jest identyczne z postacią dorosłą',
      ],
      poprawna: 0,
      wyjasnienie:
        'Diagram pokazuje, że przeobrażenie zupełne obejmuje cztery stadia (jajo, larwa, poczwarka, postać dorosła), a przeobrażenie niezupełne — tylko trzy (jajo, nimfa, postać dorosła), bez stadium poczwarki.',
      umiejetnosci: ['diagram', 'analiza'],
    },
  ]);
})();
