(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t202-01',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Z jakich dwóch podstawowych elementów zbudowany jest każdy wirus?',
      opcje: [
        'Z kwasu nukleinowego i kapsydu białkowego',
        'Z cytoplazmy i błony komórkowej',
        'Z jądra komórkowego i rybosomów',
        'Ze ściany komórkowej i nukleoidu',
      ],
      poprawna: 0,
      wyjasnienie: 'Każdy wirus zawiera kwas nukleinowy (DNA lub RNA) niosący informację genetyczną oraz otaczający go kapsyd — płaszcz białkowy chroniący ten materiał genetyczny. Wirus nie ma cytoplazmy, błony komórkowej ani rybosomów, bo nie jest komórką.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t202-02',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Wirus może namnażać się samodzielnie, poza żywą komórką gospodarza.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — wirus nie ma własnego metabolizmu ani rybosomów, dlatego do namnożenia musi wniknąć do żywej komórki gospodarza i wykorzystać jej aparat komórkowy do produkcji białek i kopiowania materiału genetycznego.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t202-03',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jak nazywa się płaszcz białkowy chroniący kwas nukleinowy wirusa?',
      opcje: ['Kapsyd', 'Nukleoid', 'Otoczka jądrowa', 'Ściana komórkowa'],
      poprawna: 0,
      wyjasnienie: 'Płaszcz białkowy otaczający i chroniący kwas nukleinowy wirusa nazywa się kapsydem.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t202-04',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka:
        'Materiałem genetycznym wirusa jest {{luka1}} — DNA albo RNA. Wirus namnaża się wyłącznie wewnątrz żywej komórki zwanej komórką {{luka2}}.',
      odpowiedziLuk: { luka1: ['kwas nukleinowy'], luka2: ['gospodarza'] },
      wyjasnienie: 'Materiałem genetycznym wirusa jest kwas nukleinowy (DNA lub RNA), a komórkę, w której wirus się namnaża, nazywamy komórką gospodarza.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t202-05',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych chorób człowieka są wywoływane przez wirusy? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Grypa', 'Odra', 'Ospa wietrzna', 'Angina bakteryjna'],
      poprawna: [0, 1, 2],
      wyjasnienie: 'Grypa, odra i ospa wietrzna są chorobami wirusowymi. Angina bakteryjna, jak sama nazwa wskazuje, jest wywoływana przez bakterie, a nie przez wirusy.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t202-06',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj element budowy wirusa do jego funkcji.',
      dopasowanie: {
        lewa: ['Kwas nukleinowy', 'Kapsyd', 'Otoczka lipidowa', 'Białka powierzchniowe (kolce)'],
        prawa: [
          'Umożliwiają rozpoznanie i związanie się z komórką gospodarza',
          'Niesie informację genetyczną wirusa',
          'Dodatkowa błona zewnętrzna występująca tylko u niektórych wirusów',
          'Płaszcz białkowy chroniący materiał genetyczny',
        ],
        pary: [1, 3, 2, 0],
      },
      wyjasnienie: 'Kwas nukleinowy niesie informację genetyczną, kapsyd chroni ją jako płaszcz białkowy, otoczka lipidowa to dodatkowa błona zewnętrzna u niektórych wirusów, a białka powierzchniowe (kolce) umożliwiają związanie się z komórką gospodarza.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t202-07',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj etapy namnażania wirusa w komórce gospodarza we właściwej kolejności.',
      elementy: [
        'Wirus przyłącza się do powierzchni komórki gospodarza',
        'Wirus wprowadza swój materiał genetyczny do wnętrza komórki',
        'Komórka gospodarza wytwarza kopie kwasu nukleinowego i białek wirusa',
        'Powstają nowe cząstki wirusa',
        'Komórka gospodarza pęka i uwalnia nowe wirusy',
      ],
      wyjasnienie: 'Namnażanie wirusa przebiega w kolejności: przyłączenie do komórki → wprowadzenie materiału genetycznego → wytwarzanie kopii kwasu nukleinowego i białek przez komórkę gospodarza → powstanie nowych cząstek wirusa → pęknięcie komórki i uwolnienie wirusów, które atakują kolejne komórki.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t202-08',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'diagram',
      poziom: 'sredni',
      punkty: 2,
      diagramId: 'd-t202-budowa-wirusa',
      tresc: 'Na schemacie budowy wirusa element oznaczony numerem 3 to płaszcz białkowy otaczający materiał genetyczny. Jak się on nazywa?',
      opcje: ['Kapsyd', 'Otoczka lipidowa', 'Kwas nukleinowy', 'Białko powierzchniowe'],
      poprawna: 0,
      wyjasnienie: 'Numer 3 na schemacie oznacza kapsyd — płaszcz białkowy chroniący materiał genetyczny wirusa, umieszczony bezpośrednio wokół kwasu nukleinowego (numer 4).',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t202-09',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'image',
      poziom: 'trudny',
      punkty: 2,
      diagramId: 'd-t202-budowa-wirusa',
      tresc: 'Na schemacie widoczna jest przerywana struktura oznaczona numerem 1, otaczająca kapsyd wirusa, z osadzonymi w niej elementami numer 2. Co to za struktura i dlaczego zaznaczono ją liniami przerywanymi (a nie każdy wirus ją posiada)?',
      opcje: [
        'To otoczka lipidowa — dodatkowa błona zewnętrzna występująca tylko u niektórych wirusów (np. wirusa grypy)',
        'To ściana komórkowa — element występujący u wszystkich wirusów',
        'To błona jądrowa — struktura otaczająca materiał genetyczny w jądrze komórkowym',
        'To cytoplazma — wnętrze komórki wirusa',
      ],
      poprawna: 0,
      wyjasnienie: 'Numer 1 oznacza otoczkę lipidową — dodatkową błonę zewnętrzną, którą mają tylko niektóre wirusy (np. wirus grypy), dlatego na schemacie zaznaczono ją linią przerywaną. Wirusy roślinne czy niektóre wirusy bezotoczkowe takiej struktury nie posiadają — jedynymi elementami obecnymi u każdego wirusa są kapsyd i kwas nukleinowy.',
      umiejetnosci: ['diagram', 'analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t202-10',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dlaczego antybiotyki, skuteczne w leczeniu zakażeń bakteryjnych, nie działają na wirusy?',
      opcje: [
        'Antybiotyki niszczą struktury typowe dla komórek bakteryjnych (np. ścianę komórkową, rybosomy bakteryjne), a wirus takich struktur nie posiada',
        'Wirusy są zbyt małe, żeby cząsteczki antybiotyku mogły do nich dotrzeć',
        'Antybiotyki działają wyłącznie na organizmy wielokomórkowe',
        'Wirusy szybko wykształcają odporność na wszystkie znane antybiotyki',
      ],
      poprawna: 0,
      wyjasnienie: 'Antybiotyki działają na struktury charakterystyczne dla komórek bakteryjnych (np. ścianę komórkową czy bakteryjne rybosomy). Wirus nie jest komórką i nie ma żadnej z tych struktur, więc antybiotyki nie mają na co działać — dlatego nie stosuje się ich w leczeniu grypy czy przeziębienia.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t202-11',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Wirus poza komórką gospodarza wykazuje takie same cechy życia jak żywa komórka — rośnie, oddycha i reaguje na bodźce.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz. Poza komórką gospodarza wirus nie wykazuje żadnych cech życia — nie rośnie, nie oddycha, nie reaguje na bodźce. Dlatego wirusy uznaje się za formy materii na pograniczu życia, a nie w pełni żywe organizmy.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t202-12',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych stwierdzeń o wirusach są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Wirus zawiera zawsze tylko jeden rodzaj kwasu nukleinowego — DNA albo RNA, nigdy oba naraz',
        'Wirusy mogą atakować nie tylko ludzi i zwierzęta, ale też rośliny',
        'Każdy wirus ma otoczkę lipidową',
        'Wirus wykorzystuje aparat komórki gospodarza do produkcji własnych białek',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Wirus zawiera zawsze tylko jeden rodzaj kwasu nukleinowego i może atakować ludzi, zwierzęta oraz rośliny (np. wirus mozaiki tytoniowej), wykorzystując przy namnażaniu aparat komórki gospodarza. Nieprawdziwe jest natomiast stwierdzenie, że każdy wirus ma otoczkę lipidową — to cecha tylko niektórych wirusów.',
      umiejetnosci: ['analiza', 'wiedza'],
    },
    {
      id: 'p-t202-13',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego trudniej jest opracować skuteczny lek zwalczający wirusa wewnątrz organizmu niż lek zwalczający bakterię?',
      opcje: [
        'Ponieważ wirus namnaża się, wykorzystując mechanizmy własnej komórki gospodarza, więc lek niszczący wirusa łatwo uszkadza jednocześnie zaatakowaną komórkę organizmu',
        'Ponieważ wirusy są znacznie większe od bakterii i trudniej je zniszczyć',
        'Ponieważ bakterie nie posiadają żadnych struktur, na które mógłby zadziałać lek',
        'Ponieważ wirusy nie wywołują żadnej reakcji układu odpornościowego',
      ],
      poprawna: 0,
      wyjasnienie: 'Bakteria ma własne, odrębne struktury komórkowe (ścianę komórkową, rybosomy bakteryjne), które można zaatakować lekiem bez szkody dla komórek człowieka. Wirus namnaża się natomiast wewnątrz komórki gospodarza, wykorzystując jej własny aparat — trudno więc zniszczyć wirusa, nie uszkadzając przy okazji samej komórki organizmu.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t202-14',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'matching',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Dopasuj wirusa (lub grupę organizmów, które atakuje) do wywoływanej przez niego choroby lub skutku.',
      dopasowanie: {
        lewa: ['Wirus grypy', 'Wirus wścieklizny', 'Wirus mozaiki tytoniowej', 'Wirus ospy wietrznej'],
        prawa: ['Choroba układu nerwowego u zwierząt i ludzi', 'Plamiste przebarwienia liści roślin', 'Wysypka i swędzące pęcherzyki na skórze', 'Gorączka, kaszel, bóle mięśni'],
        pary: [3, 0, 1, 2],
      },
      wyjasnienie: 'Wirus grypy wywołuje gorączkę, kaszel i bóle mięśni; wirus wścieklizny atakuje układ nerwowy zwierząt i ludzi; wirus mozaiki tytoniowej powoduje plamiste przebarwienia liści roślin; wirus ospy wietrznej wywołuje wysypkę i swędzące pęcherzyki na skórze.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t202-15',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Szczepionka zawiera osłabiony lub unieszkodliwiony fragment wirusa (np. jego białka powierzchniowe). Dlaczego podanie takiej szczepionki chroni przed późniejszym prawdziwym zakażeniem tym wirusem?',
      opcje: [
        'Ponieważ układ odpornościowy "uczy się" rozpoznawać charakterystyczne białka wirusa i przy prawdziwym zakażeniu reaguje znacznie szybciej, zanim wirus zdąży się namnożyć',
        'Ponieważ szczepionka trwale niszczy zdolność wirusa do wnikania do jakiejkolwiek komórki na świecie',
        'Ponieważ szczepionka zawiera antybiotyk, który od razu zabija wirusa po zakażeniu',
        'Ponieważ po szczepieniu komórki organizmu przestają mieć błonę komórkową, do której wirus mógłby się przyłączyć',
      ],
      poprawna: 0,
      wyjasnienie: 'Szczepionka prezentuje układowi odpornościowemu charakterystyczne elementy wirusa (np. białka powierzchniowe) bez wywoływania choroby. Dzięki temu organizm "zapamiętuje" te elementy i przy realnym kontakcie z wirusem reaguje szybciej i skuteczniej, zanim wirus zdąży namnożyć się na dużą skalę.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t202-16',
      dzialId: 'd2',
      tematId: 't202',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Zdaniem wielu biologów wirusy nie są zaliczane do żadnego z klasycznych pięciu królestw organizmów, ponieważ nie mają budowy komórkowej.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — klasyczny podział na pięć królestw (Monera, Protisty, Grzyby, Rośliny, Zwierzęta) obejmuje wyłącznie organizmy o budowie komórkowej. Wirusy, jako bezkomórkowe formy materii, stanowią odrębną kategorię i nie mieszczą się w tym podziale.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
  ]);
})();
