(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t106-01',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jak nazywa się podstawowa jednostka budująca kwasy nukleinowe?',
      opcje: ['Nukleotyd', 'Aminokwas', 'Monosacharyd', 'Kwas tłuszczowy'],
      poprawna: 0,
      wyjasnienie: 'Podstawową jednostką budującą kwasy nukleinowe (DNA i RNA) jest nukleotyd, złożony z cukru pięciowęglowego, reszty fosforanowej i zasady azotowej.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t106-02',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Cząsteczka DNA zbudowana jest z dwóch nici skręconych w kształt podwójnej helisy.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda. DNA zbudowane jest z dwóch nici nukleotydów skręconych wokół wspólnej osi, tworzących charakterystyczny kształt podwójnej helisy.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t106-03',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Która zasada azotowa występuje w RNA, ale nie występuje w DNA?',
      opcje: ['Uracyl', 'Adenina', 'Guanina', 'Cytozyna'],
      poprawna: 0,
      wyjasnienie: 'Uracyl zastępuje w RNA tyminę obecną w DNA. Pozostałe trzy zasady — adenina, guanina i cytozyna — występują w obu kwasach nukleinowych.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t106-04',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Jaki cukier wchodzi w skład nukleotydów budujących cząsteczkę DNA?',
      opcje: ['Deoksyryboza', 'Ryboza', 'Glukoza', 'Fruktoza'],
      poprawna: 0,
      wyjasnienie: 'Nukleotydy budujące DNA zawierają cukier deoksyrybozę. W RNA odpowiednikiem tego cukru jest ryboza.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t106-05',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Znając sekwencję zasad azotowych na jednej nici DNA, można dokładnie odtworzyć sekwencję drugiej nici. Na czym opiera się ta możliwość?',
      opcje: [
        'Na zasadzie komplementarności zasad azotowych: adenina zawsze łączy się z tyminą, a guanina zawsze z cytozyną',
        'Na tym, że obie nici DNA mają identyczną sekwencję zasad',
        'Na tym, że w DNA nie ma żadnych zasad azotowych',
        'Na losowym parowaniu dowolnych zasad azotowych',
      ],
      poprawna: 0,
      wyjasnienie: 'Zasada komplementarności zasad sprawia, że adenina zawsze paruje się z tyminą (A-T), a guanina zawsze z cytozyną (G-C). Dzięki temu sekwencja jednej nici jednoznacznie wyznacza sekwencję drugiej — to fundament wiernej replikacji DNA.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t106-06',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych elementów wchodzą w skład pojedynczego nukleotydu? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Cukier pięciowęglowy', 'Reszta fosforanowa', 'Zasada azotowa', 'Aminokwas', 'Kwas tłuszczowy'],
      poprawna: [0, 1, 2],
      wyjasnienie: 'Nukleotyd składa się z trzech elementów: cukru pięciowęglowego (pentozy), reszty fosforanowej i zasady azotowej. Aminokwasy i kwasy tłuszczowe nie wchodzą w skład nukleotydów.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t106-07',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 3,
      tresc: 'Dopasuj pojęcie do jego opisu.',
      dopasowanie: {
        lewa: ['Nukleotyd', 'Gen', 'Chromosom', 'Zasada azotowa'],
        prawa: [
          'Składnik nukleotydu odpowiadający za komplementarne parowanie nici',
          'Silnie upakowana (skondensowana) cząsteczka DNA połączona z białkami',
          'Podstawowa jednostka budująca kwas nukleinowy (cukier + fosforan + zasada)',
          'Fragment cząsteczki DNA zawierający informację o budowie jednego białka',
        ],
        pary: [2, 3, 1, 0],
      },
      wyjasnienie: 'Nukleotyd to podstawowa jednostka budująca kwas nukleinowy. Gen to fragment DNA z informacją o budowie jednego białka. Chromosom to skondensowana cząsteczka DNA związana z białkami. Zasada azotowa to składnik nukleotydu odpowiadający za komplementarne parowanie zasad między niciami.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t106-08',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdania właściwymi pojęciami.',
      tekstZLuka: 'Kwas nukleinowy zbudowany z dwóch nici tworzących podwójną helisę to {{luka1}}. Kwas nukleinowy zwykle jednoniciowy, uczestniczący w syntezie białek, to {{luka2}}.',
      odpowiedziLuk: { luka1: ['DNA'], luka2: ['RNA'] },
      wyjasnienie: 'DNA to dwuniciowy kwas nukleinowy tworzący podwójną helisę i przechowujący informację genetyczną, a RNA to zwykle jednoniciowy kwas nukleinowy uczestniczący w odczycie tej informacji i syntezie białek.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t106-09',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj poziomy organizacji materiału genetycznego od najprostszego do najbardziej złożonego.',
      elementy: ['Nukleotyd', 'Fragment nici DNA (gen)', 'Chromosom'],
      wyjasnienie: 'Nukleotyd to pojedyncza jednostka budująca DNA. Wiele nukleotydów tworzy fragment nici DNA — gen, zawierający informację o budowie jednego białka. Wiele genów tworzy silnie upakowaną, skondensowaną strukturę — chromosom.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t106-10',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Przed podziałem komórki cząsteczka DNA musi zostać dokładnie skopiowana, aby każda z komórek potomnych otrzymała identyczny materiał genetyczny. Dlaczego zasada komplementarności zasad azotowych jest kluczowa dla poprawnego przebiegu tego procesu?',
      opcje: [
        'Ponieważ pozwala precyzyjnie odtworzyć sekwencję nowej nici na podstawie nici matrycowej, bez błędów w kolejności zasad',
        'Ponieważ całkowicie eliminuje potrzebę rozdzielania nici DNA przed kopiowaniem',
        'Ponieważ sprawia, że obie nici DNA mają dokładnie taką samą sekwencję zasad',
        'Ponieważ pozwala zamienić DNA w RNA bez udziału enzymów',
      ],
      poprawna: 0,
      wyjasnienie: 'Dzięki temu, że adenina zawsze paruje się z tyminą, a guanina z cytozyną, każda z dwóch nici DNA może posłużyć jako matryca (wzorzec) do precyzyjnego odtworzenia nici komplementarnej — to gwarantuje wierność kopiowania informacji genetycznej podczas replikacji.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t106-11',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Które stwierdzenia o DNA są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'U organizmów eukariotycznych znajduje się głównie w jądrze komórkowym',
        'Zawiera informację o budowie białek organizmu',
        'Jest przekazywane potomstwu podczas rozmnażania',
        'Zbudowane jest z aminokwasów połączonych wiązaniami peptydowymi',
      ],
      poprawna: [0, 1, 2],
      wyjasnienie: 'DNA znajduje się głównie w jądrze komórkowym, zawiera informację o budowie białek i jest przekazywane potomstwu. DNA nie jest zbudowane z aminokwasów — to opis budowy białek, a nie kwasów nukleinowych.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t106-12',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż cechę, która jednoznacznie odróżnia RNA od DNA.',
      tabela: {
        tytul: 'Porównanie DNA i RNA',
        kolumny: ['Cecha', 'DNA', 'RNA'],
        wiersze: [
          ['Cukier', 'Deoksyryboza', 'Ryboza'],
          ['Liczba nici', 'Dwie (helisa)', 'Zwykle jedna'],
          ['Zasady azotowe', 'A, T, G, C', 'A, U, G, C'],
          ['Zawiera adeninę', 'Tak', 'Tak'],
        ],
      },
      opcje: ['Zawiera adeninę', 'Rodzaj cukru wchodzącego w skład nukleotydów', 'Obecność reszty fosforanowej', 'Zbudowanie z nukleotydów'],
      poprawna: 1,
      wyjasnienie: 'Zgodnie z tabelą adenina, reszta fosforanowa i budowa z nukleotydów są wspólne dla obu kwasów nukleinowych. Cechą, która je jednoznacznie odróżnia, jest rodzaj cukru: deoksyryboza w DNA a ryboza w RNA (podobnie jak liczba nici i obecność tyminy/uracylu).',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t106-13',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'image',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na schemacie podwójnej nici DNA jedna z par zasad połączonych liniami przerywanymi to G-C. Jaka zasada znajduje się na nici przeciwnej naprzeciwko adeniny (A)?',
      diagramId: 'd-t106-podwojna-helisa',
      opcje: ['Tymina (T)', 'Uracyl (U)', 'Guanina (G)', 'Cytozyna (C)'],
      poprawna: 0,
      wyjasnienie: 'Zgodnie z zasadą komplementarności adenina zawsze łączy się z tyminą (A-T) w cząsteczce DNA. Uracyl występuje wyłącznie w RNA, a nie w DNA.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t106-14',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Naukowcy zbadali fragment jednej nici DNA i stwierdzili, że 30% zasad azotowych to adenina. Jaki procent zasad azotowych w tym samym fragmencie tej nici stanowi tymina, jeśli wiadomo, że w całej cząsteczce DNA liczba adenin równa się liczbie tymin, a liczba guanin — liczbie cytozyn (reguła Chargaffa)?',
      opcje: [
        'Nie da się jednoznacznie określić na podstawie samej jednej nici — reguła Chargaffa dotyczy całej dwuniciowej cząsteczki, a nie proporcji na pojedynczej nici',
        '30%, ponieważ liczba adenin zawsze równa się liczbie tymin na tej samej nici',
        '70%, ponieważ pozostałe zasady muszą być tyminami',
        '15%, ponieważ tymina występuje w połowie mniejszej ilości niż adenina',
      ],
      poprawna: 0,
      wyjasnienie: 'Reguła Chargaffa (ilość A = ilość T i ilość G = ilość C) dotyczy całej dwuniciowej cząsteczki DNA, a nie proporcji zasad w obrębie pojedynczej nici — na jednej nici mogą występować w dowolnych proporcjach. Dopiero licząc obie nici łącznie, liczba adenin zrówna się z liczbą tymin.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t106-15',
      dzialId: 'd1',
      tematId: 't106',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Gen i chromosom to dwa różne pojęcia opisujące to samo zjawisko — pojedynczą cząsteczkę DNA.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz. Gen to fragment cząsteczki DNA zawierający informację o budowie jednego białka, natomiast chromosom to silnie upakowana (skondensowana), znacznie dłuższa cząsteczka DNA połączona z białkami, zawierająca wiele genów.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
  ]);
})();
