(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t201-01',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Nauka zajmująca się klasyfikowaniem i porządkowaniem organizmów żywych w grupy nazywa się:',
      opcje: ['Systematyka', 'Ekologia', 'Fizjologia', 'Anatomia'],
      poprawna: 0,
      wyjasnienie: 'Systematyka (taksonomia) to dział biologii zajmujący się opisywaniem, nazywaniem i klasyfikowaniem organizmów w uporządkowane grupy.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t201-02',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Twórcą dwuczłonowego systemu nazewnictwa gatunków (nazw łacińskich) był Karol Linneusz.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'Karol Linneusz, szwedzki przyrodnik z XVIII wieku, wprowadził zasadę dwuczłonowego nazewnictwa gatunkowego stosowaną do dziś.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t201-03',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Ile członów zawiera łacińska nazwa gatunkowa w systemie Linneusza (np. Homo sapiens)?',
      opcje: ['Jeden', 'Dwa', 'Trzy', 'Cztery'],
      poprawna: 1,
      wyjasnienie: 'Nazwa naukowa gatunku składa się z dwóch członów: nazwy rodzaju (Homo) i epitetu gatunkowego (sapiens).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t201-04',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Podstawową jednostką systematyczną jest {{luka1}}. Nazwa naukowa organizmu składa się z nazwy {{luka2}} oraz epitetu gatunkowego.',
      odpowiedziLuk: { luka1: ['gatunek'], luka2: ['rodzaju', 'rodzaj'] },
      wyjasnienie: 'Podstawową jednostką systematyczną jest gatunek, a nazwa naukowa organizmu zawiera nazwę rodzaju i epitet gatunkowy.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t201-05',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z wymienionych są jednostkami systematycznymi stosowanymi w klasyfikacji organizmów? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Rodzaj', 'Rodzina', 'Tkanka', 'Typ', 'Narząd'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Rodzaj, rodzina i typ to jednostki systematyczne. Tkanka i narząd to poziomy organizacji budowy organizmu, a nie jednostki systematyki.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t201-06',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj jednostkę systematyczną człowieka do właściwego przykładu.',
      dopasowanie: {
        lewa: ['Gatunek', 'Rodzaj', 'Rodzina', 'Rząd'],
        prawa: ['Homo sapiens (człowiek rozumny)', 'Homo (człowiek)', 'Hominidae (człowiekowate)', 'Naczelne (Primates)'],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Homo sapiens to gatunek, Homo to rodzaj, Hominidae to rodzina, a Naczelne (Primates) to rząd, do którego należy człowiek.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t201-07',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj jednostki systematyczne od najmniejszej (najbardziej szczegółowej) do największej (najszerszej).',
      elementy: ['Gatunek', 'Rodzaj', 'Rodzina', 'Rząd', 'Gromada (klasa)', 'Typ', 'Królestwo'],
      wyjasnienie: 'Hierarchia jednostek systematycznych, od najwęższej do najszerszej: gatunek → rodzaj → rodzina → rząd → gromada (klasa) → typ → królestwo.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t201-08',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Ile królestw organizmów wyróżnia się najczęściej w klasycznej klasyfikacji nauczanej w szkole podstawowej?',
      opcje: ['Trzy', 'Cztery', 'Pięć', 'Sześć'],
      poprawna: 2,
      wyjasnienie: 'Klasyczny podział wyróżnia pięć królestw: Monera (bakterie), Protisty, Grzyby, Rośliny i Zwierzęta.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t201-09',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego biolodzy posługują się łacińskimi nazwami gatunkowymi zamiast nazw zwyczajowych (potocznych)?',
      opcje: [
        'Bo łacina jest językiem urzędowym w Polsce',
        'Bo nazwy łacińskie są jednoznaczne i zrozumiałe dla naukowców na całym świecie, niezależnie od ich języka ojczystego',
        'Bo nazwy zwyczajowe są zbyt krótkie',
        'Bo tak nakazuje prawo międzynarodowe dotyczące handlu zwierzętami',
      ],
      poprawna: 1,
      wyjasnienie: 'Nazwy zwyczajowe różnią się między językami i krajami, a nawet regionami tego samego kraju. Jednolita nazwa łacińska pozwala jednoznacznie zidentyfikować gatunek bez względu na język, jakim posługuje się badacz.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t201-10',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dwa organizmy należące do tego samego rodzaju, ale do różnych gatunków, są zazwyczaj do siebie bardziej podobne niż dwa organizmy należące do różnych rodzin.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'System klasyfikacji jest zagnieżdżony — organizmy bliżej siebie w hierarchii (np. w tym samym rodzaju) są zwykle bliżej spokrewnione i bardziej do siebie podobne niż organizmy należące jedynie do tej samej, znacznie szerszej rodziny.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t201-11',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Rodzina Kotowate (Felidae) należy do rzędu Drapieżne (Carnivora), rząd Drapieżne — do gromady Ssaki (Mammalia), a gromada Ssaki — do typu Strunowce (Chordata). Które z poniższych stwierdzeń są na tej podstawie prawdziwe? Zaznacz wszystkie poprawne.',
      opcje: [
        'Wszystkie koty należą do rzędu Drapieżnych',
        'Wszystkie ssaki należą do rodziny Kotowatych',
        'Kotowate są jedną z rodzin należących do rzędu Drapieżnych',
        'Typ Strunowce obejmuje wyłącznie ssaki',
      ],
      poprawna: [0, 2],
      wyjasnienie: 'Kotowate to rodzina należąca do rzędu Drapieżnych, więc wszystkie koty są jednocześnie drapieżnymi. Nie wszystkie ssaki są kotami (rodzina to tylko część rzędu), a typ Strunowce obejmuje oprócz ssaków także ptaki, gady, płazy i ryby.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t201-12',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'diagram',
      poziom: 'trudny',
      punkty: 2,
      diagramId: 'd-t201-hierarchia',
      tresc: 'Na schemacie przedstawiono hierarchię jednostek systematycznych w postaci coraz szerszych poziomów. Który poziom obejmuje największą liczbę organizmów?',
      opcje: ['Gatunek', 'Rodzaj', 'Typ', 'Królestwo'],
      poprawna: 3,
      wyjasnienie: 'Królestwo to najwyższa i najszersza jednostka systematyczna na schemacie — obejmuje najwięcej organizmów, choć mają one najmniej cech wspólnych.',
      umiejetnosci: ['diagram', 'analiza'],
    },
    {
      id: 'p-t201-13',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'System klasyfikacji biologicznej ma charakter hierarchiczny i zagnieżdżony. Co to oznacza w praktyce?',
      opcje: [
        'Każdy gatunek należy jednocześnie do dokładnie jednego rodzaju, jednej rodziny, jednego rzędu itd., aż po jedno królestwo',
        'Gatunek może należeć jednocześnie do kilku różnych królestw',
        'Rodzaj jest jednostką szerszą niż rodzina',
        'Klasyfikacja biologiczna nie ma ustalonej kolejności jednostek systematycznych',
      ],
      poprawna: 0,
      wyjasnienie: 'Zagnieżdżenie oznacza, że każda jednostka niższego rzędu w całości mieści się dokładnie w jednej jednostce wyższego rzędu — gatunek nie może "rozdzielić się" między dwa różne rodzaje czy dwa różne królestwa. Rodzina jest szersza niż rodzaj, nie odwrotnie.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t201-14',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dopasuj organizm do królestwa, do którego jest zaliczany.',
      dopasowanie: {
        lewa: ['Bakteria (np. pałeczka okrężnicy)', 'Grzyb kapeluszowy (np. pieczarka)', 'Sosna zwyczajna', 'Dżdżownica'],
        prawa: ['Zwierzęta', 'Rośliny', 'Grzyby', 'Monera (Bakterie)'],
        pary: [3, 2, 1, 0],
      },
      wyjasnienie: 'Bakteria należy do królestwa Monera, grzyb kapeluszowy — do królestwa Grzybów, sosna — do królestwa Roślin, a dżdżownica — do królestwa Zwierząt.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t201-15',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Uzupełnij zdania dotyczące klasyfikacji organizmów.',
      tekstZLuka:
        'Organizmy zdolne do krzyżowania się i wydawania płodnego potomstwa w warunkach naturalnych należą do tego samego {{luka1}}. Najwyższą, najszerszą jednostką systematyczną w klasycznym podziale jest {{luka2}}.',
      odpowiedziLuk: { luka1: ['gatunku', 'gatunek'], luka2: ['królestwo', 'królestwa'] },
      wyjasnienie: 'Zdolność do krzyżowania się i wydawania płodnego potomstwa jest jednym z kryteriów wyznaczających gatunek. Królestwo to najszersza jednostka systematyczna w klasycznym podziale.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t201-16',
      dzialId: 'd2',
      tematId: 't201',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Klucz do oznaczania organizmów to narzędzie, które na podstawie widocznych cech budowy pozwala ustalić przynależność systematyczną (np. gatunek) danego organizmu.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'Klucze do oznaczania zawierają kolejne pytania (lub pary przeciwstawnych stwierdzeń) o cechy budowy organizmu, które krok po kroku prowadzą do ustalenia jego przynależności systematycznej.',
      umiejetnosci: ['wiedza'],
    },
  ]);
})();
