(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-ryby-k1',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Za pomocą jakiego narządu oddychają ryby?',
      opcje: ['Płuc', 'Skrzel', 'Skóry', 'Tchawek'],
      poprawna: 1,
      wyjasnienie: 'Ryby oddychają za pomocą skrzel — bogato unaczynionych blaszek, przez które tlen rozpuszczony w wodzie przenika do krwi.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ryby-k2',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Temperatura ciała ryb jest stała i nie zależy od temperatury wody.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — ryby są zmiennocieplne (pojkilotermiczne), a ich temperatura ciała zależy od temperatury otaczającej wody.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ryby-03',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jak nazywa się narząd zmysłu ryb, który wykrywa drgania i prądy wody?',
      opcje: ['Linia boczna', 'Pokrywa skrzelowa', 'Płetwa grzbietowa', 'Pęcherz pławny'],
      poprawna: 0,
      wyjasnienie: 'Linia boczna to charakterystyczny dla ryb narząd zmysłu biegnący wzdłuż boków ciała, wykrywający drgania i prądy wody.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ryby-04',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Ciało ryby pokryte jest {{luka1}}, chronionymi warstwą śluzu. U większości ryb zapłodnienie jaj, zwanych {{luka2}}, zachodzi na zewnątrz ciała samicy, w wodzie.',
      odpowiedziLuk: { luka1: ['łuskami', 'łuskami rybimi'], luka2: ['ikrą'] },
      wyjasnienie: 'Ciało ryby pokrywają łuski chronione śluzem, a jaja ryb (ikra) są zapładniane zewnętrznie w wodzie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ryby-05',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych cech są przystosowaniami ryb do życia w wodzie? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Opływowy kształt ciała', 'Płuca jako główny narząd oddechowy', 'Łuski pokryte śluzem', 'Płetwy umożliwiające sterowanie i napęd'],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Opływowy kształt ciała, śluzowate łuski i płetwy zmniejszają opór wody i ułatwiają pływanie. Ryby nie oddychają płucami — ich głównym narządem oddechowym są skrzela.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t206-ryby-06',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj rodzaj płetwy do jej głównej funkcji.',
      dopasowanie: {
        lewa: ['Płetwa ogonowa', 'Płetwy piersiowe', 'Płetwa grzbietowa', 'Płetwy brzuszne'],
        prawa: ['Stabilizacja ciała na linii środkowej grzbietu', 'Sterowanie kierunkiem i hamowanie', 'Główny napęd ryby', 'Utrzymanie równowagi'],
        pary: [2, 1, 0, 3],
      },
      wyjasnienie: 'Płetwa ogonowa napędza rybę, płetwy piersiowe służą do sterowania i hamowania, płetwa grzbietowa stabilizuje ciało, a płetwy brzuszne pomagają utrzymać równowagę.',
      umiejetnosci: ['budowa-funkcja', 'wiedza'],
    },
    {
      id: 'p-t206-ryby-07',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj etapy przepływu wody przez układ oddechowy ryby.',
      elementy: ['Woda wpływa przez pysk', 'Woda przepływa przez jamę gębowo-gardłową', 'Woda opłukuje blaszki skrzelowe (wymiana gazowa)', 'Woda wypływa spod pokrywy skrzelowej'],
      wyjasnienie: 'Woda wpływa do pyska, przepływa przez jamę gębowo-gardłową, opłukuje blaszki skrzelowe, gdzie zachodzi wymiana gazowa, i wypływa spod pokrywy skrzelowej.',
      umiejetnosci: ['schemat', 'wiedza'],
    },
    {
      id: 'p-t206-ryby-08',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'image',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Na schemacie budowy zewnętrznej ryby numerem 4 oznaczono element. Co on przedstawia?',
      diagramId: 'd-t206-ryby-budowa',
      opcje: ['Płetwę grzbietową', 'Linię boczną — narząd wykrywający drgania wody', 'Pokrywę skrzelową', 'Łuski'],
      poprawna: 1,
      wyjasnienie: 'Numer 4 na schemacie wskazuje linię boczną — narząd zmysłu biegnący wzdłuż boków ciała ryby, wykrywający drgania i prądy wody.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-ryby-09',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Wszystkie ryby rozmnażają się przez zapłodnienie wewnętrzne.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — u zdecydowanej większości ryb zapłodnienie jest zewnętrzne: samica składa ikrę, a samiec polewa ją mleczem w wodzie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ryby-10',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego ryby składają zwykle bardzo dużą liczbę jaj (ikry)?',
      opcje: [
        'Ponieważ jaja są bardzo małe i lekkie',
        'Ponieważ opieka rodzicielska jest znikoma lub jej brak, a duża liczba jaj rekompensuje wysoką śmiertelność potomstwa',
        'Ponieważ ryby żyją bardzo krótko',
        'Ponieważ każde jajo rozwija się w inny gatunek ryby',
      ],
      poprawna: 1,
      wyjasnienie: 'Przy znikomej opiece rodzicielskiej wiele jaj i młodych ryb ginie zjedzonych przez drapieżniki — złożenie dużej liczby jaj zwiększa szansę, że część potomstwa przeżyje do dorosłości.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-ryby-11',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które stwierdzenia o zmiennocieplności ryb są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Temperatura ciała ryby zmienia się wraz z temperaturą wody',
        'W zimnej wodzie tempo procesów życiowych ryby zwykle zwalnia',
        'Ryba samodzielnie utrzymuje stałą temperaturę ciała niezależnie od otoczenia',
        'Zmiennocieplność jest cechą typową dla ryb, płazów i gadów',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Ryby są zmiennocieplne — ich temperatura ciała zależy od otoczenia, a w zimnej wodzie procesy życiowe zwalniają. Zmiennocieplność cechuje ryby, płazy i gady (w odróżnieniu od stałocieplnych ptaków i ssaków).',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-ryby-12',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż zwierzę, którego temperatura ciała jest stała, niezależnie od temperatury otoczenia.',
      tabela: {
        tytul: 'Temperatura ciała wybranych zwierząt (wartości orientacyjne)',
        kolumny: ['Zwierzę', 'Temperatura ciała'],
        wiersze: [
          ['Karp (ryba)', 'zależna od wody, ok. 4–24°C'],
          ['Żaba (płaz)', 'zależna od temperatury otoczenia'],
          ['Wróbel (ptak)', 'stała, ok. 40–42°C'],
        ],
      },
      opcje: ['Karp', 'Żaba', 'Wróbel', 'Żadne z powyższych'],
      poprawna: 2,
      wyjasnienie: 'Wróbel, jako ptak, jest zwierzęciem stałocieplnym — utrzymuje stałą, wysoką temperaturę ciała niezależnie od otoczenia. Karp i żaba są zmiennocieplne.',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t206-ryby-13',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'matching',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dopasuj środowisko życia do przykładu gatunku ryby.',
      dopasowanie: {
        lewa: ['Wody słodkie (rzeki, jeziora)', 'Wody morskie', 'Ryba wędrowna (życie w morzu i rzece)'],
        prawa: ['Łosoś', 'Karp', 'Dorsz'],
        pary: [1, 2, 0],
      },
      wyjasnienie: 'Karp żyje w wodach słodkich, dorsz w morzach, a łosoś jest gatunkiem wędrownym — dorasta w morzu, a na tarło wraca do rzek.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-ryby-14',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Ryba pływająca w wodzie o temperaturze 6°C ma znacznie spowolnione tempo trawienia i ruchów w porównaniu z tą samą rybą w wodzie o temperaturze 20°C. Co najlepiej wyjaśnia tę obserwację?',
      opcje: [
        'Ryba jest chora tylko w zimnej wodzie',
        'Jako zwierzę zmiennocieplne, ryba ma temperaturę ciała zbliżoną do temperatury wody, co bezpośrednio wpływa na tempo jej przemiany materii',
        'Zimna woda zawiera mniej tlenu, co jest jedyną przyczyną spowolnienia',
        'Ryby w zimnej wodzie przechodzą przeobrażenie',
      ],
      poprawna: 1,
      wyjasnienie: 'U zwierząt zmiennocieplnych temperatura ciała odpowiada w przybliżeniu temperaturze otoczenia. Niższa temperatura ciała oznacza wolniejszy przebieg reakcji metabolicznych, stąd spowolnienie trawienia i aktywności ryby w zimnej wodzie.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-ryby-15',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'diagram',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Na podstawie schematu przepływu wody przez układ oddechowy ryby: w którym miejscu zachodzi właściwa wymiana gazowa (pobranie tlenu i oddanie dwutlenku węgla)?',
      diagramId: 'd-t206-ryby-oddychanie',
      opcje: ['W jamie gębowo-gardłowej', 'Na blaszkach skrzelowych', 'Pod pokrywą skrzelową, po opuszczeniu ciała ryby', 'W pysku, zanim woda dotrze do skrzel'],
      poprawna: 1,
      wyjasnienie: 'Właściwa wymiana gazowa zachodzi na blaszkach skrzelowych — są one bogato unaczynione, co umożliwia efektywne przenikanie tlenu do krwi i usuwanie dwutlenku węgla.',
      umiejetnosci: ['schemat', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-ryby-16',
      dzialId: 'd2',
      tematId: 't206-ryby',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Które z poniższych zestawień poprawnie łączy cechę budowy ryby z jej funkcją?',
      opcje: [
        'Linia boczna — trawienie pokarmu',
        'Łuski pokryte śluzem — zmniejszenie tarcia o wodę i ochrona skóry',
        'Płetwa ogonowa — wykrywanie drgań wody',
        'Skrzela — utrzymanie równowagi podczas pływania',
      ],
      poprawna: 1,
      wyjasnienie: 'Łuski pokryte śluzem zmniejszają tarcie ciała o wodę i chronią skórę ryby. Linia boczna wykrywa drgania wody, płetwa ogonowa napędza rybę, a skrzela służą do oddychania.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
  ]);
})();
