(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-pierscienice-01',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jaka cecha budowy ciała jest charakterystyczna dla pierścienic?',
      opcje: ['Podział ciała na liczne, podobne segmenty', 'Ciało spłaszczone grzbietowo-brzusznie', 'Muszla okrywająca całe ciało', 'Ciało okryte pancerzem chitynowym'],
      poprawna: 0,
      wyjasnienie: 'Pierścienice mają ciało podzielone na liczne, podobne do siebie segmenty (metameria) — to najważniejsza cecha rozpoznawcza tej grupy.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-pierscienice-02',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Pierścienice mają zamknięty układ krwionośny.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — u pierścienic krew płynie wyłącznie w naczyniach krwionośnych, a nie swobodnie w jamie ciała.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-pierscienice-03',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka:
        'Pogrubiony, jaśniejszy fragment ciała w przedniej części dżdżownicy nazywamy {{luka1}}. Wytwarza on ochronny {{luka2}}, w którym rozwijają się złożone jaja.',
      odpowiedziLuk: { luka1: ['paskiem', 'pasek', 'obrączką', 'clitellum'], luka2: ['kokon', 'kokon jajowy'] },
      wyjasnienie: 'Pasek (obrączka, clitellum) wydziela śluzową otoczkę, z której powstaje kokon chroniący rozwijające się jaja.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-pierscienice-04',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'image',
      poziom: 'latwy',
      punkty: 1,
      diagramId: 'd-t206-pierscienice-budowa',
      tresc: 'Na diagramie budowy dżdżownicy element oznaczony numerem 4 to szczecinki. Do czego służą?',
      opcje: [
        'Do wykrywania światła',
        'Do zakotwiczania fragmentu ciała w podłożu podczas pełzania',
        'Do chwytania i rozdrabniania pokarmu',
        'Do wymiany gazowej',
      ],
      poprawna: 1,
      wyjasnienie: 'Drobne szczecinki na segmentach ciała dżdżownicy zakotwiczają je w podłożu, dzięki czemu kolejne segmenty mogą się przesuwać do przodu podczas ruchu.',
      umiejetnosci: ['diagram', 'wiedza'],
    },
    {
      id: 'p-t206-pierscienice-05',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Czym różni się jama ciała pierścienic (celom) od budowy bezjamowej płazińców?',
      opcje: [
        'Celom jest przestrzenią otoczoną własną błoną, wypełnioną płynem, w której zawieszone są narządy',
        'Celom to twardy pancerz chroniący narządy wewnętrzne',
        'Celom to muszla otaczająca całe ciało',
        'Celom to układ naczyń krwionośnych',
      ],
      poprawna: 0,
      wyjasnienie: 'W odróżnieniu od bezjamowych płazińców, u pierścienic przestrzeń między ścianą ciała a jelitem to prawdziwa jama ciała (celom), pełniąca też funkcję szkieletu hydraulicznego.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-pierscienice-06',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych cech są prawdziwe dla dżdżownicy ziemnej? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Ma szczecinki na segmentach ciała', 'Oddycha całą powierzchnią wilgotnej skóry', 'Ma zewnętrzną muszlę', 'Jest obojnakiem'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Dżdżownica ma szczecinki, oddycha przez skórę i jest obojnakiem (choć zapłodnienie jest krzyżowe). Nie ma muszli — to cecha mięczaków.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-pierscienice-07',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj przedstawiciela pierścienic do opisu jego trybu życia.',
      dopasowanie: {
        lewa: ['Dżdżownica ziemna', 'Pijawka lekarska', 'Nereida (wieloszczet)'],
        prawa: [
          'Zewnętrzny pasożyt lub drapieżnik wód słodkich, bez szczecinek, z przyssawkami na obu końcach ciała',
          'Żyje w wilgotnej glebie, odżywia się szczątkami organicznymi, ma szczecinki na segmentach',
          'Wieloszczet morski, aktywny drapieżnik dna morskiego, z licznymi szczecinkami na wypustkach ciała',
        ],
        pary: [1, 0, 2],
      },
      wyjasnienie: 'Dżdżownica żyje w glebie i odżywia się szczątkami organicznymi, pijawka lekarska jest pasożytem/drapieżnikiem środowisk wodnych bez szczecinek, a nereida to morski wieloszczet-drapieżnik.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-pierscienice-08',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'diagram',
      poziom: 'sredni',
      punkty: 2,
      diagramId: 'd-t206-pierscienice-budowa',
      tresc: 'Na diagramie budowy dżdżownicy element oznaczony numerem 3 to pasek (clitellum). Jaka jest jego funkcja?',
      opcje: [
        'Wytwarzanie kokonu, w którym rozwijają się zapłodnione jaja',
        'Pobieranie pokarmu z gleby',
        'Wymiana gazowa z otoczeniem',
        'Przyczepianie się do podłoża podczas pełzania',
      ],
      poprawna: 0,
      wyjasnienie: 'Komórki paska wydzielają śluzową otoczkę, z której po zapłodnieniu jaj powstaje ochronny kokon składany do gleby.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-pierscienice-09',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Dżdżownice, mimo że są obojnakami, rozmnażają się przez zapłodnienie krzyżowe (potrzebne są dwa osobniki).',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — mimo posiadania obu typów narządów rozrodczych, dżdżownice wymieniają się plemnikami podczas kopulacji; nie dochodzi do samozapłodnienia.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-pierscienice-10',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego zamknięty układ krwionośny pierścienic umożliwia sprawniejszy transport substancji niż w otwartym układzie krwionośnym?',
      opcje: [
        'Bo krew płynie wyłącznie w naczyniach, co pozwala kontrolować kierunek i szybkość jej przepływu do poszczególnych narządów',
        'Bo krew swobodnie wypełnia całą jamę ciała, docierając wszędzie naraz',
        'Bo krew w zamkniętym układzie nie zawiera żadnych składników odżywczych',
        'Bo naczynia krwionośne u pierścienic zastępują układ nerwowy',
      ],
      poprawna: 0,
      wyjasnienie: 'W zamkniętym układzie krwionośnym krew płynie w wyznaczonych naczyniach, co umożliwia szybszy i bardziej kontrolowany transport tlenu i substancji odżywczych do poszczególnych narządów niż w układzie otwartym.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-pierscienice-11',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego dżdżownica ginie, gdy jej skóra wyschnie?',
      opcje: [
        'Bo skóra pełni u niej funkcję narządu oddechowego, a wymiana gazowa wymaga wilgotnej powierzchni',
        'Bo sucha skóra uniemożliwia trawienie pokarmu',
        'Bo woda jest jej jedynym pokarmem',
        'Bo suche powietrze niszczy jej układ nerwowy',
      ],
      poprawna: 0,
      wyjasnienie: 'Dżdżownica nie ma narządów oddechowych — tlen dyfunduje do jej organizmu przez wilgotną skórę. Wyschnięcie skóry uniemożliwia tę wymianę gazową i prowadzi do śmierci.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-pierscienice-12',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj etapy rozmnażania dżdżownicy, zaczynając od kopulacji dwóch osobników.',
      elementy: [
        'Dwa osobniki przylegają do siebie i wymieniają się plemnikami',
        'Pasek (clitellum) wydziela śluzową otoczkę wokół przedniej części ciała',
        'Otoczka zsuwa się z ciała, zbierając po drodze komórki jajowe i plemniki',
        'Z otoczki powstaje kokon złożony do gleby, w którym rozwijają się jaja',
        'Z kokonu wykluwają się małe dżdżownice',
      ],
      wyjasnienie: 'Po wymianie plemników pasek wytwarza śluzową otoczkę, która zsuwając się z ciała zbiera komórki jajowe i plemniki, tworząc kokon, z którego wykluwają się młode dżdżownice.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-pierscienice-13',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Jakie znaczenie mają dżdżownice dla żyzności gleby?',
      opcje: [
        'Zubażają glebę, zjadając korzenie roślin',
        'Spulchniają i napowietrzają glebę oraz przyczyniają się do powstawania próchnicy, przepuszczając przez jelito szczątki organiczne',
        'Zakwaszają glebę, wydzielając trujące substancje',
        'Nie mają żadnego wpływu na właściwości gleby',
      ],
      poprawna: 1,
      wyjasnienie: 'Drążąc korytarze, dżdżownice spulchniają i napowietrzają glebę, a przepuszczając przez przewód pokarmowy szczątki organiczne, przyczyniają się do powstawania próchnicy — dzięki temu gleba staje się żyźniejsza.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-pierscienice-14',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'multiple',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Które z poniższych zwierząt są przedstawicielami pierścienic? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Dżdżownica ziemna', 'Pijawka lekarska', 'Ślimak winniczek', 'Nereida (wieloszczet)'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Dżdżownica, pijawka i nereida to przedstawiciele pierścienic. Ślimak winniczek należy do mięczaków — ma muszlę i nie ma segmentowanego ciała.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-pierscienice-15',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Na czym polega zdolność do regeneracji u dżdżownicy i jakie ma znaczenie?',
      opcje: [
        'Dżdżownica może odtworzyć niewielką liczbę utraconych segmentów ciała, co zwiększa jej szansę na przeżycie po uszkodzeniu',
        'Dżdżownica może odtworzyć całe swoje ciało z jednego segmentu, dzieląc się na dwa identyczne osobniki',
        'Regeneracja u dżdżownicy dotyczy wyłącznie odtwarzania utraconych szczecinek',
        'Dżdżownice nie mają zdolności regeneracji',
      ],
      poprawna: 0,
      wyjasnienie: 'Dżdżownica potrafi odtworzyć niewielką liczbę segmentów utraconych na przednim lub tylnym końcu ciała, co pomaga jej przetrwać uszkodzenia powodowane np. przez drapieżniki.',
      umiejetnosci: ['analiza', 'wiedza'],
    },
    {
      id: 'p-t206-pierscienice-16',
      dzialId: 'd2',
      tematId: 't206-pierscienice',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Gdzie najczęściej żyje dżdżownica ziemna?',
      opcje: ['Na dnie mórz', 'W wilgotnej glebie', 'W jelicie innych zwierząt jako pasożyt', 'Na powierzchni liści roślin'],
      poprawna: 1,
      wyjasnienie: 'Dżdżownica ziemna żyje w wilgotnej glebie, w której drąży korytarze i odżywia się zawartymi w niej szczątkami organicznymi.',
      umiejetnosci: ['wiedza'],
    },
  ]);
})();
