(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-gady-k1',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Czym pokryte jest ciało gadów?',
      opcje: ['Piórami', 'Sierścią', 'Suchymi, rogowymi łuskami', 'Nagą, wilgotną skórą'],
      poprawna: 2,
      wyjasnienie: 'Ciało gadów pokrywają suche, rogowe łuski, które ograniczają parowanie wody z organizmu.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-gady-k2',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Gady oddychają wyłącznie za pomocą płuc.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'Prawda — sucha, rogowa skóra gadów nie uczestniczy w oddychaniu, dlatego jedynym narządem oddechowym gadów są płuca.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-gady-03',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Gdzie gady składają swoje jaja?',
      opcje: ['Zawsze w wodzie', 'Na lądzie', 'Wewnątrz ciała matki aż do wyklucia', 'W gnieździe zbudowanym z piór'],
      poprawna: 1,
      wyjasnienie: 'Gady składają jaja owodniowe na lądzie — twarda lub elastyczna skorupa chroni je przed wysychaniem, więc obecność wody nie jest konieczna.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-gady-04',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Jajo gada, zwane jajem {{luka1}}, jest otoczone skorupą i błonami płodowymi. Zapłodnienie u gadów jest {{luka2}}.',
      odpowiedziLuk: { luka1: ['owodniowym', 'owodniowe'], luka2: ['wewnętrzne'] },
      wyjasnienie: 'Jajo gada to jajo owodniowe, chronione skorupą i błonami płodowymi, a zapłodnienie u gadów jest wewnętrzne.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-gady-05',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych cech są charakterystyczne dla gadów? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Sucha skóra pokryta łuskami', 'Oddychanie płucno-skórne', 'Zmiennocieplność', 'Jaja owodniowe składane na lądzie'],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Gady mają suchą, łuskowatą skórę, są zmiennocieplne i składają na lądzie jaja owodniowe. Oddychanie płucno-skórne to cecha płazów, nie gadów.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t206-gady-06',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj gatunek gada do grupy, do której należy.',
      dopasowanie: {
        lewa: ['Zaskroniec', 'Jaszczurka zwinka', 'Żółw błotny', 'Krokodyl nilowy'],
        prawa: ['Krokodyle', 'Węże', 'Jaszczurki', 'Żółwie'],
        pary: [1, 2, 3, 0],
      },
      wyjasnienie: 'Zaskroniec należy do węży, jaszczurka zwinka do jaszczurek, żółw błotny do żółwi, a krokodyl nilowy do krokodyli.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-gady-07',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj poziom niezależności od wody w rozrodzie — od najbardziej związanego z wodą do najbardziej niezależnego.',
      elementy: ['Ryba — zapłodnienie i rozwój jaj w wodzie', 'Płaz — zapłodnienie i rozwój larwy w wodzie, dorosłe formy na lądzie', 'Gad — zapłodnienie wewnętrzne, jaja owodniowe składane na lądzie'],
      wyjasnienie: 'Ryby są w pełni związane z wodą także w rozrodzie, płazy łączą wodę (rozwój larwalny) i ląd (dorosłość), a gady dzięki jaju owodniowemu rozmnażają się w pełni na lądzie.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-gady-08',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'diagram',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Na schemacie budowy zewnętrznej gada numerem 1 oznaczono łuski rogowe. Jaka jest ich główna funkcja?',
      diagramId: 'd-t206-gady-budowa',
      opcje: ['Umożliwiają oddychanie skórne', 'Ograniczają parowanie wody z organizmu', 'Wytwarzają mleko dla młodych', 'Służą do lotu'],
      poprawna: 1,
      wyjasnienie: 'Suche, rogowe łuski tworzą szczelną powłokę, która skutecznie ogranicza parowanie wody z ciała gada — to kluczowe przystosowanie do życia na lądzie, także w suchych środowiskach.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-gady-09',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Z jaja gada wykluwa się larwa, która przechodzi przeobrażenie, podobnie jak u płazów.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — z jaja gada wykluwa się młody osobnik już podobny do postaci dorosłej. U gadów, w odróżnieniu od płazów, nie występuje stadium larwalne ani przeobrażenie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-gady-10',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego jaszczurki często można zaobserwować wygrzewające się na nasłonecznionych kamieniach?',
      opcje: [
        'Ponieważ potrzebują witaminy D tak jak rośliny',
        'Ponieważ jako zwierzęta zmiennocieplne podnoszą w ten sposób temperaturę ciała, co przyspiesza ich procesy życiowe',
        'Ponieważ światło słoneczne zabija pasożyty na ich skórze',
        'Ponieważ w ten sposób linieją',
      ],
      poprawna: 1,
      wyjasnienie: 'Jako zwierzęta zmiennocieplne, jaszczurki nie wytwarzają własnego ciepła — wygrzewanie się na słońcu podnosi temperaturę ich ciała, co przyspiesza metabolizm i zwiększa aktywność.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-gady-11',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które stwierdzenia porównujące gady i płazy są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Gady mają suchą skórę, a płazy nagą i wilgotną',
        'Gady oddychają wyłącznie płucami, a płazy płucno-skórnie',
        'Jaja gadów muszą być złożone w wodzie, tak jak jaja płazów',
        'Zarówno gady, jak i płazy są zmiennocieplne',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Gady mają suchą skórę i oddychają wyłącznie płucami, płazy — nagą skórę i oddychają płucno-skórnie. Oba typy zwierząt są zmiennocieplne. Jaja gadów, w odróżnieniu od jaj płazów, nie muszą być składane w wodzie — chroni je skorupa.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-gady-12',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż zwierzę, którego jaja są niezależne od obecności zbiornika wodnego.',
      tabela: {
        tytul: 'Rozród wybranych kręgowców',
        kolumny: ['Zwierzę', 'Miejsce złożenia jaj', 'Osłona jaja'],
        wiersze: [
          ['Żaba trawna (płaz)', 'woda', 'galaretowata osłonka, bez skorupy'],
          ['Zaskroniec (gad)', 'ląd, ukryte miejsce', 'elastyczna skorupa'],
          ['Karp (ryba)', 'woda', 'brak skorupy'],
        ],
      },
      opcje: ['Żaba trawna', 'Zaskroniec', 'Karp', 'Żadne z powyższych'],
      poprawna: 1,
      wyjasnienie: 'Jajo zaskrońca chronione jest elastyczną skorupą i błonami płodowymi, dzięki czemu może być złożone na lądzie, niezależnie od obecności wody — w przeciwieństwie do jaj żaby i karpia.',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t206-gady-13',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'image',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na schemacie jaja owodniowego gada wskazano numerem 2 błony płodowe. Jaką funkcję pełnią?',
      diagramId: 'd-t206-gady-jajo',
      opcje: ['Wytwarzają skorupę jaja', 'Otaczają zarodek płynem, zastępując środowisko wodne', 'Magazynują żółtko jako pokarm', 'Umożliwiają oddychanie skórne zarodka'],
      poprawna: 1,
      wyjasnienie: 'Błony płodowe otaczają rozwijający się zarodek płynem, dzięki czemu może się on rozwijać poza wodą — to kluczowe przystosowanie jaja owodniowego do rozrodu na lądzie.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-gady-14',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Naukowcy uważają jajo owodniowe za jedno z kluczowych przystosowań w ewolucji kręgowców lądowych. Co najlepiej uzasadnia to znaczenie?',
      opcje: [
        'Jajo owodniowe jest dużo mniejsze niż jaja płazów, więc samice mogą składać ich więcej',
        'Jajo owodniowe pozwala zarodkowi rozwijać się w środowisku wodnym wewnątrz skorupy, dzięki czemu zwierzę może rozmnażać się z dala od zbiorników wodnych',
        'Jajo owodniowe eliminuje potrzebę zapłodnienia',
        'Jajo owodniowe umożliwia oddychanie skórne zarodka przez całe jego życie',
      ],
      poprawna: 1,
      wyjasnienie: 'Błony płodowe i płyn wewnątrz jaja owodniowego odtwarzają środowisko wodne potrzebne do rozwoju zarodka, a skorupa chroni je przed wysychaniem — to pozwoliło gadom całkowicie uniezależnić rozród od obecności wody w otoczeniu.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-gady-15',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Które z poniższych zestawień poprawnie łączy cechę budowy gada z jej funkcją?',
      opcje: [
        'Sucha skóra z łuskami rogowymi — ograniczenie parowania wody z organizmu',
        'Płuca — wytwarzanie skorupy jaja',
        'Łuski rogowe — dodatkowy narząd oddechowy',
        'Zmiennocieplność — samodzielne utrzymywanie stałej temperatury ciała',
      ],
      poprawna: 0,
      wyjasnienie: 'Sucha, łuskowata skóra ogranicza parowanie wody. Płuca służą do oddychania, a nie do wytwarzania skorupy jaja; łuski nie pełnią funkcji oddechowej; zmiennocieplność oznacza brak zdolności do samodzielnego utrzymywania stałej temperatury ciała.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t206-gady-16',
      dzialId: 'd2',
      tematId: 't206-gady',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dlaczego gady, w odróżnieniu od płazów, mogą na stałe zasiedlać środowiska bardzo suche, np. pustynie?',
      opcje: [
        'Ponieważ gady w ogóle nie potrzebują wody do życia',
        'Ponieważ nieprzepuszczalna, łuskowata skóra ogranicza utratę wody, a jajo owodniowe umożliwia rozród bez zbiornika wodnego',
        'Ponieważ gady są stałocieplne, tak jak ssaki',
        'Ponieważ gady oddychają skórnie, tak jak płazy, ale w suchym powietrzu',
      ],
      poprawna: 1,
      wyjasnienie: 'Dwa niezależne przystosowania — nieprzepuszczalna, łuskowata skóra ograniczająca parowanie oraz jajo owodniowe niewymagające wody do rozwoju zarodka — pozwalają gadom, w odróżnieniu od płazów, żyć i rozmnażać się w bardzo suchych środowiskach.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
  ]);
})();
