(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-ssaki-k1',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jaka cecha jest wspólna dla wszystkich ssaków i nadaje nazwę tej gromadzie?',
      opcje: ['Żyworodność', 'Gruczoły mlekowe', 'Lot', 'Zmiennocieplność'],
      poprawna: 1,
      wyjasnienie: 'Nazwa „ssaki” pochodzi od gruczołów mlekowych — wszystkie ssaki, także jajorodne stekowce, karmią młode mlekiem wytwarzanym przez te gruczoły.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ssaki-k2',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Wszystkie ssaki rodzą żywe młode.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — dziobak i kolczatka (stekowce) są ssakami jajorodnymi i składają jaja, mimo że mają gruczoły mlekowe i karmią młode mlekiem.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ssaki-03',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Czym pokryte jest ciało większości ssaków?',
      opcje: ['Piórami', 'Rogowymi łuskami', 'Sierścią (włosami)', 'Nagą, wilgotną skórą'],
      poprawna: 2,
      wyjasnienie: 'Ciało większości ssaków pokrywa sierść, izolująca ciało od utraty ciepła — ważna cecha dla zwierząt stałocieplnych.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ssaki-04',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Mięsień oddzielający jamę klatki piersiowej od jamy brzusznej i uczestniczący w oddychaniu ssaków to {{luka1}}. Zróżnicowane uzębienie ssaków nazywamy {{luka2}}.',
      odpowiedziLuk: { luka1: ['przepona'], luka2: ['heterodontyzmem', 'heterodontyzm'] },
      wyjasnienie: 'Przepona to mięsień biorący udział w oddychaniu ssaków, a zróżnicowane uzębienie (siekacze, kły, zęby przedtrzonowe i trzonowe) to heterodontyzm.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ssaki-05',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych cech są charakterystyczne dla ssaków? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Gruczoły mlekowe', 'Stałocieplność', 'Zawsze żyworodność', 'Sierść pokrywająca ciało'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Gruczoły mlekowe, stałocieplność i sierść to cechy wspólne wszystkim ssakom. Żyworodność nie dotyczy wszystkich ssaków — stekowce (dziobak, kolczatka) są jajorodne.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t206-ssaki-06',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj grupę ssaków do sposobu, w jaki rozwijają się ich młode.',
      dopasowanie: {
        lewa: ['Łożyskowce', 'Torbacze', 'Stekowce'],
        prawa: ['Rodzą bardzo niedojrzałe młode, które dojrzewają w torbie', 'Zarodek rozwija się w macicy, odżywiany przez łożysko', 'Składają jaja, z których wykluwają się młode'],
        pary: [1, 0, 2],
      },
      wyjasnienie: 'Łożyskowce rodzą w pełni ukształtowane młode odżywiane w macicy przez łożysko, torbacze rodzą bardzo niedojrzałe młode dojrzewające w torbie, a stekowce jako jedyne ssaki składają jaja.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-ssaki-07',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj etapy rozwoju typowego ssaka łożyskowego, poczynając od zapłodnienia.',
      elementy: ['Zapłodnienie wewnętrzne', 'Rozwój zarodka w macicy, odżywianego przez łożysko', 'Narodziny w pełni ukształtowanego młodego', 'Karmienie młodego mlekiem matki'],
      wyjasnienie: 'U ssaków łożyskowych po zapłodnieniu wewnętrznym zarodek rozwija się w macicy matki, odżywiany przez łożysko, następnie rodzi się w pełni ukształtowane młode, które od razu jest karmione mlekiem matki.',
      umiejetnosci: ['schemat', 'wiedza'],
    },
    {
      id: 'p-t206-ssaki-08',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'diagram',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Na schemacie budowy zewnętrznej ssaka numerem 3 oznaczono ustawienie kończyn pod tułowiem. Jaką zaletę daje to zwierzęciu w porównaniu z gadami, u których kończyny są rozstawione po bokach ciała?',
      diagramId: 'd-t206-ssaki-budowa',
      opcje: ['Umożliwia oddychanie skórne', 'Pozwala na sprawniejszy, szybszy chód i bieg', 'Umożliwia lot', 'Pomaga w trawieniu pokarmu'],
      poprawna: 1,
      wyjasnienie: 'Kończyny umieszczone pod tułowiem (zamiast po jego bokach, jak u gadów) pozwalają ssakom poruszać się sprawniej i osiągać większe prędkości podczas biegu.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-ssaki-09',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Wieloryb jest rybą, ponieważ całe życie spędza w wodzie i ma opływowy kształt ciała.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — wieloryb jest ssakiem: oddycha płucami, jest stałocieplny i karmi młode mlekiem. Opływowy kształt ciała to jedynie przystosowanie do życia w wodzie, a nie dowód pokrewieństwa z rybami.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-ssaki-10',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego dziobaka, mimo że składa jaja, klasyfikuje się jako ssaka, a nie gada czy ptaka?',
      opcje: [
        'Ponieważ dziobak jest zmiennocieplny, tak jak gady',
        'Ponieważ dziobak ma sierść, gruczoły mlekowe i karmi wyklute młode mlekiem — cechy definiujące ssaki',
        'Ponieważ jaja dziobaka mają twardą, wapienną skorupę, tak jak jaja ptaków',
        'Ponieważ dziobak nie ma kręgosłupa',
      ],
      poprawna: 1,
      wyjasnienie: 'O przynależności do ssaków decydują cechy takie jak sierść, gruczoły mlekowe i karmienie młodych mlekiem, a nie sposób rozrodu. Dziobak spełnia te warunki, mimo że — jako stekowiec — składa jaja.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-ssaki-11',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które stwierdzenia porównujące ssaki i ptaki są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Oba typy zwierząt są stałocieplne',
        'Ssaki mają sierść, a ptaki pióra',
        'Ssaki karmią młode mlekiem, ptaki tego nie robią',
        'Zarówno ssaki, jak i ptaki mają w pełni czterodzielne serce, oddzielające krew utlenowaną od odtlenowanej',
      ],
      poprawna: [0, 1, 2],
      wyjasnienie: 'Ssaki i ptaki są stałocieplne, ssaki mają sierść (ptaki pióra) i tylko ssaki karmią młode mlekiem. Stwierdzenie o budowie serca wykracza poza materiał tego tematu i nie jest tu oceniane jako element porównania.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-ssaki-12',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż zwierzę, które — mimo że jest ssakiem — rozmnaża się przez składanie jaj.',
      tabela: {
        tytul: 'Sposób rozrodu wybranych ssaków',
        kolumny: ['Zwierzę', 'Sposób rozrodu'],
        wiersze: [
          ['Pies', 'żyworodność (łożyskowiec)'],
          ['Kangur', 'rodzi bardzo niedojrzałe młode, dojrzewające w torbie'],
          ['Dziobak', 'jajorodność (stekowiec)'],
        ],
      },
      opcje: ['Pies', 'Kangur', 'Dziobak', 'Żadne z powyższych'],
      poprawna: 2,
      wyjasnienie: 'Dziobak, jako stekowiec, jest jednym z dwóch gatunków ssaków jajorodnych (obok kolczatki) — mimo że jest ssakiem, rozmnaża się przez składanie jaj, a wyklute młode karmi mlekiem.',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t206-ssaki-13',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'image',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na schemacie sposobów rozrodu ssaków wskazano grupę „torbacze”. Co jest dla niej charakterystyczne?',
      diagramId: 'd-t206-ssaki-rozrod',
      opcje: [
        'Składają jaja, z których wykluwają się młode',
        'Rodzą bardzo niedojrzałe młode, które dojrzewają w torbie lęgowej matki, ssąc mleko',
        'Nie mają gruczołów mlekowych',
        'Zarodek rozwija się w pełni w macicy, odżywiany przez łożysko',
      ],
      poprawna: 1,
      wyjasnienie: 'Torbacze, np. kangur czy koala, rodzą bardzo niedojrzałe młode, które muszą dalej rozwijać się w torbie lęgowej matki, ssąc jej mleko — to pośredni sposób rozrodu między stekowcami a łożyskowcami.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-ssaki-14',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Nietoperz jest jedynym ssakiem zdolnym do czynnego, aktywnego lotu. Które z poniższych stwierdzeń NIE jest prawdziwe w odniesieniu do nietoperza jako ssaka?',
      opcje: [
        'Nietoperz karmi młode mlekiem',
        'Nietoperz jest stałocieplny',
        'Nietoperz ma kości pneumatyczne identyczne jak u ptaków, co jest cechą definiującą ssaki',
        'Nietoperz ma sierść',
      ],
      poprawna: 2,
      wyjasnienie: 'Kości pneumatyczne to przystosowanie charakterystyczne dla ptaków, a nie definiująca cecha ssaków — zdolność nietoperza do lotu wynika z innej budowy szkieletu i błony lotnej rozpiętej między wydłużonymi palcami, a nie z posiadania kości pneumatycznych. Karmienie mlekiem, stałocieplność i sierść to prawdziwe cechy ssaków, w tym nietoperza.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-ssaki-15',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Które z poniższych zestawień poprawnie łączy cechę budowy ssaka z jej funkcją?',
      opcje: [
        'Gruczoły mlekowe — wytwarzanie mleka do karmienia młodych',
        'Przepona — wytwarzanie sierści',
        'Zróżnicowane uzębienie — oddychanie',
        'Sierść — trawienie pokarmu',
      ],
      poprawna: 0,
      wyjasnienie: 'Gruczoły mlekowe wytwarzają mleko do karmienia młodych. Przepona uczestniczy w oddychaniu (nie w wytwarzaniu sierści), zróżnicowane uzębienie służy do pobierania i wstępnej obróbki pokarmu (nie do oddychania), a sierść izoluje ciepło (nie trawi pokarmu).',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t206-ssaki-16',
      dzialId: 'd2',
      tematId: 't206-ssaki',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dlaczego zróżnicowane uzębienie (heterodontyzm) jest korzystne dla ssaków w porównaniu z jednorodnym uzębieniem wielu gadów?',
      opcje: [
        'Ponieważ zwiększa masę czaszki, co poprawia równowagę',
        'Ponieważ różne typy zębów (siekacze, kły, zęby przedtrzonowe i trzonowe) umożliwiają skuteczniejsze odgryzanie, rozrywanie i rozcieranie różnych rodzajów pokarmu',
        'Ponieważ zęby ssaków, w odróżnieniu od zębów gadów, w ogóle się nie zużywają',
        'Ponieważ heterodontyzm zastępuje potrzebę posiadania żołądka',
      ],
      poprawna: 1,
      wyjasnienie: 'Zróżnicowane uzębienie pozwala ssakom skuteczniej przetwarzać zróżnicowany pokarm już na etapie jego pobierania i wstępnej obróbki w jamie gębowej — siekacze odgryzają, kły rozrywają, a zęby przedtrzonowe i trzonowe rozcierają pokarm.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
  ]);
})();
