(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t112-01',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Czym charakteryzuje się samożywność (autotrofizm)?',
      opcje: [
        'Zdolnością do samodzielnego wytwarzania związków organicznych z prostych substancji nieorganicznych',
        'Koniecznością pobierania gotowego pokarmu z otoczenia',
        'Zdolnością do rozkładania martwej materii organicznej',
        'Pasożytniczym trybem życia',
      ],
      poprawna: 0,
      wyjasnienie: 'Organizmy samożywne (autotroficzne) samodzielnie wytwarzają związki organiczne z prostych substancji nieorganicznych, np. w procesie fotosyntezy.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t112-02',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Grzyby są organizmami samożywnymi, tak jak rośliny.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — grzyby są organizmami cudzożywnymi. Nie mają chlorofilu i nie prowadzą fotosyntezy; odżywiają się jako saprotrofy lub pasożyty.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t112-03',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Organizm rozkładający martwą materię organiczną i pobierający z niej składniki odżywcze to:',
      opcje: ['Producent', 'Konsument', 'Destruent (reducent)', 'Pasożyt'],
      poprawna: 2,
      wyjasnienie: 'Destruent (reducent) to organizm cudzożywny rozkładający martwą materię organiczną, np. grzyby i wiele bakterii.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t112-04',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Organizmy samożywne, wytwarzające materię organiczną, nazywamy {{luka1}}, a organizmy cudzożywne odżywiające się innymi organizmami nazywamy {{luka2}}.',
      odpowiedziLuk: { luka1: ['producentami', 'producenci'], luka2: ['konsumentami', 'konsumenci'] },
      wyjasnienie: 'Producenci to organizmy samożywne wprowadzające materię organiczną do łańcucha pokarmowego, a konsumenci to organizmy cudzożywne odżywiające się innymi organizmami.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t112-05',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Chemosynteza, podobnie jak fotosynteza, wymaga obecności światła.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — chemosynteza wykorzystuje energię z reakcji chemicznych utleniania związków nieorganicznych, a nie energię świetlną, dlatego może zachodzić bez dostępu do światła.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t112-06',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Grzyb pleśniowy rozwijający się na resztkach martwych liści odżywia się w sposób nazywany:',
      opcje: ['Fotosyntezą', 'Chemosyntezą', 'Pasożytnictwem', 'Saprotrofizmem'],
      poprawna: 3,
      wyjasnienie: 'Rozkładanie martwej materii organicznej i pobieranie z niej składników odżywczych to saprotrofizm — typowy sposób odżywiania wielu grzybów.',
      umiejetnosci: ['analiza'],
    },
    {
      id: 'p-t112-07',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych są formami cudzożywności? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Roślinożerność', 'Fotosynteza', 'Pasożytnictwo', 'Mięsożerność'],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Roślinożerność, pasożytnictwo i mięsożerność to formy cudzożywności — organizm pobiera gotowy pokarm. Fotosynteza jest procesem samożywnym.',
      umiejetnosci: ['analiza'],
    },
    {
      id: 'p-t112-08',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj organizm do właściwego sposobu odżywiania.',
      dopasowanie: {
        lewa: ['Brzoza', 'Lew', 'Tasiemiec', 'Pleśń na chlebie'],
        prawa: ['Saprotrofizm', 'Pasożytnictwo', 'Fotosynteza (samożywność)', 'Mięsożerność'],
        pary: [2, 3, 1, 0],
      },
      wyjasnienie: 'Brzoza jest samożywna (prowadzi fotosyntezę), lew jest mięsożerny, tasiemiec jest pasożytem, a pleśń odżywia się saprotroficznie, rozkładając martwą materię organiczną.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t112-09',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj etapy obiegu materii organicznej w ekosystemie, zaczynając od jej wytworzenia.',
      elementy: [
        'Producent wytwarza materię organiczną w procesie fotosyntezy',
        'Konsument zjada producenta lub innego konsumenta',
        'Destruent rozkłada szczątki obumarłych organizmów',
        'Związki nieorganiczne wracają do środowiska i są ponownie wykorzystywane przez producentów',
      ],
      wyjasnienie: 'Materia organiczna powstaje u producentów, przechodzi przez kolejnych konsumentów, a po obumarciu organizmów jest rozkładana przez destruentów, dzięki czemu proste związki nieorganiczne wracają do środowiska i obieg się zamyka.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t112-10',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Co najprawdopodobniej stałoby się w ekosystemie, gdyby całkowicie zabrakło destruentów (grzybów i bakterii saprotroficznych)?',
      opcje: [
        'Nic by się nie zmieniło, bo destruenci nie są ważni dla obiegu materii',
        'Martwa materia organiczna gromadziłaby się, a składniki mineralne nie wracałyby do gleby',
        'Producenci zaczęliby rozkładać materię organiczną zamiast destruentów',
        'Wszystkie zwierzęta stałyby się samożywne',
      ],
      poprawna: 1,
      wyjasnienie: 'Destruenci rozkładają martwą materię organiczną, uwalniając z niej proste związki mineralne z powrotem do środowiska. Bez nich martwa materia gromadziłaby się, a producenci mieliby coraz mniej dostępnych składników mineralnych do wzrostu.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t112-11',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Pasożyt zawsze bardzo szybko zabija swojego żywiciela.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — wielu pasożytów „opłaca się” utrzymywać żywiciela przy życiu jak najdłużej, ponieważ od niego zależy ich własne przetrwanie i możliwość dalszego pobierania pokarmu.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t112-12',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które organizmy można zaliczyć do producentów w ekosystemie? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Rośliny lądowe', 'Glony w jeziorze', 'Grzyby kapeluszowe', 'Sinice (bakterie fotosyntetyzujące)'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Rośliny, glony i sinice prowadzą fotosyntezę i wytwarzają materię organiczną, więc są producentami. Grzyby kapeluszowe są cudzożywne (saprotrofy lub symbionty) i nie są producentami.',
      umiejetnosci: ['analiza', 'wiedza'],
    },
    {
      id: 'p-t112-13',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'W głębinach oceanicznych, gdzie nie dociera światło słoneczne, żyją bakterie będące producentami, wykorzystujące energię z utleniania związków siarki. Dlaczego takie bakterie nie mogą odżywiać się w drodze fotosyntezy?',
      opcje: [
        'Ponieważ fotosynteza wymaga obecności światła, którego w głębinach oceanicznych brak',
        'Ponieważ fotosynteza może zachodzić tylko w wodzie słodkiej',
        'Ponieważ bakterie nie mają chlorofilu, więc żadna forma samożywności nie jest u nich możliwa',
        'Ponieważ fotosynteza wymaga bardzo wysokiego ciśnienia, którego w głębinach brakuje',
      ],
      poprawna: 0,
      wyjasnienie: 'Fotosynteza wymaga energii świetlnej, a w głębinach oceanicznych światło słoneczne nie dociera. Dlatego takie bakterie są samożywne dzięki chemosyntezie — wykorzystują energię chemiczną z utleniania związków siarki zamiast światła.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t112-14',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Dopasuj sposób odżywiania do organizmu, który go reprezentuje.',
      dopasowanie: {
        lewa: ['Fotosynteza', 'Chemosynteza', 'Pasożytnictwo', 'Saprotrofizm'],
        prawa: ['Bakteria nitryfikacyjna w glebie', 'Pleśń rozkładająca martwe drewno', 'Sosna zwyczajna', 'Tasiemiec w jelicie żywiciela'],
        pary: [2, 0, 3, 1],
      },
      wyjasnienie: 'Sosna prowadzi fotosyntezę, bakteria nitryfikacyjna odżywia się dzięki chemosyntezie, tasiemiec jest pasożytem, a pleśń rozkładająca martwe drewno jest saprotrofem.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t112-15',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie dotyczące roli destruentów w przyrodzie.',
      tekstZLuka: 'Destruenci rozkładają {{luka1}} materię organiczną do prostych związków {{luka2}}, które mogą zostać ponownie wykorzystane przez producentów.',
      odpowiedziLuk: { luka1: ['martwą'], luka2: ['nieorganicznych', 'mineralnych'] },
      wyjasnienie: 'Destruenci rozkładają martwą materię organiczną do prostych związków nieorganicznych (mineralnych), umożliwiając ich ponowne wykorzystanie przez producentów — zamykając obieg materii w przyrodzie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t112-16',
      dzialId: 'd1',
      tematId: 't112',
      typ: 'ordering',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uporządkuj organizmy w prosty łańcuch pokarmowy, zaczynając od producenta.',
      elementy: ['Trawa (producent)', 'Zając (konsument roślinożerny)', 'Lis (konsument mięsożerny)', 'Bakterie i grzyby rozkładające szczątki lisa (destruenci)'],
      wyjasnienie: 'W łańcuchu pokarmowym materia i energia przepływają od producenta (trawy), przez kolejnych konsumentów (zająca, lisa), aż do destruentów rozkładających szczątki organizmów po ich obumarciu.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
  ]);
})();
