(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-nicienie-01',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jaki kształt ciała mają nicienie?',
      opcje: ['Spłaszczony grzbietowo-brzusznie', 'Wydłużony, nitkowaty, o okrągłym przekroju', 'Segmentowany, pierścieniowaty', 'Skręcony spiralnie w muszli'],
      poprawna: 1,
      wyjasnienie: 'Nicienie mają charakterystyczne, wydłużone, nitkowate (wrzecionowate) ciało o okrągłym przekroju poprzecznym, niesegmentowane.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-nicienie-02',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Nicienie, w odróżnieniu od tasiemców, mają w pełni wykształcony przewód pokarmowy z otworem gębowym i odbytowym.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — nicienie mają przewód pokarmowy przechodzący przez całe ciało, w przeciwieństwie do tasiemców, które nie mają przewodu pokarmowego.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-nicienie-03',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'W jaki sposób człowiek najczęściej zaraża się glistą ludzką?',
      opcje: [
        'Przez spożycie surowego mięsa wieprzowego',
        'Przez połknięcie jaj inwazyjnych z brudnych warzyw, owoców lub rąk',
        'Przez ukąszenie komara',
        'Przez kontakt skóry z wodą morską',
      ],
      poprawna: 1,
      wyjasnienie: 'Do zarażenia glistą ludzką dochodzi po połknięciu jaj inwazyjnych, które trafiają na warzywa, owoce lub ręce z zanieczyszczonej gleby.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-nicienie-04',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych są nicieniami pasożytującymi w organizmie człowieka? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Glista ludzka', 'Owsik ludzki', 'Wypławek biały', 'Włosień kręty'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Glista ludzka, owsik ludzki i włosień kręty to nicienie pasożytujące u człowieka. Wypławek biały należy do płazińców i jest formą wolno żyjącą.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-nicienie-05',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj gatunek nicienia do miejsca, w którym pasożytuje w organizmie człowieka.',
      dopasowanie: {
        lewa: ['Glista ludzka', 'Owsik ludzki', 'Włosień kręty'],
        prawa: ['Mięśnie szkieletowe (stadium larwalne)', 'Jelito cienkie', 'Jelito grube / okolica odbytu'],
        pary: [1, 2, 0],
      },
      wyjasnienie: 'Glista ludzka pasożytuje w jelicie cienkim, owsik ludzki w jelicie grubym (samice składają jaja w okolicy odbytu), a larwy włośnia krętego osiedlają się w mięśniach szkieletowych.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-nicienie-06',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka:
        'Ciało nicieni pokryte jest elastyczną, odporną okrywą zwaną {{luka1}}. Przestrzeń między ścianą ciała a jelitem wypełnia płyn tworzący {{luka2}}, pełniącą funkcję szkieletu hydraulicznego.',
      odpowiedziLuk: { luka1: ['kutikulą', 'kutikula', 'oskórkiem'], luka2: ['jamę ciała pierwotną', 'jama ciała pierwotna'] },
      wyjasnienie: 'Kutikula chroni ciało nicienia, a jama ciała pierwotna wypełniona płynem usztywnia ciało i umożliwia ruch.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-nicienie-07',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj etapy cyklu zarażenia glistą ludzką, zaczynając od jaj w środowisku.',
      elementy: [
        'Jaja inwazyjne znajdują się w glebie lub na brudnych warzywach',
        'Człowiek połyka jaja wraz z pokarmem lub z brudnych rąk',
        'Z jaja wykluwa się larwa, która wędruje z krwią przez wątrobę i płuca',
        'Larwa zostaje odkrztuszona i połknięta ponownie, trafiając do jelita',
        'W jelicie cienkim rozwija się dorosła glista, a jej jaja są wydalane z kałem',
      ],
      wyjasnienie: 'Cykl rozwojowy glisty ludzkiej obejmuje etap wędrówki larwy przez wątrobę i płuca, zanim ponownie trafi ona do jelita cienkiego, gdzie dojrzewa.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-nicienie-08',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'diagram',
      poziom: 'sredni',
      punkty: 2,
      diagramId: 'd-t206-nicienie-budowa',
      tresc: 'Na diagramie budowy glisty ludzkiej element oznaczony numerem 2 to kutikula. Jaką pełni funkcję?',
      opcje: [
        'Umożliwia fotosyntezę',
        'Chroni ciało przed uszkodzeniami i działaniem soków trawiennych żywiciela',
        'Służy do wymiany gazowej przez skrzela',
        'Buduje muszlę ochronną',
      ],
      poprawna: 1,
      wyjasnienie: 'Kutikula to elastyczna, odporna okrywa ciała nicieni, chroniąca je m.in. przed enzymami trawiennymi żywiciela, u którego pasożytują.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-nicienie-09',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'image',
      poziom: 'latwy',
      punkty: 1,
      diagramId: 'd-t206-nicienie-cykl',
      tresc: 'Zgodnie z przedstawionym cyklem zarażenia glistą ludzką, co następuje bezpośrednio po połknięciu jaj przez człowieka?',
      opcje: [
        'Dorosłe glisty od razu pojawiają się w jelicie cienkim',
        'Larwy wędrują przez jelito, wątrobę i płuca',
        'Jaja są od razu wydalane z kałem',
        'Larwy przenikają przez skórę',
      ],
      poprawna: 1,
      wyjasnienie: 'Po połknięciu jaj wykluwają się z nich larwy, które migrują przez ścianę jelita, wątrobę i płuca, zanim trafią ponownie do jelita cienkiego.',
      umiejetnosci: ['diagram', 'analiza'],
    },
    {
      id: 'p-t206-nicienie-10',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego odporna kutikula jest szczególnie ważna dla nicieni pasożytujących w jelicie żywiciela?',
      opcje: [
        'Umożliwia im fotosyntezę w ciemnym wnętrzu jelita',
        'Chroni je przed strawieniem przez enzymy trawienne żywiciela',
        'Pozwala im pływać szybciej w wodzie',
        'Zwiększa ich masę ciała',
      ],
      poprawna: 1,
      wyjasnienie: 'Nicienie pasożytujące w jelicie są otoczone sokami trawiennymi żywiciela — odporna kutikula chroni je przed strawieniem.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-nicienie-11',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego zarażenie owsikiem ludzkim powoduje charakterystyczne swędzenie okolicy odbytu w nocy?',
      opcje: [
        'Bo owsiki żywią się skórą w tej okolicy',
        'Bo samice owsika wychodzą w nocy przez odbyt i składają tam jaja, co podrażnia skórę',
        'Bo larwy owsika migrują wtedy przez płuca',
        'Bo owsiki wydzielają wtedy jad',
      ],
      poprawna: 1,
      wyjasnienie: 'Samice owsika w nocy wydostają się przez odbyt na skórę okolicy odbytu, aby złożyć tam jaja — to podrażnienie wywołuje silne swędzenie.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-nicienie-12',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Larwy glisty ludzkiej w trakcie rozwoju wędrują przez wątrobę i płuca człowieka.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — po wykluciu się z jaja larwy glisty migrują z krwią przez wątrobę i płuca, zanim ponownie trafią do jelita cienkiego.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-nicienie-13',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Czym różni się droga rozwoju owsika ludzkiego od drogi rozwoju glisty ludzkiej w organizmie człowieka?',
      opcje: [
        'Owsik, w przeciwieństwie do glisty, nie migruje przez wątrobę i płuca — rozwija się bezpośrednio w jelicie grubym',
        'Owsik migruje przez płuca, a glista rozwija się wyłącznie w jelicie grubym',
        'Obydwa gatunki rozwijają się wyłącznie w mięśniach szkieletowych',
        'Owsik, w przeciwieństwie do glisty, potrzebuje żywiciela pośredniego',
      ],
      poprawna: 0,
      wyjasnienie: 'W odróżnieniu od glisty ludzkiej, której larwy migrują przez wątrobę i płuca, larwy owsika rozwijają się bezpośrednio w jelicie, bez etapu migracji przez inne narządy.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-nicienie-14',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które działania są skuteczną profilaktyką przeciwko zarażeniu nicieniami pasożytniczymi u człowieka? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Dokładne mycie warzyw i owoców przed spożyciem',
        'Mycie rąk przed jedzeniem, zwłaszcza po kontakcie z ziemią',
        'Spożywanie surowego mięsa wieprzowego',
        'Odpowiednia obróbka termiczna (gotowanie, pieczenie) mięsa',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Mycie warzyw, owoców i rąk ogranicza połykanie jaj z gleby, a gotowanie mięsa niszczy larwy pasożytów (np. włośnia). Spożywanie surowego mięsa zwiększa ryzyko zarażenia, nie jest profilaktyką.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-nicienie-15',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Jaką funkcję pełni u nicieni jama ciała pierwotna, wypełniona płynem pod ciśnieniem?',
      opcje: [
        'Umożliwia trawienie pokarmu',
        'Działa jak szkielet hydrauliczny, nadając ciału sztywność i umożliwiając ruch mimo braku twardego szkieletu',
        'Służy do wytwarzania jaj',
        'Pełni funkcję układu krwionośnego, transportując tlen',
      ],
      poprawna: 1,
      wyjasnienie: 'Płyn wypełniający jamę ciała pierwotną jest pod ciśnieniem i działa jak hydrauliczny szkielet — usztywnia ciało nicienia i pozwala mięśniom skutecznie się kurczyć podczas ruchu.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t206-nicienie-16',
      dzialId: 'd2',
      tematId: 't206-nicienie',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Mątwik ziemniaczany jest przykładem nicienia pasożytującego na:',
      opcje: ['Człowieku', 'Świni', 'Roślinach (np. ziemniakach)', 'Rybach'],
      poprawna: 2,
      wyjasnienie: 'Mątwik ziemniaczany to nicień pasożytujący na korzeniach roślin, m.in. ziemniaka, powodując straty w uprawach.',
      umiejetnosci: ['wiedza'],
    },
  ]);
})();
