(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t107-01',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Które stwierdzenie dotyczące komórki prokariotycznej jest prawdziwe?',
      opcje: [
        'Ma jądro komórkowe otoczone otoczką jądrową',
        'Jej materiał genetyczny (DNA) nie jest otoczony błoną jądrową',
        'Nie posiada błony komórkowej',
        'Jest zawsze większa od komórki eukariotycznej',
      ],
      poprawna: 1,
      wyjasnienie: 'Cechą charakterystyczną komórki prokariotycznej jest brak jądra otoczonego błoną — DNA znajduje się swobodnie w cytoplazmie jako nukleoid.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t107-02',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Do jakiej grupy organizmów należą wyłącznie komórki o budowie prokariotycznej?',
      opcje: ['Rośliny i zwierzęta', 'Grzyby i protisty', 'Bakterie i archeony (archebakterie)', 'Wyłącznie wirusy'],
      poprawna: 2,
      wyjasnienie: 'Budowę prokariotyczną mają tylko bakterie i archeony. Protisty, grzyby, rośliny i zwierzęta zbudowane są z komórek eukariotycznych, a wirusy w ogóle nie mają budowy komórkowej.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t107-03',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Komórka eukariotyczna różni się od prokariotycznej przede wszystkim tym, że...',
      opcje: [
        'ma większe rozmiary i liczne organelle otoczone błonami, w tym jądro komórkowe',
        'nie zawiera DNA',
        'nie posiada rybosomów',
        'nie posiada cytoplazmy',
      ],
      poprawna: 0,
      wyjasnienie: 'Kluczową różnicą jest obecność jądra komórkowego i innych organelli błonowych oraz zwykle większe rozmiary komórki eukariotycznej. DNA, rybosomy i cytoplazma występują w obu typach komórek.',
      umiejetnosci: ['analiza'],
    },
    {
      id: 'p-t107-04',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc:
        'Mitochondria komórek eukariotycznych mają własne, koliste DNA i rybosomy przypominające te bakteryjne, a także dzielą się niezależnie od reszty komórki. Które wyjaśnienie pochodzenia mitochondriów jest zgodne z tymi obserwacjami (teoria endosymbiozy)?',
      opcje: [
        'Mitochondria powstały z odczepionego fragmentu jądra komórkowego',
        'Mitochondria są pozostałością po komórce prokariotycznej, która w przeszłości została wchłonięta przez większą komórkę i zaczęła w niej żyć w symbiozie',
        'Mitochondria to fragmenty ściany komórkowej, które przeniknęły do wnętrza komórki',
        'Mitochondria powstają wyłącznie w wyniku fotosyntezy',
      ],
      poprawna: 1,
      wyjasnienie:
        'Teoria endosymbiozy zakłada, że mitochondria (i chloroplasty) wywodzą się od dawnych prokariotycznych organizmów, które zostały wchłonięte przez inną komórkę i z czasem stały się jej trwałym, współzależnym elementem — stąd ich własne, bakteryjnopodobne DNA i rybosomy.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t107-05',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Każda komórka, zarówno prokariotyczna, jak i eukariotyczna, posiada błonę komórkową.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'Błona komórkowa jest wspólną cechą wszystkich komórek — oddziela ich wnętrze od środowiska zewnętrznego i kontroluje transport substancji.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t107-06',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Bakterie nie posiadają materiału genetycznego (DNA), dlatego nazywamy je komórkami prokariotycznymi.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — bakterie mają DNA, tylko nie jest ono otoczone błoną jądrową. Nazwa "prokariotyczna" odnosi się do braku prawdziwego (otoczonego błoną) jądra, a nie do braku DNA.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t107-07',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które struktury występują zarówno w komórce prokariotycznej, jak i eukariotycznej? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Błona komórkowa', 'Jądro komórkowe otoczone otoczką jądrową', 'Cytoplazma', 'Rybosomy'],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Błona komórkowa, cytoplazma i rybosomy są wspólne dla obu typów komórek. Jądro otoczone błoną występuje wyłącznie w komórce eukariotycznej.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t107-08',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'multiple',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Które z poniższych cech są charakterystyczne wyłącznie dla komórki eukariotycznej? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Obecność jądra komórkowego otoczonego otoczką jądrową',
        'Obecność materiału genetycznego (DNA)',
        'Obecność organelli błonowych, np. aparatu Golgiego i siateczki śródplazmatycznej',
        'Obecność rybosomów',
      ],
      poprawna: [0, 2],
      wyjasnienie: 'DNA i rybosomy występują też w komórkach prokariotycznych, więc nie są cechą wyłączną eukariontów. Jądro otoczone błoną oraz organelle błonowe to cechy charakterystyczne tylko dla komórki eukariotycznej.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t107-09',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj strukturę komórkową do jej opisu.',
      dopasowanie: {
        lewa: ['Nukleoid', 'Otoczka jądrowa', 'Ściana komórkowa', 'Cytoplazma'],
        prawa: [
          'Podwójna błona otaczająca jądro komórkowe',
          'Obszar cytoplazmy z kolistym DNA, nieotoczony błoną',
          'Sztywna warstwa ochronna na zewnątrz błony komórkowej',
          'Półpłynne środowisko wewnątrz komórki',
        ],
        pary: [1, 0, 2, 3],
      },
      wyjasnienie: 'Nukleoid to obszar z DNA bez otoczki, otoczka jądrowa otacza jądro, ściana komórkowa chroni komórkę od zewnątrz, a cytoplazma to wnętrze komórki.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t107-10',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'matching',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dopasuj cechę komórki do typu, dla którego jest charakterystyczna.',
      dopasowanie: {
        lewa: ['DNA jako nukleoid w cytoplazmie', 'DNA w jądrze otoczonym błoną', 'Zwykle 1–10 µm', 'Zwykle 10–100 µm'],
        prawa: ['Komórka eukariotyczna', 'Komórka prokariotyczna'],
        pary: [1, 0, 1, 0],
      },
      wyjasnienie: 'Komórka prokariotyczna: DNA jako nukleoid, mniejsze rozmiary (1–10 µm). Komórka eukariotyczna: DNA w jądrze otoczonym błoną, większe rozmiary (10–100 µm).',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t107-11',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka:
        'Komórka, która nie posiada jądra otoczonego błoną, nazywana jest komórką {{luka1}}. Jej materiał genetyczny znajduje się w obszarze cytoplazmy zwanym {{luka2}}.',
      odpowiedziLuk: { luka1: ['prokariotyczną'], luka2: ['nukleoidem', 'nukleoid'] },
      wyjasnienie: 'Komórka prokariotyczna nie ma jądra otoczonego błoną — jej DNA znajduje się w nukleoidzie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t107-12',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'gapfill',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka:
        'Jądro komórki eukariotycznej otoczone jest podwójną błoną zwaną {{luka1}}. Budowę eukariotyczną mają komórki roślin, zwierząt, grzybów oraz {{luka2}}.',
      odpowiedziLuk: { luka1: ['otoczką jądrową', 'otoczka jądrowa'], luka2: ['protistów', 'protisty'] },
      wyjasnienie: 'Otoczka jądrowa oddziela jądro od cytoplazmy. Do organizmów eukariotycznych zaliczamy rośliny, zwierzęta, grzyby i protisty.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t107-13',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj poniższe struktury od najbardziej "zewnętrznej" do najbardziej "wewnętrznej" w typowej komórce bakteryjnej posiadającej ścianę komórkową.',
      elementy: ['Ściana komórkowa', 'Błona komórkowa', 'Cytoplazma', 'Nukleoid (DNA)'],
      wyjasnienie:
        'W komórce bakteryjnej ściana komórkowa znajduje się najbardziej na zewnątrz, dalej błona komórkowa, następnie cytoplazma, a w jej wnętrzu — obszar nukleoidu z DNA.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t107-14',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'image',
      diagramId: 'd-t107-prokariota-eukariota',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Na schemacie porównującym komórki, który numer oznacza błonę komórkową w komórce eukariotycznej?',
      opcje: ['Numer 2', 'Numer 4', 'Numer 6', 'Numer 8'],
      poprawna: 2,
      wyjasnienie: 'Numer 6 wskazuje błonę komórkową otaczającą komórkę eukariotyczną (prawa strona schematu). Numer 2 to błona komórkowa po stronie komórki prokariotycznej.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t107-15',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'image',
      diagramId: 'd-t107-prokariota-eukariota',
      poziom: 'konkursowy',
      punkty: 2,
      tresc:
        'Na schemacie strukturę oznaczoną numerem 4 narysowano z przerywanym konturem, w odróżnieniu od struktury oznaczonej numerem 7, narysowanej konturem ciągłym (podwójnym). Co to rozróżnienie oznacza biologicznie?',
      opcje: [
        'Struktura 4 (nukleoid) nie jest otoczona błoną, a struktura 7 (jądro komórkowe) jest otoczona otoczką jądrową',
        'Struktura 4 jest większa niż struktura 7',
        'Struktura 4 zawiera więcej DNA niż struktura 7',
        'To rozróżnienie nie ma żadnego znaczenia biologicznego, to tylko styl rysunku',
      ],
      poprawna: 0,
      wyjasnienie:
        'Przerywany kontur nukleoidu (4) symbolizuje brak otoczki błonowej wokół DNA komórki prokariotycznej, a ciągły, podwójny kontur jądra (7) — obecność otoczki jądrowej w komórce eukariotycznej. To właśnie ta różnica jest kluczowym kryterium podziału komórek.',
      umiejetnosci: ['diagram', 'przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t107-16',
      dzialId: 'd1',
      tematId: 't107',
      typ: 'table',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż zdanie prawdziwe.',
      tabela: {
        tytul: 'Porównanie wybranych cech komórki prokariotycznej i eukariotycznej',
        kolumny: ['Cecha', 'Komórka prokariotyczna', 'Komórka eukariotyczna'],
        wiersze: [
          ['Jądro otoczone błoną', 'Brak', 'Obecne'],
          ['Typowa wielkość', '1–10 µm', '10–100 µm'],
          ['Organelle błonowe (np. Golgiego)', 'Brak', 'Liczne'],
          ['Rybosomy', 'Obecne', 'Obecne'],
        ],
      },
      opcje: [
        'Rybosomy występują tylko w komórce eukariotycznej',
        'Komórka prokariotyczna jest zwykle większa od eukariotycznej',
        'Obie komórki posiadają rybosomy, ale tylko eukariotyczna ma jądro otoczone błoną',
        'Żadna z komórek nie posiada organelli błonowych',
      ],
      poprawna: 2,
      wyjasnienie: 'Z tabeli wynika, że rybosomy występują w obu typach komórek, natomiast jądro otoczone błoną i liczne organelle błonowe są charakterystyczne wyłącznie dla komórki eukariotycznej.',
      umiejetnosci: ['tabela', 'analiza'],
    },
  ]);
})();
