(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-ptaki-k1',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Czym pokryte jest ciało ptaków?',
      opcje: ['Sierścią', 'Piórami', 'Nagą skórą', 'Rogowymi łuskami na całym ciele'],
      poprawna: 1,
      wyjasnienie: 'Ciało ptaków pokrywają pióra — konturowe (kształt ciała, powierzchnia nośna) i puchowe (izolacja cieplna). Łuski rogowe u ptaków występują tylko na nogach.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ptaki-k2',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Ptaki są zwierzętami stałocieplnymi.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'Prawda — ptaki samodzielnie wytwarzają ciepło i utrzymują stałą, wysoką temperaturę ciała niezależnie od temperatury otoczenia.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ptaki-03',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jaki wyrostek na mostku ptaka jest miejscem przyczepu mięśni piersiowych poruszających skrzydłami?',
      opcje: ['Kil (grzebień mostka)', 'Worek powietrzny', 'Błona bębenkowa', 'Kość pneumatyczna'],
      poprawna: 0,
      wyjasnienie: 'Kil, czyli grzebień mostka, to miejsce przyczepu silnych mięśni piersiowych, które poruszają skrzydłami podczas lotu.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ptaki-04',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Kości ptaków są {{luka1}} — mają cienkie ścianki i zawierają komory z powietrzem. Jaja ptaków mają twardą, {{luka2}} skorupę.',
      odpowiedziLuk: { luka1: ['pneumatyczne'], luka2: ['wapienną'] },
      wyjasnienie: 'Kości pneumatyczne zmniejszają masę szkieletu ptaka, a jaja ptaków mają twardą, wapienną skorupę.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ptaki-05',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych cech są przystosowaniami ptaków do lotu? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Kości pneumatyczne', 'Kil (grzebień mostka)', 'Worki powietrzne połączone z płucami', 'Zmiennocieplność'],
      poprawna: [0, 1, 2],
      wyjasnienie: 'Kości pneumatyczne zmniejszają masę ciała, kil daje oparcie mięśniom skrzydeł, a worki powietrzne umożliwiają wydajną wymianę gazową. Zmiennocieplność nie jest cechą ptaków — są one stałocieplne.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t206-ptaki-06',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj cechę budowy ptaka do jej głównej funkcji.',
      dopasowanie: {
        lewa: ['Pióra puchowe', 'Pióra konturowe skrzydeł', 'Dziób rogowy bez zębów', 'Nogi z łuskami rogowymi'],
        prawa: ['Zmniejszenie masy głowy', 'Izolacja cieplna ciała', 'Powierzchnia nośna do lotu', 'Cecha wspólna z gadami, ochrona nóg'],
        pary: [1, 2, 0, 3],
      },
      wyjasnienie: 'Pióra puchowe izolują ciepło, pióra konturowe skrzydeł tworzą powierzchnię nośną, dziób bez zębów zmniejsza masę głowy, a łuski na nogach są cechą odziedziczoną po przodkach wspólnych z gadami.',
      umiejetnosci: ['budowa-funkcja', 'wiedza'],
    },
    {
      id: 'p-t206-ptaki-07',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj etapy rozrodu ptaka, poczynając od zapłodnienia.',
      elementy: ['Zapłodnienie wewnętrzne', 'Złożenie jaja z twardą skorupą', 'Wysiadywanie jaja przez rodzica', 'Wyklucie się pisklęcia'],
      wyjasnienie: 'Rozród ptaka przebiega w kolejności: zapłodnienie wewnętrzne, złożenie jaja z twardą skorupą, wysiadywanie jaja przez rodzica i wyklucie się pisklęcia.',
      umiejetnosci: ['schemat', 'wiedza'],
    },
    {
      id: 'p-t206-ptaki-08',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'diagram',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Na schemacie budowy zewnętrznej ptaka numerem 4 oznaczono nogi. Jaka cecha budowy nóg wskazuje na pokrewieństwo ptaków z gadami?',
      diagramId: 'd-t206-ptaki-budowa',
      opcje: ['Obecność piór puchowych', 'Pokrycie łuskami rogowymi', 'Obecność worków powietrznych', 'Kil na mostku'],
      poprawna: 1,
      wyjasnienie: 'Nogi ptaków, w odróżnieniu od reszty ciała, pokryte są rogowymi łuskami — taką samą strukturą, jaka pokrywa całe ciało gadów. To ślad wspólnego pochodzenia obu grup.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-ptaki-09',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Wszystkie ptaki potrafią latać.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — niektóre ptaki, np. struś i pingwin, mimo posiadania piór i skrzydeł, nie potrafią latać (struś biega, pingwin pływa).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-ptaki-10',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego wysoka intensywność przemiany materii jest ptakom szczególnie potrzebna?',
      opcje: [
        'Ponieważ ptaki nie mają płuc',
        'Ponieważ lot wymaga dużych i szybko dostępnych nakładów energii, a stała, wysoka temperatura ciała pozwala mięśniom pracować wydajnie',
        'Ponieważ ptaki żyją bardzo krótko',
        'Ponieważ ptaki nie mają serca',
      ],
      poprawna: 1,
      wyjasnienie: 'Aktywny lot to bardzo energochłonny wysiłek. Wysokie tempo przemiany materii oraz stała, wysoka temperatura ciała pozwalają mięśniom ptaka pracować szybko i wydajnie przez cały czas lotu.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-ptaki-11',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które stwierdzenia o worku powietrznych i oddychaniu ptaków są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Worki powietrzne są połączone z płucami ptaka',
        'Dzięki workom powietrznym wymiana gazowa zachodzi zarówno podczas wdechu, jak i wydechu',
        'Worki powietrzne pełnią funkcję gruczołów mlekowych',
        'Taki układ oddechowy dostarcza więcej tlenu niż płuca płazów czy gadów',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Worki powietrzne, połączone z płucami, umożliwiają przepływ powietrza przez płuca podczas wdechu i wydechu (tzw. podwójne oddychanie), co dostarcza więcej tlenu niż u innych kręgowców lądowych. Nie mają nic wspólnego z gruczołami mlekowymi — te występują u ssaków.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-ptaki-12',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż zwierzę o najwyższej, stałej temperaturze ciała.',
      tabela: {
        tytul: 'Orientacyjna temperatura ciała wybranych zwierząt',
        kolumny: ['Zwierzę', 'Temperatura ciała'],
        wiersze: [
          ['Zaskroniec (gad)', 'zależna od otoczenia, ok. 20–30°C'],
          ['Wróbel (ptak)', 'stała, ok. 40–42°C'],
          ['Pies (ssak)', 'stała, ok. 38–39°C'],
        ],
      },
      opcje: ['Zaskroniec', 'Wróbel', 'Pies', 'Wszystkie mają taką samą temperaturę'],
      poprawna: 1,
      wyjasnienie: 'Wróbel, jako ptak, ma najwyższą i przy tym stałą temperaturę ciała spośród wymienionych zwierząt — wynika to z bardzo wysokiej intensywności przemiany materii, potrzebnej m.in. do lotu.',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t206-ptaki-13',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'chart',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Wykres przedstawia przybliżoną liczbę uderzeń serca na minutę u wybranych zwierząt w spoczynku. Które zwierzę ma najwyższe tętno spoczynkowe?',
      wykres: {
        typ: 'slupkowy',
        tytul: 'Tętno spoczynkowe wybranych zwierząt',
        jednostka: 'uderzenia/min',
        dane: [
          { etykieta: 'Żółw', wartosc: 20 },
          { etykieta: 'Pies', wartosc: 90 },
          { etykieta: 'Wróbel', wartosc: 400 },
        ],
      },
      opcje: ['Żółw', 'Pies', 'Wróbel', 'Wszystkie mają podobne tętno'],
      poprawna: 2,
      wyjasnienie: 'Wróbel ma zdecydowanie najwyższe tętno spoczynkowe spośród przedstawionych zwierząt — to konsekwencja bardzo wysokiej intensywności przemiany materii typowej dla małych ptaków stałocieplnych.',
      umiejetnosci: ['wykres', 'analiza'],
    },
    {
      id: 'p-t206-ptaki-14',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Struś ma pióra i dobrze rozwinięte skrzydła, ale nie potrafi latać. Co to sugeruje na temat budowy jego szkieletu w porównaniu z ptakami latającymi?',
      opcje: [
        'Struś prawdopodobnie ma mostek bez kila lub bardzo słabo rozwinięty kil, więc brakuje mu oparcia dla silnych mięśni piersiowych potrzebnych do lotu',
        'Struś nie ma piór lotnych, dlatego nie lata',
        'Struś jest zmiennocieplny, więc nie ma energii do lotu',
        'Struś nie ma worków powietrznych, więc się dusi podczas próby lotu',
      ],
      poprawna: 0,
      wyjasnienie: 'U strusia mostek nie ma dobrze rozwiniętego kila, co oznacza brak odpowiedniego przyczepu dla silnych mięśni piersiowych — bez nich, mimo posiadania piór i skrzydeł, aktywny lot nie jest możliwy.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-ptaki-15',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'diagram',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Na schemacie przystosowań ptaka do lotu wskazano cztery cechy. Która z nich dotyczy bezpośrednio wydajności układu oddechowego, a nie samej budowy szkieletu lub mięśni?',
      diagramId: 'd-t206-ptaki-lot',
      opcje: ['Kości pneumatyczne', 'Mostek z grzebieniem (kilem)', 'Worki powietrzne', 'Wysoka intensywność przemiany materii dotyczy tylko trawienia'],
      poprawna: 2,
      wyjasnienie: 'Worki powietrzne, połączone z płucami, odpowiadają bezpośrednio za wydajność układu oddechowego (podwójne oddychanie). Kości pneumatyczne i kil dotyczą budowy szkieletu i mięśni, a intensywność przemiany materii to cecha metaboliczna całego organizmu, nie tylko trawienia.',
      umiejetnosci: ['schemat', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-ptaki-16',
      dzialId: 'd2',
      tematId: 't206-ptaki',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Które z poniższych zestawień poprawnie łączy cechę budowy ptaka z jej funkcją?',
      opcje: [
        'Kości pneumatyczne — zmniejszenie masy szkieletu',
        'Pióra puchowe — powierzchnia nośna do lotu',
        'Dziób — trawienie pokarmu w żołądku',
        'Łuski na nogach — izolacja cieplna',
      ],
      poprawna: 0,
      wyjasnienie: 'Kości pneumatyczne, dzięki komorom powietrznym wewnątrz, zmniejszają masę szkieletu ptaka. Powierzchnię nośną tworzą pióra konturowe (nie puchowe), dziób służy do pobierania pokarmu (nie trawienia), a łuski na nogach chronią, nie izolują cieplnie tak jak pióra.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
  ]);
})();
