(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-tkanki-k1',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Ile podstawowych typów tkanek zwierzęcych wyróżnia się u człowieka?',
      opcje: ['Dwa', 'Trzy', 'Cztery', 'Pięć'],
      poprawna: 2,
      wyjasnienie: 'U człowieka i innych zwierząt wyróżnia się cztery podstawowe typy tkanek: nabłonkową, łączną, mięśniową i nerwową — każda z nich pełni inną, charakterystyczną funkcję.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-tkanki-k2',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Krew jest rodzajem tkanki łącznej.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — krew zaliczana jest do tkanki łącznej, mimo że jest płynna. Jej istotą międzykomórkową jest płynne osocze, w którym rozproszone są komórki krwi.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-tkanki-03',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jaką funkcję pełni głównie tkanka nabłonkowa pokrywająca skórę (naskórek)?',
      opcje: [
        'Kurczenie się i wykonywanie ruchu',
        'Ochrona głębiej położonych tkanek przed uszkodzeniami, wysychaniem i drobnoustrojami',
        'Przewodzenie impulsów nerwowych',
        'Magazynowanie tłuszczu jako materiału zapasowego',
      ],
      poprawna: 1,
      wyjasnienie: 'Naskórek jest tkanką nabłonkową, której główną funkcją jest ochrona głębiej położonych tkanek przed uszkodzeniami, wysychaniem i wnikaniem drobnoustrojów.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-tkanki-04',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdania właściwymi nazwami tkanek.',
      tekstZLuka:
        'Tkanka zbudowana z komórek zdolnych do kurczenia się, umożliwiająca wykonywanie ruchu, to tkanka {{luka1}}. Tkanka zbudowana głównie z neuronów, odbierająca i przewodząca impulsy, to tkanka {{luka2}}.',
      odpowiedziLuk: { luka1: ['mięśniowa', 'mieśniowa'], luka2: ['nerwowa'] },
      wyjasnienie: 'Tkanka mięśniowa umożliwia ruch dzięki zdolności komórek do kurczenia się, a tkanka nerwowa, zbudowana głównie z neuronów, odbiera bodźce i przewodzi impulsy nerwowe.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-tkanki-05',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Co odróżnia tkankę łączną od tkanki nabłonkowej pod względem budowy?',
      opcje: [
        'Tkanka łączna ma komórki ciasno przylegające do siebie, a nabłonkowa — rozproszone w istocie międzykomórkowej',
        'Tkanka łączna ma komórki rozproszone w obfitej istocie międzykomórkowej, a nabłonkowa — ciasno ułożone komórki tworzące zwarte warstwy',
        'Obie tkanki mają identyczną budowę, różnią się jedynie miejscem występowania',
        'Tkanka łączna nie zawiera żadnych komórek, tylko istotę międzykomórkową',
      ],
      poprawna: 1,
      wyjasnienie:
        'Tkanka nabłonkowa zbudowana jest z ciasno ułożonych komórek tworzących zwarte warstwy (funkcje ochronne, wchłaniające, wydzielnicze), natomiast tkanka łączna ma komórki rozproszone w obfitej istocie międzykomórkowej (funkcje podporowe, łączące, odżywcze i obronne).',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-tkanki-06',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj typ tkanki do jej funkcji i przykładu narządu/struktury, którą buduje.',
      dopasowanie: {
        lewa: ['Tkanka nabłonkowa', 'Tkanka łączna', 'Tkanka mięśniowa', 'Tkanka nerwowa'],
        prawa: [
          'Naskórek chroniący ciało przed uszkodzeniami i drobnoustrojami',
          'Kość budująca szkielet, pełniąca funkcję podporową',
          'Mięsień sercowy, którego kurczenie się pompuje krew',
          'Mózg odbierający i przetwarzający bodźce z otoczenia',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie:
        'Tkanka nabłonkowa buduje m.in. naskórek (ochrona), tkanka łączna buduje kości (podpora), tkanka mięśniowa buduje mięsień sercowy (kurczliwość, pompowanie krwi), a tkanka nerwowa buduje mózg (odbiór i przetwarzanie bodźców).',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-tkanki-07',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych stwierdzeń o tkance mięśniowej są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Mięśnie szkieletowe kurczą się pod kontrolą woli (świadomie)',
        'Mięsień sercowy kurczy się mimowolnie',
        'Mięśnie gładkie występują np. w ścianach żołądka, jelit i naczyń krwionośnych',
        'Wszystkie rodzaje mięśni kurczą się wyłącznie świadomie, pod kontrolą woli',
      ],
      poprawna: [0, 1, 2],
      wyjasnienie:
        'Mięśnie szkieletowe sterowane są świadomie, mięsień sercowy i mięśnie gładkie kurczą się mimowolnie. Mięśnie gładkie budują m.in. ściany żołądka, jelit i naczyń krwionośnych. Stwierdzenie czwarte jest fałszywe, bo nie wszystkie mięśnie kurczą się świadomie.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-tkanki-08',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'image',
      poziom: 'sredni',
      punkty: 1,
      diagramId: 'd-t206-4typy',
      tresc: 'Na schemacie przedstawiono cztery podstawowe typy tkanek zwierzęcych. Który z nich pełni funkcję kurczliwości, umożliwiającą wykonywanie ruchu?',
      opcje: ['Tkanka nabłonkowa', 'Tkanka łączna', 'Tkanka mięśniowa', 'Tkanka nerwowa'],
      poprawna: 2,
      wyjasnienie: 'Zgodnie ze schematem tkanka mięśniowa jest zbudowana z komórek zdolnych do kurczenia się, co umożliwia wykonywanie ruchu — przykładem są mięśnie szkieletowe i mięsień sercowy.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-tkanki-09',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Jaką rolę pełnią neurony budujące tkankę nerwową?',
      opcje: [
        'Kurczą się, umożliwiając ruch całego ciała',
        'Odbierają bodźce oraz przewodzą i przekazują impulsy nerwowe',
        'Tworzą zwarte warstwy pokrywające powierzchnię ciała',
        'Magazynują substancje odżywcze w obfitej istocie międzykomórkowej',
      ],
      poprawna: 1,
      wyjasnienie: 'Neurony (komórki nerwowe) są wyspecjalizowane w odbieraniu bodźców oraz przewodzeniu i przekazywaniu impulsów nerwowych — to podstawowa funkcja tkanki nerwowej.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-tkanki-10',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Mięsień sercowy, mimo że jest poprzecznie prążkowany podobnie jak mięśnie szkieletowe, kurczy się mimowolnie, niezależnie od naszej woli.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — mięsień sercowy jest poprzecznie prążkowany (jak mięśnie szkieletowe), ale w odróżnieniu od nich kurczy się mimowolnie, co zapewnia nieprzerwaną pracę serca.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-tkanki-11',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'single',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Dlaczego rany naskórka (skóry) goją się stosunkowo szybko?',
      opcje: [
        'Ponieważ komórki nabłonka szybko się dzielą i odnawiają, co daje tej tkance dużą zdolność do regeneracji',
        'Ponieważ naskórek zbudowany jest z tkanki nerwowej, której komórki intensywnie się dzielą',
        'Ponieważ gojenie ran nie wymaga udziału żadnych komórek',
        'Ponieważ naskórek zbudowany jest wyłącznie z istoty międzykomórkowej, bez komórek',
      ],
      poprawna: 0,
      wyjasnienie: 'Komórki tkanki nabłonkowej szybko się odnawiają i dzielą, dzięki czemu ma ona dużą zdolność do regeneracji — dlatego rany skóry (uszkodzenia naskórka) goją się stosunkowo szybko.',
      umiejetnosci: ['przyczynowo-skutkowe', 'wiedza'],
    },
    {
      id: 'p-t206-tkanki-12',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych struktur zaliczane są do tkanki łącznej? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Tkanka kostna (kości szkieletu)', 'Tkanka chrzęstna (np. małżowina uszna)', 'Krew', 'Naskórek'],
      poprawna: [0, 1, 2],
      wyjasnienie:
        'Do tkanki łącznej zalicza się m.in. tkankę kostną, tkankę chrzęstną oraz krew (z płynną istotą międzykomórkową — osoczem). Naskórek to tkanka nabłonkowa, a nie łączna.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-tkanki-13',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'gapfill',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uzupełnij zdanie dotyczące krwi jako tkanki łącznej.',
      tekstZLuka: 'Krew zaliczana jest do tkanki {{luka1}}, ponieważ jej istota międzykomórkowa, czyli {{luka2}}, ma postać płynną.',
      odpowiedziLuk: { luka1: ['łącznej'], luka2: ['osocze', 'osocza'] },
      wyjasnienie: 'Krew jest rodzajem tkanki łącznej, mimo że jest płynna — jej istotą międzykomórkową jest płynne osocze, w którym rozproszone są komórki krwi.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-tkanki-14',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc:
        'Ściana żołądka zbudowana jest m.in. z tkanki nabłonkowej wyściełającej jego wnętrze, tkanki mięśniowej gładkiej w ścianie oraz tkanki łącznej. Co świadczy to o budowie narządów zwierzęcych?',
      opcje: [
        'Każdy narząd zbudowany jest tylko z jednego typu tkanki',
        'Narządy są zwykle zbudowane z kilku różnych tkanek współpracujących ze sobą, z których każda pełni inną funkcję',
        'Tkanki w obrębie jednego narządu nigdy się ze sobą nie stykają',
        'Żołądek nie zawiera żadnej tkanki łącznej',
      ],
      poprawna: 1,
      wyjasnienie:
        'Narządy ciała są zwykle zbudowane z kilku różnych tkanek współpracujących ze sobą — np. w żołądku nabłonek wyściela i chroni, mięśnie gładkie umożliwiają ruchy trawienne, a tkanka łączna spaja i odżywia narząd.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-tkanki-15',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Dopasuj rodzaj tkanki łącznej do jej opisu.',
      dopasowanie: {
        lewa: ['Tkanka kostna', 'Tkanka chrzęstna', 'Tkanka tłuszczowa', 'Krew'],
        prawa: [
          'Buduje kości szkieletu, pełni funkcję podporową',
          'Buduje np. małżowinę uszną oraz chrząstki stawowe',
          'Magazynuje materiał zapasowy i chroni ciało przed utratą ciepła',
          'Płynna tkanka łączna transportująca tlen i substancje odżywcze',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie:
        'Tkanka kostna buduje szkielet (podpora), tkanka chrzęstna buduje np. małżowinę uszną i chrząstki stawowe, tkanka tłuszczowa magazynuje materiał zapasowy i chroni przed utratą ciepła, a krew — płynna tkanka łączna — transportuje tlen i substancje odżywcze.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-tkanki-16',
      dzialId: 'd2',
      tematId: 't206-tkanki',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc:
        'Uszkodzenie tkanki nerwowej (np. neuronów rdzenia kręgowego) regeneruje się znacznie trudniej i wolniej niż uszkodzenie nabłonka skóry. Co najlepiej to tłumaczy?',
      opcje: [
        'Neurony, w przeciwieństwie do komórek nabłonka, dzielą się bardzo rzadko lub wcale, co ogranicza zdolność tkanki nerwowej do odnowy',
        'Tkanka nerwowa w ogóle nie jest zbudowana z komórek',
        'Neurony są znacznie mniejsze niż komórki nabłonka, dlatego trudniej im się odnawiać',
        'Tkanka nerwowa nie pełni żadnej funkcji ochronnej, dlatego organizm nie musi jej regenerować',
      ],
      poprawna: 0,
      wyjasnienie:
        'Komórki nabłonka szybko się dzielą i odnawiają, co daje tej tkance dużą zdolność do regeneracji. Neurony natomiast dzielą się bardzo rzadko lub wcale, dlatego uszkodzenia tkanki nerwowej goją się dużo trudniej i wolniej niż uszkodzenia nabłonka.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
  ]);
})();
