(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t204-mchy-01',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Mchy zaliczamy do roślin:',
      opcje: ['zarodnikowych, beznaczyniowych', 'nasiennych, naczyniowych', 'zarodnikowych, naczyniowych', 'nasiennych, beznaczyniowych'],
      poprawna: 0,
      wyjasnienie: 'Mchy rozmnażają się za pomocą zarodników (rośliny zarodnikowe) i nie mają tkanek przewodzących (rośliny beznaczyniowe).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-mchy-02',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Mchy mają prawdziwe korzenie, którymi skutecznie pobierają wodę z głębszych warstw gleby.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — mchy nie mają prawdziwych korzeni. Zamiast nich mają chwytniki (ryzoidy), które jedynie przytwierdzają roślinę do podłoża.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-mchy-03',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Struktury, które u mchów zastępują korzenie i służą jedynie do przytwierdzania rośliny do podłoża, to:',
      opcje: ['korzenie przybyszowe', 'chwytniki (ryzoidy)', 'kłącze', 'bulwy'],
      poprawna: 1,
      wyjasnienie: 'Chwytniki (ryzoidy) to nitkowate wyrostki mocujące mech do podłoża — nie pobierają skutecznie wody.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-mchy-04',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie: Mchy rosną najlepiej w miejscach {{luka1}} i zacienionych, ponieważ ich rozmnażanie płciowe wymaga obecności {{luka2}}.',
      tekstZLuka: 'Mchy rosną najlepiej w miejscach {{luka1}} i zacienionych, ponieważ ich rozmnażanie płciowe wymaga obecności {{luka2}}.',
      odpowiedziLuk: { luka1: ['wilgotnych'], luka2: ['wody'] },
      wyjasnienie: 'Bez wody plemniki nie mogłyby dopłynąć do rodni, dlatego mchy potrzebują wilgotnego środowiska.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-mchy-05',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dlaczego mchy osiągają niewielkie rozmiary (zwykle kilka centymetrów wysokości)?',
      opcje: [
        'Ponieważ nie mają tkanek przewodzących ani wzmacniających, które umożliwiałyby transport wody na duże odległości i utrzymanie większych rozmiarów',
        'Ponieważ rosną wyłącznie w cieniu, gdzie brakuje światła do fotosyntezy',
        'Ponieważ ich zarodniki są bardzo ciężkie i nie mogą być przenoszone daleko od rośliny macierzystej',
        'Ponieważ mchy są organizmami jednokomórkowymi',
      ],
      poprawna: 0,
      wyjasnienie: 'Brak tkanek przewodzących i wzmacniających uniemożliwia mchom transport wody na duże odległości oraz utrzymanie dużych, wyprostowanych rozmiarów.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-mchy-06',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Widoczna, zielona roślina mchu, którą zwykle obserwujemy w lesie, to sporofit.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — widoczna, zielona postać mchu to gametofit. Sporofit to zarodnia na nóżce, osadzona na gametofitcie.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-mchy-07',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj pojęcie do jego opisu.',
      dopasowanie: {
        lewa: ['Gametofit', 'Sporofit', 'Chwytniki', 'Protonema'],
        prawa: ['Dominujące, widoczne pokolenie płciowe mchu', 'Pokolenie bezpłciowe — zarodnia na nóżce osadzona na gametofitcie', 'Nitkowate struktury przytwierdzające mech do podłoża', 'Nitkowata forma powstająca z kiełkującego zarodnika'],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Gametofit to widoczne pokolenie płciowe, sporofit to zarodnia na nóżce, chwytniki mocują mech do podłoża, a protonema to etap kiełkowania zarodnika.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-mchy-08',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych stwierdzeń są prawdziwe dla mchów? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Nie mają prawdziwych tkanek przewodzących', 'Rozmnażanie płciowe wymaga obecności wody', 'Wytwarzają nasiona', 'Dominującym pokoleniem w cyklu rozwojowym jest gametofit'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Mchy nie mają tkanek przewodzących, ich rozmnażanie płciowe zależy od wody, a dominującym pokoleniem jest gametofit. Mchy nie wytwarzają nasion — są roślinami zarodnikowymi.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t204-mchy-09',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Torfowce, obumierając w warunkach niedoboru tlenu i gromadząc się warstwami przez długi czas, przyczyniają się do powstawania:',
      opcje: ['torfu', 'gleby próchnicznej wyłącznie w lasach liściastych', 'skał wapiennych', 'węgla kamiennego'],
      poprawna: 0,
      wyjasnienie: 'Obumierające warstwy torfowców, gromadzące się w warunkach niedoboru tlenu na torfowiskach, przekształcają się w torf.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t204-mchy-10',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Uporządkuj etapy cyklu rozwojowego mchu, zaczynając od dojrzałego gametofitu.',
      elementy: [
        'Dojrzały gametofit (mech) wytwarza plemnie i rodnie',
        'Zapłodnienie w obecności wody — powstaje zygota',
        'Rozwój sporofitu (zarodni na nóżce) z zygoty',
        'Powstanie zarodników w zarodni w wyniku mejozy',
        'Kiełkowanie zarodnika w protonemę i nowy gametofit',
      ],
      wyjasnienie: 'Cykl rozwojowy mchu przebiega: dojrzały gametofit → zapłodnienie (w wodzie) → sporofit (zarodnia) → zarodniki (mejoza) → protonema → nowy gametofit.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t204-mchy-11',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Zarówno mchy, jak i paprocie należą do roślin zarodnikowych. Co to oznacza?',
      opcje: ['Rozmnażają się za pomocą zarodników, a nie nasion', 'Nie mają zdolności do fotosyntezy', 'Rozmnażają się wyłącznie wegetatywnie, bez udziału gamet', 'Wytwarzają owoce chroniące nasiona'],
      poprawna: 0,
      wyjasnienie: 'Rośliny zarodnikowe to grupa rozmnażająca się za pomocą zarodników powstających w zarodniach, w przeciwieństwie do roślin nasiennych.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-mchy-12',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które struktury występują w cyklu rozwojowym mchu? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Plemnia', 'Rodnia', 'Zarodnia (sporofit)', 'Szyszka'],
      poprawna: [0, 1, 2],
      wyjasnienie: 'W cyklu rozwojowym mchu występują plemnie, rodnie i zarodnia (sporofit). Szyszki są strukturą charakterystyczną dla roślin nagonasiennych, nie mchów.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-mchy-13',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'W lesie zaobserwowano bujny rozwój mchów na powalonych, stale wilgotnych pniach drzew, natomiast na suchych, silnie nasłonecznionych skałach te same gatunki występowały w formie niewielkich, skarlałych kępek. Co najlepiej tłumaczy tę różnicę?',
      opcje: [
        'Mchy nie mają skutecznych mechanizmów ograniczających utratę wody (brak grubej kutykuli, brak korzeni pobierających wodę z głębi gleby), dlatego ich rozwój silnie zależy od wilgotności podłoża i powietrza',
        'Mchy rosnące na skałach należą do zupełnie innej grupy organizmów niż mchy leśne',
        'Mchy potrzebują bardzo dużych ilości bezpośredniego światła słonecznego, którego brakuje na powalonych, zacienionych pniach',
        'Różne pokolenia tego samego mchu rosną wyłącznie na różnych rodzajach podłoża',
      ],
      poprawna: 0,
      wyjasnienie: 'Ze względu na brak skutecznej ochrony przed utratą wody i brak korzeni sięgających do głębszych, wilgotnych warstw podłoża, wzrost i kondycja mchów silnie zależą od dostępnej wilgotności.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t204-mchy-14',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Plemniki mchów są zdolne do samodzielnego, aktywnego ruchu w wodzie dzięki obecności wici.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'Plemniki mchów mają wici, dzięki którym mogą aktywnie płynąć w wodzie do rodni, gdzie znajduje się komórka jajowa.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-mchy-15',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie: Zjawisko następowania po sobie w cyklu rozwojowym pokolenia płciowego i bezpłciowego nazywamy {{luka1}}. U mchów dominującym pokoleniem, widocznym gołym okiem, jest {{luka2}}.',
      tekstZLuka: 'Zjawisko następowania po sobie w cyklu rozwojowym pokolenia płciowego i bezpłciowego nazywamy {{luka1}}. U mchów dominującym pokoleniem, widocznym gołym okiem, jest {{luka2}}.',
      odpowiedziLuk: { luka1: ['przemianą pokoleń', 'przemiana pokoleń'], luka2: ['gametofit'] },
      wyjasnienie: 'Przemiana pokoleń to naprzemienne następowanie gametofitu i sporofitu; u mchów dominuje gametofit.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-mchy-16',
      dzialId: 'd2',
      tematId: 't204-mchy',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dopasuj etap cyklu rozwojowego mchu do jego opisu.',
      dopasowanie: {
        lewa: ['Gametofit (mech)', 'Sporofit (zarodnia na nóżce)', 'Zarodniki', 'Zygota'],
        prawa: [
          'Pokolenie wytwarzające gamety (plemniki i komórki jajowe)',
          'Pokolenie powstałe z zapłodnionej komórki jajowej, produkujące zarodniki w wyniku mejozy',
          'Komórki rozsiewane i kiełkujące w nowy gametofit (poprzez protonemę)',
          'Komórka powstała z połączenia plemnika i komórki jajowej, z której rozwija się sporofit',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Gametofit wytwarza gamety, z ich połączenia powstaje zygota, z której rozwija się sporofit produkujący zarodniki, a te kiełkują w nowy gametofit.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
  ]);
})();
