(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t204-okrytonasienne-01',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Organem rozmnażania płciowego rośliny okrytonasiennej jest:',
      opcje: ['kwiat', 'szyszka', 'sorus', 'chwytnik'],
      poprawna: 0,
      wyjasnienie: 'Kwiat jest organem rozmnażania płciowego roślin okrytonasiennych.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-okrytonasienne-02',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'U roślin okrytonasiennych nasiona są ukryte wewnątrz owocu.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — właśnie ukrycie nasion wewnątrz owocu, powstałego z zalążni, decyduje o nazwie tej grupy roślin.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-okrytonasienne-03',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Męskim organem płciowym kwiatu jest:',
      opcje: ['pręcik', 'słupek', 'płatek korony', 'działka kielicha'],
      poprawna: 0,
      wyjasnienie: 'Pręcik, złożony z nitki i pylnika, jest męskim organem płciowym kwiatu — wytwarza pyłek.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-okrytonasienne-04',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie: Żeński organ płciowy kwiatu to {{luka1}}, złożony ze znamienia, szyjki i {{luka2}}.',
      tekstZLuka: 'Żeński organ płciowy kwiatu to {{luka1}}, złożony ze znamienia, szyjki i {{luka2}}.',
      odpowiedziLuk: { luka1: ['słupek'], luka2: ['zalążni'] },
      wyjasnienie: 'Słupek to żeński organ płciowy kwiatu, zbudowany ze znamienia, szyjki i zalążni zawierającej zalążki.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-okrytonasienne-05',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Owoc rośliny okrytonasiennej powstaje z:',
      opcje: ['zalążni słupka, po zapłodnieniu zalążków', 'pręcika, po wytworzeniu pyłku', 'działek kielicha, po przekwitnięciu kwiatu', 'korzenia rośliny'],
      poprawna: 0,
      wyjasnienie: 'Po zapłodnieniu ściana zalążni rozrasta się i przekształca w owoc, który otacza rozwijające się z zalążków nasiona.',
      umiejetnosci: ['budowa-funkcja'],
    },
    {
      id: 'p-t204-okrytonasienne-06',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Barwna, pachnąca korona kwiatu i obecność nektaru są zwykle przystosowaniem do zapylenia przez wiatr.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — barwa, zapach i nektar to przystosowania przyciągające owady (entomogamia). Kwiaty zapylane przez wiatr są zwykle niepozorne, bez płatków i nektaru.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-okrytonasienne-07',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj pojęcie do jego opisu.',
      dopasowanie: {
        lewa: ['Pręcik', 'Słupek', 'Korona', 'Kielich'],
        prawa: [
          'Męski organ płciowy złożony z nitki i pylnika',
          'Żeński organ płciowy złożony ze znamienia, szyjki i zalążni',
          'Okółek barwnych płatków, przyciągający zapylaczy',
          'Okółek zielonych działek, chroniący pąk kwiatowy',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Pręcik to organ męski, słupek to organ żeński, korona to barwne płatki, a kielich to zielone działki chroniące pąk.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-okrytonasienne-08',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które funkcje pełni owoc rośliny okrytonasiennej? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Otacza i chroni znajdujące się w nim nasiona', 'Ułatwia rozsiewanie nasion (np. przez zwierzęta lub wiatr)', 'Zastępuje pręcik w wytwarzaniu pyłku', 'Powstaje z rozrastającej się ściany zalążni po zapłodnieniu'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Owoc chroni nasiona, ułatwia ich rozsiewanie i powstaje z zalążni po zapłodnieniu. Nie wytwarza pyłku — to funkcja pręcika.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t204-okrytonasienne-09',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego kwiaty zapylane przez owady są zwykle barwne, pachnące i wytwarzają nektar, a kwiaty zapylane przez wiatr są niepozorne?',
      opcje: [
        'Barwa, zapach i nektar to przystosowania przyciągające owady przenoszące pyłek; roślinom zapylanym wiatrem takie przystosowania są niepotrzebne, bo pyłek roznosi ruch powietrza',
        'Kwiaty niepozorne wcale nie wytwarzają pyłku',
        'Barwa kwiatu zależy wyłącznie od żyzności gleby, a nie od sposobu zapylenia',
        'Nektar jest potrzebny wyłącznie do odżywiania rozwijającego się nasiona',
      ],
      poprawna: 0,
      wyjasnienie: 'Barwa, zapach i nektar to koszt energetyczny ponoszony po to, by przyciągnąć owady — rośliny zapylane wiatrem nie muszą przyciągać zapylaczy, więc oszczędzają te zasoby.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t204-okrytonasienne-10',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Uporządkuj etapy powstawania nasiona i owocu u rośliny okrytonasiennej.',
      elementy: [
        'Zapylenie — przeniesienie pyłku z pręcika na znamię słupka',
        'Wzrost łagiewki pyłkowej w kierunku zalążni',
        'Zapłodnienie zalążka w zalążni',
        'Przekształcenie zalążka w nasiono',
        'Rozrost ściany zalążni w owoc otaczający nasiona',
      ],
      wyjasnienie: 'Kolejność: zapylenie → wzrost łagiewki pyłkowej → zapłodnienie zalążka → powstanie nasiona → rozwój owocu z zalążni.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t204-okrytonasienne-11',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Podstawą podziału roślin okrytonasiennych na jednoliścienne i dwuliścienne jest przede wszystkim:',
      opcje: ['liczba liścieni w zarodku nasienia', 'barwa kwiatów', 'wielkość owocu', 'środowisko życia rośliny'],
      poprawna: 0,
      wyjasnienie: 'Rośliny jednoliścienne mają jeden liścień w zarodku nasienia, a dwuliścienne — dwa; to podstawowe kryterium tego podziału.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-okrytonasienne-12',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych roślin są przykładami roślin okrytonasiennych? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Jabłoń', 'Groch', 'Sosna', 'Tulipan'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Jabłoń, groch i tulipan to rośliny okrytonasienne (wytwarzają kwiaty i owoce). Sosna jest rośliną nagonasienną.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-okrytonasienne-13',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Kwiaty pewnej rośliny są duże, intensywnie zabarwione, silnie pachnące i wytwarzają dużo nektaru, a ich pyłek jest lepki i gruboziarnisty. Który sposób zapylenia jest u niej najbardziej prawdopodobny?',
      opcje: [
        'Zapylenie przez owady (entomogamia)',
        'Zapylenie przez wiatr (anemogamia)',
        'Samozapylenie bez udziału jakiegokolwiek przenośnika pyłku',
        'Zapylenie wyłącznie przez wodę',
      ],
      poprawna: 0,
      wyjasnienie: 'Lepki, gruboziarnisty pyłek słabo unosi się w powietrzu, ale łatwo przykleja się do ciała owada, a barwa, zapach i nektar przyciągają zapylaczy — to typowe cechy kwiatów zapylanych przez owady.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t204-okrytonasienne-14',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Każdy owoc rośliny okrytonasiennej musi być soczysty i jadalny dla człowieka.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — owocem w sensie biologicznym jest każda struktura powstała z zalążni po zapłodnieniu, w tym owoce suche (np. strąk grochu, orzech), niekoniecznie soczyste ani jadalne dla ludzi.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t204-okrytonasienne-15',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie: U roślin okrytonasiennych nasiona są ukryte wewnątrz {{luka1}}, powstającego z rozrastającej się ściany {{luka2}} po zapłodnieniu zalążków.',
      tekstZLuka: 'U roślin okrytonasiennych nasiona są ukryte wewnątrz {{luka1}}, powstającego z rozrastającej się ściany {{luka2}} po zapłodnieniu zalążków.',
      odpowiedziLuk: { luka1: ['owocu'], luka2: ['zalążni'] },
      wyjasnienie: 'Owoc powstaje z rozrastającej się ściany zalążni po zapłodnieniu zalążków, które przekształcają się w nasiona.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t204-okrytonasienne-16',
      dzialId: 'd2',
      tematId: 't204-okrytonasienne',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dopasuj pojęcie do jego opisu.',
      dopasowanie: {
        lewa: ['Entomogamia', 'Anemogamia', 'Owoc mięsisty', 'Owoc suchy ze skrzydełkiem'],
        prawa: [
          'Zapylenie za pośrednictwem owadów',
          'Zapylenie za pośrednictwem wiatru',
          'Ułatwia rozsiewanie nasion przez zwierzęta, które go zjadają',
          'Ułatwia rozsiewanie nasion przez wiatr, np. u klonu',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Entomogamia to zapylenie przez owady, anemogamia przez wiatr, owoc mięsisty jest rozsiewany przez zwierzęta, a owoc ze skrzydełkiem — przez wiatr.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
  ]);
})();
