(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t206-plazy-k1',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jaką cechę skóry mają płazy?',
      opcje: ['Skóra pokryta rogowymi łuskami', 'Skóra naga i wilgotna', 'Skóra pokryta piórami', 'Skóra pokryta sierścią'],
      poprawna: 1,
      wyjasnienie: 'Płazy mają nagą, pozbawioną łusek skórę, utrzymywaną w wilgoci — pełni ona funkcję dodatkowego narządu oddechowego.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-plazy-k2',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Kijanka oddycha za pomocą płuc.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — kijanka oddycha skrzelami, tak jak ryby. Płuca wykształcają się dopiero w toku przeobrażenia.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-plazy-03',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jak nazywa się proces przekształcania kijanki w dorosłego płaza?',
      opcje: ['Linienie', 'Przeobrażenie (metamorfoza)', 'Regeneracja', 'Hibernacja'],
      poprawna: 1,
      wyjasnienie: 'Przekształcenie wodnej larwy (kijanki) w dorosłego płaza przystosowanego do życia na lądzie nazywamy przeobrażeniem, czyli metamorfozą.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-plazy-04',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Dorosłe płazy oddychają w sposób {{luka1}}. Jaja płazów, pozbawione twardej skorupy, nazywamy {{luka2}}.',
      odpowiedziLuk: { luka1: ['płucno-skórny', 'płucno-skórny sposób'], luka2: ['skrzekiem', 'skrzek'] },
      wyjasnienie: 'Dorosłe płazy oddychają płucno-skórnie, a ich jaja bez skorupy, otoczone galaretowatą osłonką, to skrzek.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-plazy-05',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych cech są charakterystyczne dla płazów? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Naga, wilgotna skóra', 'Jaja osłonięte wapienną skorupą', 'Zmiennocieplność', 'Rozwój larwalny (kijanka) w wodzie'],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Płazy mają nagą, wilgotną skórę, są zmiennocieplne, a ich rozwój larwalny (stadium kijanki) przebiega w wodzie. Jaja z wapienną skorupą to cecha gadów i ptaków, nie płazów.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
    {
      id: 'p-t206-plazy-06',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj etap rozwoju żaby do jego głównej cechy.',
      dopasowanie: {
        lewa: ['Skrzek', 'Kijanka', 'Kijanka z odnóżami', 'Dorosła żaba'],
        prawa: ['Oddycha płucami i skórą, ma kończyny', 'Jaja bez skorupy złożone w wodzie', 'Oddycha skrzelami, ma ogon', 'Zanika ogon, wykształcają się płuca'],
        pary: [1, 2, 3, 0],
      },
      wyjasnienie: 'Skrzek to jaja bez skorupy złożone w wodzie, kijanka oddycha skrzelami i ma ogon, kijanka z odnóżami traci ogon i zyskuje płuca, a dorosła żaba oddycha płucno-skórnie i ma w pełni wykształcone kończyny.',
      umiejetnosci: ['schemat', 'wiedza'],
    },
    {
      id: 'p-t206-plazy-07',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj etapy cyklu rozwojowego żaby, poczynając od złożenia jaj.',
      elementy: ['Jajo (skrzek) złożone w wodzie', 'Kijanka oddychająca skrzelami', 'Kijanka z odnóżami — zanika ogon', 'Dorosła żaba oddychająca płucami i skórą'],
      wyjasnienie: 'Cykl rozwojowy żaby przebiega w kolejności: jajo → kijanka oddychająca skrzelami → kijanka z odnóżami, u której zanika ogon → dorosła żaba oddychająca płucno-skórnie.',
      umiejetnosci: ['schemat', 'wiedza'],
    },
    {
      id: 'p-t206-plazy-08',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'image',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Na schemacie budowy zewnętrznej żaby numerem 1 oznaczono skórę. Jaką dodatkową funkcję (poza ochronną) pełni ona u płazów?',
      diagramId: 'd-t206-plazy-budowa',
      opcje: ['Magazynuje wodę na okres suszy', 'Jest dodatkowym narządem oddechowym', 'Wytwarza mleko dla młodych', 'Chroni przed nadmiernym ciepłem jak futro'],
      poprawna: 1,
      wyjasnienie: 'Naga, wilgotna i bogato unaczyniona skóra płaza jest dodatkowym narządem wymiany gazowej — umożliwia oddychanie skórne, uzupełniające oddychanie płucne.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-plazy-09',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Wszystkie dorosłe płazy mają ogon.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — u żab i ropuch ogon zanika w toku przeobrażenia, natomiast traszki i salamandry zachowują ogon również jako dorosłe zwierzęta.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t206-plazy-10',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego płazy muszą utrzymywać skórę stale wilgotną?',
      opcje: [
        'Ponieważ wilgotna skóra lepiej odbija światło słoneczne',
        'Ponieważ oddychanie skórne, uzupełniające oddychanie płucne, wymaga stałej wilgoci skóry',
        'Ponieważ suche powietrze uszkadza im wzrok',
        'Ponieważ wilgoć pomaga trawić pokarm',
      ],
      poprawna: 1,
      wyjasnienie: 'Wymiana gazowa przez skórę (oddychanie skórne) możliwa jest tylko wtedy, gdy skóra pozostaje wilgotna — wysychanie znacznie ją utrudnia lub uniemożliwia.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t206-plazy-11',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które stwierdzenia o zmiennocieplności płazów są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Temperatura ciała płaza zależy od temperatury otoczenia',
        'Płazy potrafią samodzielnie utrzymać stałą, wysoką temperaturę ciała',
        'Zimą płazy zapadają w odrętwienie, gdy temperatura otoczenia spada',
        'Zmiennocieplność cechuje ryby, płazy i gady',
      ],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Płazy są zmiennocieplne — ich temperatura ciała zależy od otoczenia, a zimą zapadają w odrętwienie. Zmiennocieplność cechuje ryby, płazy i gady (w odróżnieniu od stałocieplnych ptaków i ssaków).',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-plazy-12',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż zwierzę, którego jaja są składane w wodzie i nie mają twardej skorupy.',
      tabela: {
        tytul: 'Jaja wybranych kręgowców',
        kolumny: ['Zwierzę', 'Miejsce składania jaj', 'Rodzaj osłony jaja'],
        wiersze: [
          ['Żaba trawna (płaz)', 'woda', 'galaretowata osłonka, bez skorupy'],
          ['Zaskroniec (gad)', 'ląd', 'elastyczna skorupa'],
          ['Wróbel (ptak)', 'ląd (gniazdo)', 'twarda, wapienna skorupa'],
        ],
      },
      opcje: ['Żaba trawna', 'Zaskroniec', 'Wróbel', 'Żadne z powyższych'],
      poprawna: 0,
      wyjasnienie: 'Żaba trawna, jako płaz, składa jaja (skrzek) w wodzie — są one otoczone jedynie galaretowatą osłonką, bez twardej skorupy, w odróżnieniu od jaj gadów i ptaków.',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t206-plazy-13',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'matching',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dopasuj gatunek płaza do jego cechy charakterystycznej.',
      dopasowanie: {
        lewa: ['Żaba trawna', 'Ropucha szara', 'Traszka zwyczajna', 'Rzekotka drzewna'],
        prawa: ['Zachowuje ogon jako dorosłe zwierzę', 'Skacze na silnych tylnych kończynach, traci ogon', 'Chodzi drobnymi krokami, ma suchawą, brodawkowatą skórę', 'Ma przylgi na palcach ułatwiające wspinaczkę po roślinach'],
        pary: [1, 2, 0, 3],
      },
      wyjasnienie: 'Żaba trawna skacze i traci ogon w toku przeobrażenia, ropucha ma charakterystyczną brodawkowatą skórę, traszka jako płaz ogoniasty zachowuje ogon, a rzekotka ma przylgi ułatwiające wspinaczkę.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t206-plazy-14',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'W wysychającym latem oczku wodnym zaobserwowano masowe śnięcie kijanek, podczas gdy dorosłe żaby, które wcześniej opuściły zbiornik, przetrwały bez szkody. Co najlepiej wyjaśnia tę różnicę?',
      opcje: [
        'Kijanki są bardziej wrażliwe na światło słoneczne niż dorosłe żaby',
        'Kijanki oddychają skrzelami i są w pełni zależne od środowiska wodnego, natomiast dorosłe żaby oddychają płucno-skórnie i mogą przebywać na lądzie',
        'Dorosłe żaby są odporne na brak wody, ponieważ nie potrzebują tlenu',
        'Kijanki nie mają jeszcze układu krwionośnego',
      ],
      poprawna: 1,
      wyjasnienie: 'Kijanki oddychają skrzelami, więc muszą przebywać w wodzie — wyschnięcie zbiornika odcina im dostęp do tlenu. Dorosłe żaby oddychają płucno-skórnie i mogą funkcjonować poza wodą, dlatego mogły opuścić wysychające oczko.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t206-plazy-15',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'diagram',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Na podstawie schematu cyklu rozwojowego żaby: na którym etapie zwierzę po raz pierwszy zyskuje zdolność oddychania powietrzem atmosferycznym za pomocą płuc?',
      diagramId: 'd-t206-plazy-cykl',
      opcje: ['Jajo (skrzek)', 'Kijanka', 'Kijanka z odnóżami', 'Etap ten nie występuje u płazów'],
      poprawna: 2,
      wyjasnienie: 'To w stadium kijanki z odnóżami zanika ogon i wykształcają się płuca — od tego momentu zwierzę zyskuje zdolność oddychania powietrzem atmosferycznym, którą w pełni wykorzystuje jako dorosła żaba.',
      umiejetnosci: ['schemat', 'budowa-funkcja'],
    },
    {
      id: 'p-t206-plazy-16',
      dzialId: 'd2',
      tematId: 't206-plazy',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Które z poniższych zestawień poprawnie łączy cechę budowy płaza z jej funkcją?',
      opcje: [
        'Błona bębenkowa — wykrywanie zapachów',
        'Naga, wilgotna skóra — dodatkowy narząd wymiany gazowej',
        'Błony pławne między palcami — wysiadywanie jaj',
        'Duże, wypukłe oczy — trawienie pokarmu',
      ],
      poprawna: 1,
      wyjasnienie: 'Naga, wilgotna skóra płaza jest dodatkowym narządem oddechowym. Błona bębenkowa odbiera dźwięki, błony pławne ułatwiają pływanie, a duże oczy zapewniają szerokie pole widzenia — żaden z pozostałych zestawień nie jest poprawny.',
      umiejetnosci: ['budowa-funkcja', 'analiza'],
    },
  ]);
})();
