(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t108-01',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Które organellum przechowuje materiał genetyczny (DNA) i kontroluje procesy zachodzące w komórce?',
      opcje: ['Mitochondrium', 'Jądro komórkowe', 'Aparat Golgiego', 'Rybosom'],
      poprawna: 1,
      wyjasnienie: 'Jądro komórkowe przechowuje DNA i pełni funkcję centrum sterującego procesami życiowymi komórki.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-02',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'W którym organellum zachodzi oddychanie komórkowe i produkcja energii w postaci ATP?',
      opcje: ['Chloroplast', 'Aparat Golgiego', 'Mitochondrium', 'Siateczka śródplazmatyczna gładka'],
      poprawna: 2,
      wyjasnienie: 'Mitochondrium to organellum, w którym z substancji odżywczych i tlenu wytwarzana jest energia w postaci ATP — dlatego nazywa się je "elektrownią komórki".',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-03',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc:
        'Białko wyprodukowane przez rybosomy przytwierdzone do siateczki śródplazmatycznej szorstkiej ma zostać wydzielone poza komórkę. Które organellum jako kolejne modyfikuje je, sortuje i pakuje do transportu?',
      opcje: ['Jądro komórkowe', 'Aparat Golgiego', 'Mitochondrium', 'Wakuola'],
      poprawna: 1,
      wyjasnienie: 'Aparat Golgiego odbiera białka z siateczki śródplazmatycznej, modyfikuje je, sortuje i pakuje w pęcherzyki transportowe kierowane m.in. na zewnątrz komórki.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-04',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc:
        'Komórki mięśniowe zawierają wyjątkowo dużą liczbę pewnego organellum w porównaniu z innymi komórkami ciała. Które organellum i dlaczego?',
      opcje: [
        'Chloroplasty — bo mięśnie potrzebują światła do pracy',
        'Mitochondria — bo skurcz mięśnia wymaga bardzo dużych ilości energii (ATP)',
        'Wakuole — bo mięśnie magazynują dużo wody',
        'Rybosomy — bo mięśnie nie potrzebują energii, tylko białek strukturalnych',
      ],
      poprawna: 1,
      wyjasnienie: 'Skurcz mięśni jest procesem bardzo energochłonnym, dlatego komórki mięśniowe zawierają wyjątkowo dużo mitochondriów — organelli produkujących ATP w procesie oddychania komórkowego.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t108-05',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Rybosomy są organellami otoczonymi błoną.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — rybosomy zbudowane są z RNA i białek i nie są otoczone żadną błoną, w przeciwieństwie do większości innych organelli.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-06',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Mitochondria występują wyłącznie w komórkach roślinnych.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — mitochondria występują we wszystkich komórkach eukariotycznych, zarówno roślinnych, jak i zwierzęcych, grzybów i protistów.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t108-07',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które organelle są otoczone dwiema błonami (podwójną otoczką)? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Jądro komórkowe', 'Rybosom', 'Mitochondrium', 'Chloroplast'],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Jądro komórkowe, mitochondrium i chloroplast są otoczone dwiema błonami. Rybosom nie jest otoczony żadną błoną.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-08',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'multiple',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Które struktury występują TYLKO w typowej komórce roślinnej, a nie w komórce zwierzęcej? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Ściana komórkowa', 'Mitochondrium', 'Chloroplast', 'Duża, centralna wakuola'],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Ściana komórkowa, chloroplasty i duża centralna wakuola są typowe dla komórek roślinnych. Mitochondria występują w obu typach komórek.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-09',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj organellum do jego głównej funkcji.',
      dopasowanie: {
        lewa: ['Mitochondrium', 'Chloroplast', 'Aparat Golgiego', 'Rybosom'],
        prawa: ['Produkcja energii (ATP) w oddychaniu komórkowym', 'Fotosynteza', 'Modyfikowanie, sortowanie i pakowanie białek', 'Synteza białek'],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Mitochondrium — oddychanie komórkowe i ATP; chloroplast — fotosynteza; aparat Golgiego — obróbka i pakowanie białek; rybosom — synteza białek.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-10',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'matching',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dopasuj organellum do charakterystycznej cechy jego budowy.',
      dopasowanie: {
        lewa: ['Mitochondrium', 'Jądro komórkowe', 'Siateczka śródplazmatyczna szorstka', 'Wakuola'],
        prawa: [
          'Wewnętrzna błona silnie pofałdowana (grzebienie)',
          'Otoczone otoczką z licznymi porami, zawiera jąderko',
          'Ma na powierzchni przytwierdzone rybosomy',
          'Pęcherzyk wypełniony sokiem komórkowym',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Każda z tych cech budowy jest ściśle związana z funkcją danego organellum — zasada budowa → funkcja.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-11',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Organellum, w którym zachodzi fotosynteza, nazywa się {{luka1}}. Organellum produkujące energię w postaci ATP to {{luka2}}.',
      odpowiedziLuk: { luka1: ['chloroplast'], luka2: ['mitochondrium'] },
      wyjasnienie: 'Chloroplast przeprowadza fotosyntezę, a mitochondrium — oddychanie komórkowe, w którym powstaje ATP.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t108-12',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'gapfill',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Struktury odpowiedzialne za syntezę białek to {{luka1}}. Organellum, które modyfikuje, sortuje i pakuje białka do transportu, to {{luka2}}.',
      odpowiedziLuk: { luka1: ['rybosomy'], luka2: ['aparat Golgiego'] },
      wyjasnienie: 'Rybosomy syntetyzują białka, a aparat Golgiego jest odpowiedzialny za ich dalszą obróbkę, sortowanie i pakowanie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t108-13',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj etapy "drogi" białka przeznaczonego do wydzielenia poza komórkę, od powstania do wysłania.',
      elementy: ['Synteza białka na rybosomie', 'Wstępna obróbka w siateczce śródplazmatycznej szorstkiej', 'Modyfikacja i pakowanie w aparacie Golgiego', 'Transport pęcherzykiem do błony komórkowej i wydzielenie na zewnątrz'],
      wyjasnienie: 'Białko powstaje na rybosomie, trafia do siateczki śródplazmatycznej szorstkiej na wstępną obróbkę, następnie do aparatu Golgiego, gdzie jest modyfikowane i pakowane, po czym w pęcherzyku transportowym dociera do błony komórkowej i zostaje wydzielone.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-14',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'image',
      diagramId: 'd-t108-komorka-zwierzeca',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Na schemacie komórki zwierzęcej, który numer oznacza jądro komórkowe?',
      opcje: ['Numer 1', 'Numer 2', 'Numer 4', 'Numer 7'],
      poprawna: 1,
      wyjasnienie: 'Numer 2 wskazuje jądro komórkowe — dużą, okrągłą strukturę z widocznym jąderkiem (numer 3).',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-15',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'image',
      diagramId: 'd-t108-komorka-roslinna',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Na schemacie komórki roślinnej, który numer oznacza chloroplast — organellum odpowiedzialne za fotosyntezę?',
      opcje: ['Numer 1', 'Numer 4', 'Numer 6', 'Numer 9'],
      poprawna: 1,
      wyjasnienie: 'Numer 4 oznacza chloroplasty — zielone organelle, w których zachodzi fotosynteza. Numer 1 to ściana komórkowa, 6 to wakuola centralna, a 9 to rybosomy.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-16',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'image',
      diagramId: 'd-t108-komorka-zwierzeca',
      poziom: 'konkursowy',
      punkty: 2,
      tresc:
        'Na schemacie komórki zwierzęcej struktura oznaczona numerem 6 ma na swojej powierzchni drobne kropki (rybosomy), a struktura oznaczona numerem 7 nie ma ich wcale, mimo podobnego, falistego kształtu błon. Co to oznacza?',
      opcje: [
        'Struktura 6 to siateczka śródplazmatyczna szorstka (uczestniczy w syntezie białek), a struktura 7 to aparat Golgiego (modyfikuje i pakuje gotowe białka)',
        'Struktura 6 i 7 to dwa fragmenty tego samego organellum bez żadnej różnicy funkcjonalnej',
        'Struktura 7 to siateczka śródplazmatyczna, a 6 to aparat Golgiego',
        'Obecność rybosomów oznacza, że struktura 6 to mitochondrium',
      ],
      poprawna: 0,
      wyjasnienie: 'Obecność przytwierdzonych rybosomów jest charakterystyczna dla siateczki śródplazmatycznej szorstkiej (6), która uczestniczy w syntezie białek. Aparat Golgiego (7) nie ma rybosomów — jego rola to dalsza modyfikacja, sortowanie i pakowanie białek.',
      umiejetnosci: ['diagram', 'analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t108-17',
      dzialId: 'd1',
      tematId: 't108',
      typ: 'table',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż zdanie prawdziwe.',
      tabela: {
        tytul: 'Występowanie wybranych organelli w komórce roślinnej i zwierzęcej',
        kolumny: ['Organellum', 'Komórka roślinna', 'Komórka zwierzęca'],
        wiersze: [
          ['Mitochondrium', 'Obecne', 'Obecne'],
          ['Chloroplast', 'Obecny (nie zawsze)', 'Brak'],
          ['Ściana komórkowa', 'Obecna', 'Brak'],
          ['Duża, centralna wakuola', 'Zwykle obecna', 'Brak (mogą być małe wakuole)'],
        ],
      },
      opcje: [
        'Mitochondria występują tylko w komórce roślinnej',
        'Chloroplasty występują w każdej komórce roślinnej i zwierzęcej',
        'Ściana komórkowa i duża centralna wakuola są typowe dla komórki roślinnej, a nie zwierzęcej',
        'Komórka zwierzęca ma więcej rodzajów organelli niż roślinna',
      ],
      poprawna: 2,
      wyjasnienie: 'Z tabeli wynika, że ściana komórkowa i duża centralna wakuola charakteryzują komórkę roślinną, natomiast mitochondria występują w obu typach komórek, a chloroplasty nie występują w każdej komórce roślinnej ani w żadnej zwierzęcej.',
      umiejetnosci: ['tabela', 'analiza'],
    },
  ]);
})();
