(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t114-01',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Które słowne równanie poprawnie opisuje oddychanie tlenowe?',
      opcje: [
        'Dwutlenek węgla + woda + energia świetlna → glukoza + tlen',
        'Glukoza + tlen → dwutlenek węgla + woda + energia',
        'Glukoza + woda → tlen + energia',
        'Kwas mlekowy + tlen → glukoza + dwutlenek węgla',
      ],
      poprawna: 1,
      wyjasnienie: 'W oddychaniu tlenowym glukoza jest rozkładana przy udziale tlenu do dwutlenku węgla i wody, a przy tym uwalniana jest energia.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t114-02',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'W jakim organellum komórkowym zachodzi oddychanie tlenowe?',
      opcje: ['W chloroplaście', 'W mitochondrium', 'W jądrze komórkowym', 'W wakuoli'],
      poprawna: 1,
      wyjasnienie: 'Oddychanie tlenowe zachodzi w mitochondriach — organellach obecnych w niemal każdej żywej komórce.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t114-03',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Oddychanie komórkowe zachodzi we wszystkich żywych komórkach, przez całą dobę.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — w przeciwieństwie do fotosyntezy, oddychanie komórkowe zachodzi nieprzerwanie we wszystkich żywych komórkach, niezależnie od pory dnia czy dostępu do światła.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t114-04',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie opisujące substraty i produkty oddychania tlenowego.',
      tekstZLuka: 'Substratami oddychania tlenowego są glukoza i {{luka1}}, a jej produktami są dwutlenek węgla, woda i {{luka2}}.',
      odpowiedziLuk: { luka1: ['tlen'], luka2: ['energia'] },
      wyjasnienie: 'Oddychanie tlenowe przekształca glukozę i tlen w dwutlenek węgla, wodę i energię.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t114-05',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Który produkt powstaje w fermentacji mleczanowej zachodzącej w mięśniach człowieka podczas intensywnego wysiłku fizycznego?',
      opcje: ['Etanol', 'Kwas mlekowy', 'Glukoza', 'Chlorofil'],
      poprawna: 1,
      wyjasnienie: 'Fermentacja mleczanowa, zachodząca w mięśniach przy niedostatecznym dopływie tlenu, prowadzi do powstania kwasu mlekowego, którego nagromadzenie powoduje uczucie zmęczenia mięśni.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t114-06',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'truefalse',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Oddychanie komórkowe to to samo zjawisko co wymiana gazowa (wdech i wydech) zachodząca w płucach.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — wymiana gazowa w płucach to fizyczny transport gazów (pobór tlenu, usuwanie CO2) do i z krwi, natomiast oddychanie komórkowe to proces chemiczny zachodzący wewnątrz każdej żywej komórki, uwalniający energię z pokarmu.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t114-07',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które stwierdzenia o fermentacji są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Fermentacja alkoholowa zachodzi u drożdży',
        'Fermentacja mleczanowa może zachodzić w mięśniach człowieka',
        'Fermentacja uwalnia więcej energii niż oddychanie tlenowe',
        'Fermentacja nie wymaga obecności tlenu',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Fermentację alkoholową prowadzą drożdże, fermentację mleczanową — m.in. mięśnie człowieka przy niedotlenieniu, a oba procesy nie wymagają tlenu. Fermentacja uwalnia znacznie mniej energii niż oddychanie tlenowe, więc trzecie stwierdzenie jest fałszywe.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t114-08',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj proces do miejsca lub organizmu, w którym typowo zachodzi.',
      dopasowanie: {
        lewa: ['Oddychanie tlenowe', 'Fermentacja mleczanowa', 'Fermentacja alkoholowa', 'Fotosynteza'],
        prawa: ['Chloroplast rośliny', 'Mitochondrium komórki', 'Komórka drożdży', 'Mięśnie człowieka przy dużym wysiłku'],
        pary: [1, 3, 2, 0],
      },
      wyjasnienie: 'Oddychanie tlenowe zachodzi w mitochondrium, fermentacja mleczanowa — m.in. w mięśniach człowieka przy intensywnym wysiłku, fermentacja alkoholowa — w komórkach drożdży, a fotosynteza — w chloroplastach roślin.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t114-09',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj etapy oddychania tlenowego w komórce, od dostarczenia substratów do powstania produktów.',
      elementy: ['Glukoza i tlen docierają do komórki', 'Glukoza i tlen trafiają do mitochondrium', 'W mitochondrium zachodzi rozkład glukozy z udziałem tlenu', 'Powstają dwutlenek węgla, woda i energia'],
      wyjasnienie: 'Glukoza i tlen docierają do komórki, następnie trafiają do mitochondrium, gdzie glukoza jest rozkładana z udziałem tlenu, w wyniku czego powstają dwutlenek węgla, woda i energia.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t114-10',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'chart',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na wykresie przedstawiono zależność zużycia tlenu przez organizm człowieka od intensywności wykonywanego wysiłku fizycznego. Na podstawie wykresu określ, jak zmienia się zużycie tlenu wraz ze wzrostem intensywności wysiłku.',
      wykres: {
        typ: 'liniowy',
        tytul: 'Zużycie tlenu w zależności od intensywności wysiłku fizycznego',
        jednostka: 'dm3/min',
        dane: [
          { etykieta: 'spoczynek', wartosc: 0.3 },
          { etykieta: 'marsz', wartosc: 1.0 },
          { etykieta: 'trucht', wartosc: 2.2 },
          { etykieta: 'bieg', wartosc: 3.4 },
          { etykieta: 'sprint', wartosc: 4.5 },
        ],
      },
      opcje: [
        'Zużycie tlenu maleje wraz ze wzrostem intensywności wysiłku',
        'Zużycie tlenu rośnie wraz ze wzrostem intensywności wysiłku, ponieważ pracujące mięśnie zużywają więcej energii i intensywniej oddychają komórkowo',
        'Zużycie tlenu jest stałe niezależnie od intensywności wysiłku',
        'Zużycie tlenu spada do zera podczas sprintu',
      ],
      poprawna: 1,
      wyjasnienie: 'Im intensywniejszy wysiłek fizyczny, tym więcej energii potrzebują pracujące mięśnie, a więc intensywniej zachodzi w nich oddychanie tlenowe, co zwiększa zapotrzebowanie na tlen i jego zużycie.',
      umiejetnosci: ['wykres', 'analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t114-11',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Podczas bardzo intensywnego biegu dopływ tlenu do mięśni nóg jest niewystarczający w stosunku do zapotrzebowania energetycznego. Jaki będzie najbardziej prawdopodobny skutek tej sytuacji dla komórek mięśniowych?',
      opcje: [
        'Komórki mięśniowe przełączą się na fotosyntezę',
        'W komórkach mięśniowych nasili się fermentacja mleczanowa i zacznie gromadzić się kwas mlekowy',
        'Komórki mięśniowe przestaną potrzebować energii',
        'Zwiększy się produkcja tlenu przez mitochondria',
      ],
      poprawna: 1,
      wyjasnienie: 'Gdy dopływ tlenu nie nadąża za zapotrzebowaniem energetycznym mięśni, część energii zaczyna być uwalniana w procesie fermentacji mleczanowej, czego skutkiem jest gromadzenie się kwasu mlekowego i uczucie zmęczenia mięśni.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t114-12',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'W mięśniach człowieka podczas intensywnego wysiłku fizycznego może zachodzić fermentacja alkoholowa.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — w mięśniach człowieka przy niedotlenieniu zachodzi fermentacja mleczanowa, a nie alkoholowa. Fermentację alkoholową prowadzą np. drożdże, a organizm człowieka jej nie przeprowadza.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t114-13',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które stwierdzenia porównujące oddychanie tlenowe i beztlenowe są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Oddychanie tlenowe uwalnia więcej energii z tej samej ilości glukozy niż fermentacja',
        'Oddychanie tlenowe zachodzi w mitochondrium, a fermentacja głównie w cytoplazmie',
        'Tylko oddychanie tlenowe zużywa glukozę jako substrat',
        'Produktem fermentacji alkoholowej jest etanol i dwutlenek węgla',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Oddychanie tlenowe jest znacznie wydajniejsze energetycznie i zachodzi w mitochondrium, a fermentacja — głównie w cytoplazmie. Produktem fermentacji alkoholowej jest etanol i CO2. Zarówno oddychanie tlenowe, jak i fermentacja wykorzystują glukozę jako substrat, więc trzecie stwierdzenie jest fałszywe.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t114-14',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Piekarz dodaje do ciasta drożdże i zostawia je w ciepłym miejscu do wyrośnięcia. Ciasto zwiększa swoją objętość i staje się puszyste. Co jest najbardziej prawdopodobną biologiczną przyczyną tego zjawiska?',
      opcje: [
        'Drożdże prowadzą fotosyntezę i wydzielają tlen, który spulchnia ciasto',
        'Drożdże prowadzą fermentację alkoholową, a wydzielany przy tym dwutlenek węgla tworzy pęcherzyki spulchniające ciasto',
        'Drożdże oddychają tlenowo i wydzielają wodę, która spulchnia ciasto',
        'Drożdże rozkładają mąkę na tlen i azot',
      ],
      poprawna: 1,
      wyjasnienie: 'Drożdże w cieście, w warunkach ograniczonego dostępu do tlenu, prowadzą fermentację alkoholową, w wyniku której z cukrów zawartych w mące powstaje etanol i dwutlenek węgla. Pęcherzyki uwalnianego CO2 spulchniają ciasto.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t114-15',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie dotyczące ilości energii uwalnianej w różnych typach oddychania.',
      tekstZLuka: 'Z tej samej ilości glukozy oddychanie tlenowe uwalnia {{luka1}} energii niż fermentacja, ponieważ fermentacja to proces {{luka2}}, w którym glukoza jest rozkładana tylko częściowo.',
      odpowiedziLuk: { luka1: ['więcej'], luka2: ['beztlenowy', 'niewymagający tlenu'] },
      wyjasnienie: 'Oddychanie tlenowe rozkłada glukozę w pełni, z udziałem tlenu, uwalniając dużo energii. Fermentacja jest procesem beztlenowym, w którym glukoza jest rozkładana tylko częściowo, dlatego uwalnia się znacznie mniej energii.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t114-16',
      dzialId: 'd1',
      tematId: 't114',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Dopasuj sytuację do jej najbardziej prawdopodobnego wyjaśnienia biologicznego.',
      dopasowanie: {
        lewa: ['Ból i zmęczenie mięśni po sprincie', 'Bąbelki gazu w rosnącym cieście drożdżowym', 'Produkcja jogurtu z mleka przez bakterie', 'Nieprzerwane wydzielanie CO2 przez śpiące zwierzę'],
        prawa: ['Fermentacja alkoholowa drożdży', 'Fermentacja mleczanowa bakterii', 'Oddychanie komórkowe zachodzące przez całą dobę', 'Nagromadzenie kwasu mlekowego z fermentacji mleczanowej'],
        pary: [3, 0, 1, 2],
      },
      wyjasnienie: 'Ból mięśni po sprincie wynika z nagromadzenia kwasu mlekowego (fermentacja mleczanowa), bąbelki w cieście to efekt fermentacji alkoholowej drożdży, jogurt powstaje dzięki fermentacji mleczanowej bakterii, a wydzielanie CO2 przez śpiące zwierzę to dowód, że oddychanie komórkowe zachodzi nieprzerwanie, także podczas snu.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
  ]);
})();
