(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t205-k1',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Co oznacza, że grzyby są organizmami cudzożywnymi?',
      opcje: [
        'Same wytwarzają substancje organiczne w procesie fotosyntezy',
        'Pobierają gotowe substancje organiczne z otoczenia, ponieważ nie przeprowadzają fotosyntezy',
        'Odżywiają się wyłącznie wodą i solami mineralnymi',
        'Żywią się wyłącznie innymi grzybami',
      ],
      poprawna: 1,
      wyjasnienie:
        'Cudzożywność oznacza, że organizm nie potrafi sam wytworzyć związków organicznych z nieorganicznych (jak robią to rośliny w fotosyntezie), lecz musi pobierać gotowe substancje odżywcze z otoczenia — np. rozkładając materię organiczną, pasożytując lub żyjąc w mikoryzie.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t205-k2',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Grzyby, podobnie jak rośliny, mają ścianę komórkową zbudowaną z celulozy.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie:
        'To fałsz — ściana komórkowa grzybów zbudowana jest z chityny, a nie z celulozy. Celuloza buduje ściany komórkowe roślin. To jedna z cech odróżniających grzyby od roślin.',
      umiejetnosci: ['wiedza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t205-03',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jak nazywa się właściwe ciało grzyba, zbudowane z nitkowatych strzępek i rozwijające się zwykle w podłożu?',
      opcje: ['Owocnik', 'Grzybnia', 'Kapelusz', 'Zarodnik'],
      poprawna: 1,
      wyjasnienie: 'Grzybnia to właściwe ciało grzyba — sieć strzępek rozwijająca się w podłożu, pobierająca wodę i substancje odżywcze.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t205-04',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Grzyby rozmnażają się za pomocą {{luka1}}, które powstają w {{luka2}} na blaszkach lub w rurkach pod kapeluszem.',
      odpowiedziLuk: { luka1: ['zarodników', 'zarodniki'], luka2: ['owocnikach', 'owocniku'] },
      wyjasnienie: 'Grzyby wytwarzają zarodniki w owocnikach — to podstawowy sposób rozmnażania grzybów wielkoowocnikowych.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t205-05',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Grzybnia grzyba tworzącego mikoryzę oplata korzenie sosny. Co grzyb otrzymuje dzięki tej symbiozie?',
      opcje: ['Tlen potrzebny do fotosyntezy', 'Cukry powstałe w procesie fotosyntezy rośliny', 'Chitynę budującą ścianę komórkową', 'Zarodniki do rozmnażania'],
      poprawna: 1,
      wyjasnienie: 'W mikoryzie grzyb otrzymuje od rośliny cukry wytworzone w fotosyntezie, a w zamian dostarcza jej wodę i sole mineralne pobrane dzięki rozległej grzybni.',
      umiejetnosci: ['budowa-funkcja', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t205-06',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj pojęcie do jego opisu.',
      dopasowanie: {
        lewa: ['Grzybnia', 'Owocnik', 'Zarodnik', 'Chityna'],
        prawa: [
          'Substancja budująca ścianę komórkową grzybów',
          'Organ służący do wytwarzania i rozsiewania zarodników',
          'Mikroskopijna struktura rozmnożeniowa',
          'Sieć strzępek pobierająca wodę i substancje odżywcze z podłoża',
        ],
        pary: [3, 1, 2, 0],
      },
      wyjasnienie:
        'Grzybnia to sieć strzępek pobierająca wodę i substancje odżywcze; owocnik służy do wytwarzania i rozsiewania zarodników; zarodnik to struktura rozmnożeniowa; chityna buduje ścianę komórkową grzybów.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t205-07',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych stwierdzeń o grzybach są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Grzyby są cudzożywne', 'Grzyby przeprowadzają fotosyntezę tak jak rośliny', 'Ściana komórkowa grzybów zawiera chitynę', 'Grzybnia znajduje się zwykle pod powierzchnią podłoża'],
      poprawna: [0, 2, 3],
      wyjasnienie:
        'Grzyby są cudzożywne i nie przeprowadzają fotosyntezy (stwierdzenie drugie jest fałszywe). Ich ściana komórkowa zawiera chitynę, a grzybnia rozwija się zwykle pod powierzchnią podłoża.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t205-08',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'image',
      poziom: 'sredni',
      punkty: 1,
      diagramId: 'd-t205-owocnik',
      tresc: 'Na schemacie budowy grzyba wielkoowocnikowego element oznaczony numerem 4 to podziemna sieć strzępek. Jaką pełni funkcję?',
      opcje: ['Wytwarza i rozsiewa zarodniki', 'Pobiera wodę i substancje odżywcze z podłoża', 'Unosi kapelusz nad powierzchnię gleby', 'Chroni owocnik przed wysychaniem'],
      poprawna: 1,
      wyjasnienie: 'Element nr 4 to grzybnia (strzępki) — właściwe ciało grzyba, które pobiera wodę i substancje odżywcze z podłoża i przekazuje je m.in. do owocnika.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t205-09',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'single',
      poziom: 'trudny',
      punkty: 1,
      tresc:
        'Grzybnia jednego grzyba (opieńki miodowej) w lesie w USA (Oregon) zajmuje powierzchnię porównywalną z wieloma kilometrami kwadratowymi i jest uznawana za jeden z największych żywych organizmów na Ziemi. Co to świadczy o grzybni?',
      opcje: [
        'Grzybnia to pojedyncza komórka, która osiąga ogromne rozmiary',
        'Grzybnia może rozrastać się przez wiele lat, tworząc rozległą sieć strzępek znacznie większą niż widoczne owocniki',
        'Każdy owocnik grzyba ma osobną, niezależną grzybnię',
        'Wielkość grzybni zależy wyłącznie od liczby wytworzonych zarodników',
      ],
      poprawna: 1,
      wyjasnienie:
        'Grzybnia jest zbudowana z wielu komórek (strzępek) i może rozrastać się przez lata, obejmując bardzo duży obszar podłoża — znacznie większy niż widoczne nad ziemią, stosunkowo niewielkie owocniki.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t205-10',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Wszystkie grzyby pasożytnicze prowadzą wyłącznie do śmierci organizmu żywiciela.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie:
        'To fałsz — pasożyt czerpie korzyści kosztem żywiciela i mu szkodzi, ale niekoniecznie prowadzi bezpośrednio do jego śmierci; wiele grzybic ma przebieg przewlekły, osłabiający, lecz nie zawsze śmiertelny dla żywiciela.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t205-11',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj etapy cyklu rozwojowego grzyba wielkoowocnikowego, zaczynając od zarodnika.',
      elementy: [
        'Zarodnik opada na sprzyjające podłoże',
        'Zarodnik kiełkuje i wytwarza grzybnię',
        'Grzybnia rozrasta się w podłożu, pobierając wodę i substancje odżywcze',
        'W sprzyjających warunkach z grzybni wyrasta owocnik',
        'Owocnik wytwarza nowe zarodniki',
      ],
      wyjasnienie:
        'Cykl rozwojowy przebiega: zarodnik opada na podłoże → kiełkuje, tworząc grzybnię → grzybnia rozrasta się, pobierając wodę i substancje odżywcze → wyrasta z niej owocnik → owocnik wytwarza nowe zarodniki, które rozpoczynają cykl od nowa.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t205-12',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które z poniższych organizmów/przykładów są grzybami wykorzystywanymi bezpośrednio przez człowieka? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Drożdże piekarskie', 'Pleśń Penicillium (źródło penicyliny)', 'Sinice', 'Borowik szlachetny (grzyb jadalny)'],
      poprawna: [0, 1, 3],
      wyjasnienie:
        'Drożdże wykorzystuje się w piekarnictwie i produkcji napojów, pleśń Penicillium jest źródłem antybiotyku penicyliny, a borowik szlachetny to ceniony grzyb jadalny. Sinice to bakterie fotosyntetyzujące, nie grzyby.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t205-13',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'W lesie iglastym usunięto większość grzybów mikoryzowych współżyjących z korzeniami drzew. Jaki najbardziej prawdopodobny skutek to spowoduje dla wzrostu drzew?',
      opcje: [
        'Drzewa będą rosły szybciej, bo nie będą "dzielić się" cukrami z grzybami',
        'Drzewa będą miały utrudnione pobieranie wody i soli mineralnych z gleby, co osłabi ich wzrost',
        'Drzewa zaczną same wytwarzać chitynę',
        'Nie będzie żadnych skutków, bo mikoryza nie wpływa na drzewa',
      ],
      poprawna: 1,
      wyjasnienie:
        'Grzyby mikoryzowe znacząco zwiększają powierzchnię pobierania wody i soli mineralnych przez korzenie drzew dzięki rozległej grzybni. Ich brak utrudnia drzewom pobieranie tych składników, co osłabia wzrost — mimo utraty części cukrów oddawanych grzybowi, korzyści z mikoryzy zwykle przeważają.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t205-14',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Dopasuj sposób odżywiania się grzyba do opisanego przykładu.',
      dopasowanie: {
        lewa: ['Saprotrofizm', 'Pasożytnictwo', 'Mikoryza'],
        prawa: [
          'Grzyb rozkładający opadłe liście i próchniejące drewno w lesie',
          'Grzyb wywołujący grzybicę skóry u człowieka',
          'Grzyb oplatający korzenie sosny, wymieniający wodę i sole mineralne na cukry',
        ],
        pary: [0, 1, 2],
      },
      wyjasnienie:
        'Rozkład martwej materii organicznej to saprotrofizm; czerpanie substancji z żywego organizmu ze szkodą dla niego to pasożytnictwo; korzystna wymiana wody i soli mineralnych za cukry z korzeniami drzew to mikoryza.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t205-15',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc:
        'Dlaczego grzyby, mimo że nie poruszają się i rosną osadzone w podłożu, klasyfikuje się bliżej organizmów cudzożywnych (jak zwierzęta) niż samożywnych (jak rośliny)?',
      opcje: [
        'Ponieważ mają układ nerwowy podobny do zwierząt',
        'Ponieważ podobnie jak zwierzęta nie przeprowadzają fotosyntezy i pobierają gotowe związki organiczne z otoczenia',
        'Ponieważ ich komórki nie mają ściany komórkowej, tak jak u zwierząt',
        'Ponieważ rozmnażają się płciowo, tak jak zwierzęta',
      ],
      poprawna: 1,
      wyjasnienie:
        'Sposób odżywiania (a nie zdolność do ruchu) decyduje o przynależności do organizmów cudzożywnych — grzyby, podobnie jak zwierzęta, nie mają chlorofilu i nie przeprowadzają fotosyntezy, więc muszą pobierać gotowe związki organiczne z otoczenia.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t205-16',
      dzialId: 'd2',
      tematId: 't205',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie opisujące mikoryzę.',
      tekstZLuka:
        'W mikoryzie grzyb dostarcza roślinie {{luka1}} i sole mineralne pobrane dzięki rozległej grzybni, a w zamian otrzymuje od rośliny {{luka2}} powstałe w procesie fotosyntezy.',
      odpowiedziLuk: { luka1: ['wodę', 'wode'], luka2: ['cukry', 'cukier'] },
      wyjasnienie: 'Mikoryza to symbioza korzystna dla obu stron: grzyb dostarcza wodę i sole mineralne, a otrzymuje cukry wytworzone przez roślinę w fotosyntezie.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
  ]);
})();
