(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t115-k1',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Które zdanie poprawnie opisuje rozmnażanie bezpłciowe?',
      opcje: [
        'Powstaje z połączenia dwóch gamet i daje potomstwo zróżnicowane genetycznie',
        'Bierze w nim udział jeden organizm rodzicielski, a potomstwo jest identyczne genetycznie z rodzicem',
        'Zawsze wymaga udziału dwóch organizmów rodzicielskich różnej płci',
        'Zachodzi wyłącznie u roślin okrytonasiennych',
      ],
      poprawna: 1,
      wyjasnienie:
        'Rozmnażanie bezpłciowe polega na wytworzeniu potomstwa przez jeden organizm rodzicielski, bez udziału gamet i zapłodnienia — potomek jest genetycznie identyczny z rodzicem (klon).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t115-k2',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Rozmnażanie płciowe zwiększa zmienność genetyczną potomstwa w porównaniu z rozmnażaniem bezpłciowym.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie:
        'Prawda — podczas rozmnażania płciowego materiał genetyczny dwóch rodziców łączy się w nowych kombinacjach, dzięki czemu potomstwo różni się genetycznie od rodziców i od siebie nawzajem.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t115-03',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc:
        'Drożdże (jednokomórkowe grzyby) rozmnażają się bezpłciowo poprzez wytworzenie małego wyrostka na komórce macierzystej, z którego powstaje nowa komórka. Jak nazywamy ten sposób rozmnażania?',
      opcje: ['Podział', 'Pączkowanie', 'Fragmentacja', 'Rozmnażanie wegetatywne'],
      poprawna: 1,
      wyjasnienie:
        'To pączkowanie — z komórki macierzystej wyrasta pąk, który powiększa się i oddziela jako nowy, samodzielny organizm (np. u drożdży i stułbi pospolitej).',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t115-04',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdania dotyczące rozmnażania płciowego.',
      tekstZLuka:
        'Komórki rozrodcze biorące udział w rozmnażaniu płciowym nazywamy {{luka1}}. Połączenie się gamety męskiej i żeńskiej to {{luka2}}, w wyniku którego powstaje {{luka3}}.',
      odpowiedziLuk: { luka1: ['gametami', 'gamety'], luka2: ['zapłodnienie'], luka3: ['zygota', 'zygotę'] },
      wyjasnienie:
        'Gamety (komórki rozrodcze) łączą się w procesie zapłodnienia, tworząc zygotę — pierwszą komórkę nowego organizmu.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t115-05',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Które z poniższych NIE jest przykładem rozmnażania bezpłciowego?',
      opcje: [
        'Podział ameby na dwie komórki potomne',
        'Powstanie nowej rośliny truskawki z rozłogu',
        'Powstanie zygoty z połączenia plemnika i komórki jajowej',
        'Regeneracja nowego osobnika płazińca z fragmentu ciała',
      ],
      poprawna: 2,
      wyjasnienie:
        'Połączenie plemnika i komórki jajowej (zapłodnienie) to etap rozmnażania płciowego, ponieważ bierze w nim udział materiał genetyczny dwóch rodziców.',
      umiejetnosci: ['analiza'],
    },
    {
      id: 'p-t115-06',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Zaznacz wszystkie wymienione sposoby, które są formami rozmnażania bezpłciowego.',
      opcje: [
        'Podział komórki',
        'Pączkowanie',
        'Zapłodnienie zewnętrzne',
        'Fragmentacja (rozpad ciała na części zdolne do regeneracji)',
        'Rozmnażanie wegetatywne roślin (np. rozłogami)',
      ],
      poprawna: [0, 1, 3, 4],
      wyjasnienie:
        'Podział, pączkowanie, fragmentacja i rozmnażanie wegetatywne to formy rozmnażania bezpłciowego — biorą w nich udział komórki jednego organizmu bez udziału gamet. Zapłodnienie jest etapem rozmnażania płciowego.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t115-07',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj organizm/przykład do właściwego sposobu rozmnażania bezpłciowego.',
      dopasowanie: {
        lewa: ['Stułbia (hydra)', 'Ziemniak', 'Rozgwiazda (regeneracja z fragmentu ramienia)', 'Bakteria'],
        prawa: ['Podział komórki', 'Pączkowanie', 'Rozmnażanie wegetatywne (bulwami)', 'Fragmentacja'],
        pary: [1, 2, 3, 0],
      },
      wyjasnienie:
        'Stułbia rozmnaża się przez pączkowanie, ziemniak wegetatywnie za pomocą bulw, rozgwiazda może się zregenerować z fragmentu ciała (fragmentacja), a bakterie rozmnażają się przez podział komórki.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t115-08',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj etapy rozmnażania płciowego w prawidłowej kolejności.',
      elementy: ['Powstanie gamety męskiej i żeńskiej', 'Zapłodnienie (połączenie gamet)', 'Powstanie zygoty', 'Rozwój nowego organizmu'],
      wyjasnienie:
        'Najpierw powstają gamety męska i żeńska, następnie dochodzi do zapłodnienia i powstania zygoty, z której rozwija się nowy organizm.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t115-09',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc:
        'Dlaczego rozmnażanie bezpłciowe prowadzi do znacznie mniejszej zmienności genetycznej potomstwa niż rozmnażanie płciowe?',
      opcje: [
        'Ponieważ w rozmnażaniu bezpłciowym potomek powstaje z jednego rodzica i dziedziczy dokładnie taki sam materiał genetyczny, bez łączenia genów dwóch osobników',
        'Ponieważ organizmy rozmnażające się bezpłciowo mają mniej chromosomów',
        'Ponieważ rozmnażanie bezpłciowe zachodzi wolniej niż płciowe',
        'Ponieważ w rozmnażaniu bezpłciowym powstaje więcej potomstwa jednocześnie',
      ],
      poprawna: 0,
      wyjasnienie:
        'W rozmnażaniu bezpłciowym potomek powstaje z komórek jednego organizmu rodzicielskiego (np. przez podział lub pączkowanie) i otrzymuje kopię jego materiału genetycznego — nie dochodzi do łączenia genów dwóch różnych osobników, jak podczas zapłodnienia. Dlatego potomstwo jest genetycznie identyczne z rodzicem (klon), a cała populacja powstała bezpłciowo jest genetycznie jednorodna.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t115-10',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc:
        'Sadzonka pelargonii ukorzeniona z fragmentu łodygi rośliny matecznej jest genetycznie identyczna z rośliną, z której ją pobrano.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie:
        'Prawda — sadzonkowanie to forma rozmnażania wegetatywnego (bezpłciowego), więc nowa roślina jest genetyczną kopią (klonem) rośliny macierzystej.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t115-11',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Które stwierdzenia o rozmnażaniu wegetatywnym roślin są prawdziwe? Zaznacz wszystkie poprawne.',
      opcje: [
        'Nowa roślina może powstać z rozłogów, np. u truskawki',
        'Nowa roślina może powstać z kłącza, np. u perzu',
        'Rozmnażanie wegetatywne zawsze wymaga udziału pyłku i zapylenia',
        'Rośliny rozmnożone wegetatywnie są genetycznie identyczne z rośliną macierzystą',
        'Bulwy ziemniaka są jednym z organów służących do rozmnażania wegetatywnego',
      ],
      poprawna: [0, 1, 3, 4],
      wyjasnienie:
        'Rozmnażanie wegetatywne roślin zachodzi za pomocą organów wegetatywnych — rozłogów (truskawka), kłączy (perz), bulw (ziemniak) — i nie wymaga pyłku ani zapylenia (to cechy rozmnażania płciowego). Rośliny powstałe wegetatywnie są genetycznie identyczne z rośliną macierzystą.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t115-12',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'table',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na podstawie tabeli porównującej rozmnażanie bezpłciowe i płciowe wskaż zdanie prawdziwe.',
      tabela: {
        tytul: 'Porównanie rozmnażania bezpłciowego i płciowego',
        kolumny: ['Cecha', 'Rozmnażanie bezpłciowe', 'Rozmnażanie płciowe'],
        wiersze: [
          ['Liczba organizmów rodzicielskich', '1', '2'],
          ['Udział gamet', 'Nie', 'Tak'],
          ['Zmienność genetyczna potomstwa', 'Bardzo mała (klon)', 'Duża'],
          ['Tempo namnażania populacji', 'Zwykle szybkie', 'Zwykle wolniejsze'],
        ],
      },
      opcje: [
        'Rozmnażanie płciowe wymaga udziału jednego organizmu rodzicielskiego',
        'Potomstwo powstałe w wyniku rozmnażania bezpłciowego cechuje duża zmienność genetyczna',
        'Rozmnażanie bezpłciowe zwykle pozwala na szybsze namnożenie populacji niż płciowe',
        'W rozmnażaniu bezpłciowym biorą udział gamety',
      ],
      poprawna: 2,
      wyjasnienie:
        'Zgodnie z tabelą rozmnażanie bezpłciowe angażuje jeden organizm, nie wymaga gamet, daje potomstwo niemal identyczne genetycznie i zwykle pozwala na szybsze zwiększenie liczebności populacji niż rozmnażanie płciowe.',
      umiejetnosci: ['tabela', 'analiza'],
    },
    {
      id: 'p-t115-13',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc:
        'Populacja bakterii rozmnażających się wyłącznie bezpłciowo (przez podział) zostaje poddana działaniu antybiotyku. Dlaczego taka populacja jest szczególnie narażona na wyginięcie, jeśli żadna z komórek nie ma przypadkowej mutacji dającej odporność?',
      opcje: [
        'Ponieważ bakterie rozmnażające się bezpłciowo rosną wolniej niż te rozmnażające się płciowo',
        'Ponieważ wszystkie komórki potomne są genetycznie identyczne z komórką macierzystą, więc żadna z nich nie ma naturalnie innej wrażliwości na antybiotyk niż pozostałe',
        'Ponieważ bakterie nie mają materiału genetycznego',
        'Ponieważ antybiotyki działają wyłącznie na organizmy rozmnażające się płciowo',
      ],
      poprawna: 1,
      wyjasnienie:
        'Skoro rozmnażanie bezpłciowe nie tworzy nowych kombinacji genów, cała populacja jest genetycznie jednorodna (klon). Jeśli żadna komórka nie ma losowej mutacji dającej oporność, wszystkie reagują na antybiotyk tak samo, co grozi wyginięciem całej populacji — brak zmienności genetycznej ogranicza zdolność przystosowania się do zmian środowiska.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t115-14',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'matching',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Dopasuj mniej oczywisty przykład organizmu do sposobu, w jaki rozmnaża się bezpłciowo.',
      dopasowanie: {
        lewa: ['Storczyk (rozmnażany kłączem w uprawie)', 'Truskawka', 'Rozgwiazda po utracie ramienia', 'Bakteria E. coli'],
        prawa: ['Podział komórki', 'Fragmentacja/regeneracja', 'Rozmnażanie wegetatywne (kłącze)', 'Rozmnażanie wegetatywne (rozłogi)'],
        pary: [2, 3, 1, 0],
      },
      wyjasnienie:
        'Storczyk można rozmnażać wegetatywnie za pomocą kłącza, truskawka wytwarza rozłogi, rozgwiazda potrafi zregenerować cały organizm z fragmentu ciała (fragmentacja), a bakterie rozmnażają się przez podział komórki.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t115-15',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Uzupełnij zdania precyzyjnymi pojęciami biologicznymi.',
      tekstZLuka:
        'Proces, w którym z fragmentu ciała organizmu odtwarza się cały, samodzielny osobnik, nazywamy {{luka1}}. Rośliny mogą też rozmnażać się bezpłciowo za pomocą organów takich jak rozłogi czy kłącza — nazywamy to {{luka2}}.',
      odpowiedziLuk: { luka1: ['fragmentacją', 'fragmentacja'], luka2: ['rozmnażaniem wegetatywnym', 'rozmnażanie wegetatywne'] },
      wyjasnienie:
        'Odtworzenie całego organizmu z fragmentu ciała to fragmentacja (regeneracja), a rozmnażanie roślin za pomocą organów wegetatywnych (rozłogi, kłącza, bulwy) to rozmnażanie wegetatywne.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t115-16',
      dzialId: 'd1',
      tematId: 't115',
      typ: 'diagram',
      poziom: 'konkursowy',
      punkty: 2,
      diagramId: 'd-t115-rozmnazanie',
      tresc: 'Na diagramie porównano rozmnażanie bezpłciowe i płciowe. Które zdanie poprawnie opisuje przedstawioną na nim sytuację?',
      opcje: [
        'Po lewej stronie diagramu przedstawiono połączenie dwóch gamet w zygotę',
        'Po prawej stronie diagramu potomek powstaje w wyniku połączenia gamety męskiej i żeńskiej, co prowadzi do zmienności genetycznej',
        'Obie strony diagramu przedstawiają dokładnie ten sam proces',
        'Po lewej stronie diagramu widoczne są dwie różne gamety',
      ],
      poprawna: 1,
      wyjasnienie:
        'Prawa strona diagramu przedstawia rozmnażanie płciowe — połączenie gamety męskiej i żeńskiej prowadzi do powstania zygoty i potomka o nowej kombinacji genów. Lewa strona przedstawia rozmnażanie bezpłciowe, w którym potomkowie są identyczni genetycznie z jednym rodzicem.',
      umiejetnosci: ['diagram', 'analiza'],
    },
  ]);
})();
