(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t103-01',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Jakie związki chemiczne są podstawowymi jednostkami budującymi białka?',
      opcje: ['Aminokwasy', 'Monosacharydy', 'Kwasy tłuszczowe', 'Nukleotydy'],
      poprawna: 0,
      wyjasnienie: 'Białka są zbudowane z aminokwasów połączonych wiązaniami peptydowymi w długie łańcuchy.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t103-02',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Wiązanie łączące dwa sąsiednie aminokwasy w łańcuchu białkowym nazywamy wiązaniem peptydowym.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — wiązanie peptydowe powstaje między grupą karboksylową jednego aminokwasu a grupą aminową drugiego.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t103-03',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Ile poziomów struktury przestrzennej może mieć cząsteczka białka?',
      opcje: ['Dwa', 'Trzy', 'Cztery', 'Pięć'],
      poprawna: 2,
      wyjasnienie: 'Wyróżniamy cztery poziomy struktury białka: I-rzędową, II-rzędową, III-rzędową i IV-rzędową (tę ostatnią mają tylko białka złożone z kilku łańcuchów).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t103-04',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Podstawowe jednostki budujące białka to {{luka1}}. Kolejność, w jakiej są one połączone w łańcuchu, nazywamy strukturą {{luka2}}.',
      odpowiedziLuk: { luka1: ['aminokwasy'], luka2: ['pierwszorzędową', 'I-rzędową', 'pierwszorzedowa'] },
      wyjasnienie: 'Aminokwasy to podstawowe jednostki budujące białka, a ich sekwencja w łańcuchu to struktura pierwszorzędowa (I-rzędowa).',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t103-05',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'single',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Co powstaje jako produkt uboczny podczas łączenia dwóch aminokwasów wiązaniem peptydowym?',
      opcje: ['Cząsteczka wody', 'Cząsteczka tlenu', 'Cząsteczka amoniaku', 'Cząsteczka dwutlenku węgla'],
      poprawna: 0,
      wyjasnienie: 'Powstawanie wiązania peptydowego to reakcja kondensacji — grupa karboksylowa jednego aminokwasu łączy się z grupą aminową drugiego, a uwolniony zostaje atom wodoru i grupa hydroksylowa, tworzące razem cząsteczkę wody.',
      umiejetnosci: ['budowa-funkcja', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t103-06',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 3,
      tresc: 'Które z poniższych są funkcjami pełnionymi przez białka w organizmie? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Funkcja budulcowa (np. kolagen, keratyna)', 'Funkcja enzymatyczna (przyspieszanie reakcji chemicznych)', 'Główne, długoterminowe magazynowanie energii zapasowej', 'Funkcja odpornościowa (przeciwciała)'],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Białka pełnią funkcje budulcową, enzymatyczną i odpornościową. Głównym materiałem zapasowym magazynującym energię w organizmie są tłuszcze, a nie białka.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t103-07',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 3,
      tresc: 'Dopasuj rodzaj białka do jego przykładu.',
      dopasowanie: {
        lewa: ['Enzym', 'Przeciwciało', 'Hormon białkowy', 'Białko budulcowe'],
        prawa: ['Kolagen (skóra, ścięgna)', 'Insulina (reguluje poziom cukru we krwi)', 'Amylaza (rozkłada skrobię)', 'Immunoglobulina (zwalcza patogeny)'],
        pary: [2, 3, 1, 0],
      },
      wyjasnienie: 'Amylaza to enzym trawienny, immunoglobulina to przeciwciało, insulina to hormon białkowy, a kolagen to białko budulcowe skóry i ścięgien.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t103-08',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'ordering',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uporządkuj poziomy struktury białka od najprostszego do najbardziej złożonego.',
      elementy: [
        'Sekwencja aminokwasów w łańcuchu (struktura I-rzędowa)',
        'Lokalne pofałdowanie łańcucha w helisę lub harmonijkę (struktura II-rzędowa)',
        'Przestrzenne, trójwymiarowe zwinięcie całego łańcucha (struktura III-rzędowa)',
        'Połączenie kilku łańcuchów w jedną cząsteczkę (struktura IV-rzędowa)',
      ],
      wyjasnienie: 'Struktura I-rzędowa (sekwencja) jest podstawą, na której powstają kolejno struktury II, III i (u niektórych białek) IV-rzędowa.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t103-09',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dlaczego zmiana kolejności choćby jednego aminokwasu w łańcuchu białkowym może całkowicie zmienić funkcję białka?',
      opcje: [
        'Ponieważ sekwencja aminokwasów (struktura I-rzędowa) determinuje sposób przestrzennego zwinięcia białka, a to z kolei decyduje o jego funkcji',
        'Ponieważ każdy aminokwas ma inny ładunek elektryczny niezależny od kształtu białka',
        'Ponieważ zmiana jednego aminokwasu zawsze powoduje natychmiastową denaturację białka',
        'Ponieważ białka bez ściśle określonej sekwencji w ogóle nie mogą powstać w komórce',
      ],
      poprawna: 0,
      wyjasnienie: 'To klasyczna zależność budowa-funkcja: sekwencja aminokwasów determinuje, jak łańcuch się pofałduje i zwinie przestrzennie, a ostateczny kształt cząsteczki decyduje o tym, jaką funkcję białko może pełnić.',
      umiejetnosci: ['budowa-funkcja', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t103-10',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'multiple',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Które stwierdzenia o denaturacji białka są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Polega na zniszczeniu przestrzennej struktury białka bez zrywania wiązań peptydowych',
        'Może być spowodowana wysoką temperaturą lub silnie zmienionym pH',
        'Jest zawsze procesem w pełni odwracalnym',
        'Powoduje najczęściej utratę biologicznej aktywności białka (np. enzymu)',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Denaturacja niszczy strukturę przestrzenną białka (nie wiązania peptydowe), może być wywołana temperaturą lub pH i zwykle prowadzi do utraty aktywności biologicznej. Zazwyczaj jest procesem nieodwracalnym, a nie odwracalnym.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t103-11',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'image',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Na schemacie poziomów organizacji białka, który numer odpowiada strukturze trzeciorzędowej (III-rzędowej)?',
      diagramId: 'd-t103-struktury-bialka',
      opcje: ['1', '2', '3', '4'],
      poprawna: 2,
      wyjasnienie: 'Struktura III-rzędowa to przestrzenne, trójwymiarowe zwinięcie całego łańcucha polipeptydowego — na schemacie jest to trzeci etap (numer 3), po strukturze I-rzędowej (sekwencja) i II-rzędowej (helisa/harmonijka).',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t103-12',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'table',
      poziom: 'trudny',
      punkty: 3,
      tresc: 'Na podstawie tabeli wskaż, który poziom struktury białka jest bezpośrednio niszczony podczas trawienia (hydrolizy) białka w żołądku.',
      tabela: {
        tytul: 'Poziomy struktury białka',
        kolumny: ['Poziom struktury', 'Co opisuje', 'Przykładowe wiązanie/oddziaływanie'],
        wiersze: [
          ['I-rzędowa', 'Kolejność aminokwasów w łańcuchu', 'Wiązanie peptydowe'],
          ['II-rzędowa', 'Lokalny kształt fragmentu łańcucha (helisa, harmonijka)', 'Wiązania wodorowe wzdłuż łańcucha'],
          ['III-rzędowa', 'Przestrzenne zwinięcie całego łańcucha', 'Oddziaływania między grupami R aminokwasów'],
          ['IV-rzędowa', 'Połączenie kilku łańcuchów w jedną cząsteczkę', 'Oddziaływania między podjednostkami'],
        ],
      },
      opcje: ['I-rzędowa', 'II-rzędowa', 'III-rzędowa', 'IV-rzędowa'],
      poprawna: 0,
      wyjasnienie: 'Trawienie to hydroliza wiązań peptydowych, a więc bezpośrednio niszczy strukturę I-rzędową (rozkłada łańcuch na pojedyncze aminokwasy). To odróżnia trawienie od denaturacji, która niszczy jedynie wyższe poziomy struktury.',
      umiejetnosci: ['tabela', 'analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t103-13',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Wysoka gorączka (powyżej ok. 42°C) jest niebezpieczna dla organizmu człowieka przede wszystkim dlatego, że:',
      opcje: [
        'Powoduje nieodwracalną denaturację białek enzymatycznych, które w efekcie przestają działać',
        'Przyspiesza trawienie białek w żołądku do niebezpiecznego poziomu',
        'Zwiększa liczbę wiązań peptydowych w komórkach organizmu',
        'Zamienia cząsteczki białek w cząsteczki węglowodanów',
      ],
      poprawna: 0,
      wyjasnienie: 'Wysoka temperatura powoduje denaturację białek, w tym enzymów niezbędnych do zachodzenia reakcji metabolicznych. Bez sprawnych enzymów podstawowe procesy komórkowe zostają zaburzone, co zagraża życiu.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t103-14',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'truefalse',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Ugotowanie białka jaja kurzego jest przykładem trawienia białka, ponieważ pod wpływem wysokiej temperatury dochodzi do rozerwania wiązań peptydowych.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz. Gotowanie powoduje denaturację białka — zmienia się jedynie jego kształt przestrzenny, a wiązania peptydowe pozostają nienaruszone. Trawienie (rozerwanie wiązań peptydowych) zachodzi dopiero pod wpływem enzymów trawiennych w przewodzie pokarmowym.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t103-15',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Enzym trawienny działający prawidłowo w środowisku żołądka (pH ok. 2) przestaje działać po przeniesieniu do środowiska o pH 8. Najbardziej prawdopodobne wyjaśnienie tego zjawiska to:',
      opcje: [
        'Zmiana pH spowodowała denaturację enzymu i utratę jego charakterystycznego kształtu przestrzennego',
        'Enzym w nowym środowisku zamienił się w cząsteczkę węglowodanu',
        'Zmiana pH zwiększyła liczbę wiązań peptydowych w cząsteczce enzymu',
        'Enzym uległ całkowitemu strawieniu przez samego siebie',
      ],
      poprawna: 0,
      wyjasnienie: 'Silna zmiana pH może zaburzyć oddziaływania utrzymujące przestrzenny kształt białka, prowadząc do denaturacji. Ponieważ aktywność enzymu zależy od dopasowania jego kształtu do substratu, denaturacja oznacza utratę aktywności.',
      umiejetnosci: ['przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t103-16',
      dzialId: 'd1',
      tematId: 't103',
      typ: 'gapfill',
      poziom: 'konkursowy',
      punkty: 3,
      tresc: 'Uzupełnij zdanie dotyczące różnicy między trawieniem a denaturacją białek.',
      tekstZLuka:
        'Podczas trawienia białek w przewodzie pokarmowym rozrywane są wiązania {{luka1}}, natomiast podczas denaturacji (np. pod wpływem wysokiej temperatury) niszczona jest jedynie {{luka2}} struktura białka, a wiązania między aminokwasami pozostają nienaruszone.',
      odpowiedziLuk: { luka1: ['peptydowe'], luka2: ['przestrzenna', 'trójwymiarowa', 'przestrzenna (trzeciorzędowa)', 'trzeciorzędowa'] },
      wyjasnienie: 'Trawienie rozrywa wiązania peptydowe (strukturę I-rzędową), a denaturacja niszczy jedynie wyższe, przestrzenne poziomy struktury białka, nie naruszając samej sekwencji aminokwasów.',
      umiejetnosci: ['budowa-funkcja', 'przyczynowo-skutkowe'],
    },
  ]);
})();
