(function () {
  'use strict';
  var register = window.App.content.register;

  register.pytania([
    {
      id: 'p-t109-01',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'single',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Czym pod względem przepuszczalności dla różnych substancji jest błona komórkowa?',
      opcje: [
        'W pełni przepuszczalna dla wszystkich substancji',
        'Całkowicie nieprzepuszczalna dla wszystkich substancji',
        'Półprzepuszczalna — przepuszcza jedne substancje, a innych nie',
        'Przepuszczalna wyłącznie dla wody',
      ],
      poprawna: 2,
      wyjasnienie: 'Błona komórkowa jest półprzepuszczalna (selektywnie przepuszczalna) — dzięki temu komórka może kontrolować, jakie substancje do niej wnikają, a jakie z niej wychodzą.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t109-02',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'single',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Który z wymienionych procesów transportu wymaga zużycia energii w postaci ATP?',
      opcje: ['Dyfuzja prosta', 'Osmoza', 'Dyfuzja wspomagana', 'Transport aktywny'],
      poprawna: 3,
      wyjasnienie: 'Transport aktywny odbywa się wbrew gradientowi stężeń, dlatego wymaga nakładu energii pochodzącej z rozkładu ATP. Pozostałe procesy to formy transportu biernego.',
      umiejetnosci: ['wiedza', 'budowa-funkcja'],
    },
    {
      id: 'p-t109-03',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'single',
      poziom: 'trudny',
      punkty: 2,
      tresc:
        'Cząsteczki glukozy nie mogą swobodnie przenikać przez dwuwarstwę lipidową, ale przemieszczają się przez błonę zgodnie z gradientem stężeń, bez zużycia energii przez komórkę, dzięki białkom kanałowym lub transportowym. Ten proces nazywamy...',
      opcje: ['dyfuzją prostą', 'dyfuzją wspomaganą (ułatwioną)', 'transportem aktywnym', 'osmozą'],
      poprawna: 1,
      wyjasnienie: 'Dyfuzja wspomagana dotyczy cząsteczek, które nie przenikają bezpośrednio przez dwuwarstwę lipidową i potrzebują białek błonowych, ale nadal przemieszczają się zgodnie z gradientem stężeń i bez zużycia energii.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t109-04',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'single',
      poziom: 'konkursowy',
      punkty: 2,
      tresc:
        'Krążek tkanki roślinnej umieszczono w stężonym roztworze soli. Po pewnym czasie zaobserwowano, że komórki straciły jędrność (turgor), a błona komórkowa wraz z cytoplazmą oddzieliła się od ściany komórkowej. To zjawisko nazywamy...',
      opcje: ['turgorem', 'plazmolizą', 'fotosyntezą', 'transportem aktywnym'],
      poprawna: 1,
      wyjasnienie:
        'Plazmoliza to odpływ wody z komórki roślinnej (na drodze osmozy) do bardziej stężonego roztworu zewnętrznego, powodujący obkurczenie się protoplastu (błony z cytoplazmą) i jego oddzielenie od sztywnej ściany komórkowej.',
      umiejetnosci: ['przyczynowo-skutkowe', 'analiza'],
    },
    {
      id: 'p-t109-05',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'truefalse',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Transport bierny zachodzi zgodnie z gradientem stężeń i nie wymaga zużycia energii przez komórkę.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 0,
      wyjasnienie: 'To prawda — transport bierny (dyfuzja, osmoza) odbywa się samorzutnie, z obszaru o wyższym do niższego stężenia, bez udziału energii ATP.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t109-06',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'truefalse',
      poziom: 'trudny',
      punkty: 1,
      tresc: 'Osmoza dotyczy przemieszczania się przez błonę dowolnych substancji rozpuszczonych w wodzie.',
      opcje: ['Prawda', 'Fałsz'],
      poprawna: 1,
      wyjasnienie: 'To fałsz — osmoza dotyczy wyłącznie przemieszczania się cząsteczek WODY przez błonę półprzepuszczalną, a nie substancji w niej rozpuszczonych.',
      umiejetnosci: ['przyczynowo-skutkowe'],
    },
    {
      id: 'p-t109-07',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'multiple',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Które z poniższych procesów są przykładami transportu BIERNEGO? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: ['Dyfuzja prosta', 'Transport z udziałem pompy sodowo-potasowej', 'Osmoza', 'Dyfuzja wspomagana'],
      poprawna: [0, 2, 3],
      wyjasnienie: 'Dyfuzja prosta, osmoza i dyfuzja wspomagana to formy transportu biernego — zachodzą zgodnie z gradientem stężeń, bez zużycia energii. Pompa sodowo-potasowa to przykład transportu aktywnego.',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t109-08',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'multiple',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Które stwierdzenia dotyczące białek błonowych są prawdziwe? Zaznacz wszystkie poprawne odpowiedzi.',
      opcje: [
        'Białka kanałowe tworzą pory umożliwiające przechodzenie określonych cząsteczek lub jonów',
        'Białka receptorowe rozpoznają sygnały chemiczne docierające do komórki',
        'Wszystkie białka błonowe uczestniczą wyłącznie w transporcie aktywnym',
        'Białka transportowe (nośnikowe) mogą uczestniczyć zarówno w transporcie biernym (dyfuzja wspomagana), jak i aktywnym',
      ],
      poprawna: [0, 1, 3],
      wyjasnienie: 'Białka błonowe pełnią różne funkcje — nie tylko transportową (np. receptorową), a białka transportowe mogą działać zarówno biernie, jak i aktywnie (kosztem ATP).',
      umiejetnosci: ['analiza', 'budowa-funkcja'],
    },
    {
      id: 'p-t109-09',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'matching',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Dopasuj rodzaj transportu do jego opisu.',
      dopasowanie: {
        lewa: ['Dyfuzja prosta', 'Osmoza', 'Transport aktywny', 'Dyfuzja wspomagana'],
        prawa: [
          'Ruch małych cząsteczek bezpośrednio przez dwuwarstwę lipidową, zgodnie z gradientem stężeń',
          'Ruch cząsteczek wody przez błonę półprzepuszczalną',
          'Ruch substancji wbrew gradientowi stężeń, kosztem energii ATP',
          'Ruch cząsteczek przez białka kanałowe/transportowe, zgodnie z gradientem stężeń, bez zużycia energii',
        ],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Każdy z czterech procesów różni się rodzajem przemieszczanej substancji, udziałem białek oraz zużyciem (lub nie) energii ATP.',
      umiejetnosci: ['wiedza', 'analiza'],
    },
    {
      id: 'p-t109-10',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'matching',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Dopasuj przykład do rodzaju transportu, który najlepiej go opisuje.',
      dopasowanie: {
        lewa: [
          'Pompa sodowo-potasowa w komórce nerwowej',
          'Przenikanie tlenu z pęcherzyków płucnych do krwi',
          'Pobieranie wody przez włośniki korzeniowe z gleby',
          'Wchłanianie glukozy do komórki nabłonka jelita przy udziale białka nośnikowego, zgodnie z gradientem stężeń',
        ],
        prawa: ['Transport aktywny', 'Dyfuzja prosta', 'Osmoza', 'Dyfuzja wspomagana'],
        pary: [0, 1, 2, 3],
      },
      wyjasnienie: 'Pompa sodowo-potasowa wymaga ATP (transport aktywny); tlen dyfunduje bezpośrednio przez błony (dyfuzja prosta); pobieranie wody przez korzenie to osmoza; wchłanianie glukozy przy udziale białka, zgodnie z gradientem, to dyfuzja wspomagana.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t109-11',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'gapfill',
      poziom: 'latwy',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka: 'Podstawę błony komórkowej stanowi {{luka1}} fosfolipidowa. Białka zanurzone w błonie, które tworzą w niej pory, nazywamy białkami {{luka2}}.',
      odpowiedziLuk: { luka1: ['dwuwarstwa'], luka2: ['kanałowymi', 'kanałowe'] },
      wyjasnienie: 'Błona komórkowa zbudowana jest z dwuwarstwy fosfolipidowej, a pory umożliwiające przechodzenie substancji tworzą białka kanałowe.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t109-12',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'gapfill',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Uzupełnij zdanie właściwymi pojęciami.',
      tekstZLuka:
        'Ruch cząsteczek zgodnie z gradientem stężeń, bez zużycia energii, nazywamy transportem {{luka1}}. Ruch substancji wbrew gradientowi stężeń, wymagający energii z ATP, nazywamy transportem {{luka2}}.',
      odpowiedziLuk: { luka1: ['biernym'], luka2: ['aktywnym'] },
      wyjasnienie: 'Transport bierny nie wymaga energii i zachodzi zgodnie z gradientem stężeń, a transport aktywny wymaga energii ATP i zachodzi wbrew gradientowi.',
      umiejetnosci: ['wiedza'],
    },
    {
      id: 'p-t109-13',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'ordering',
      poziom: 'trudny',
      punkty: 2,
      tresc: 'Uporządkuj etapy działania białkowej pompy błonowej (transport aktywny, np. pompa sodowo-potasowa), od początku do końca.',
      elementy: [
        'Jon łączy się z białkiem transportowym po jednej stronie błony',
        'Energia uwolniona z rozkładu ATP powoduje zmianę kształtu białka',
        'Białko przenosi jon na drugą stronę błony',
        'Jon zostaje uwolniony po przeciwnej stronie błony, a białko wraca do pierwotnego kształtu',
      ],
      wyjasnienie: 'Transport aktywny wymaga kolejno: przyłączenia cząsteczki do białka, dostarczenia energii z ATP, zmiany kształtu białka przenoszącej cząsteczkę na drugą stronę i uwolnienia jej po przeciwnej stronie błony.',
      umiejetnosci: ['analiza', 'przyczynowo-skutkowe', 'budowa-funkcja'],
    },
    {
      id: 'p-t109-14',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'image',
      diagramId: 'd-t109-blona-komorkowa',
      poziom: 'latwy',
      punkty: 1,
      tresc: 'Na schemacie błony komórkowej, który numer oznacza białko kanałowe?',
      opcje: ['Numer 1', 'Numer 3', 'Numer 4', 'Numer 5'],
      poprawna: 1,
      wyjasnienie: 'Numer 3 wskazuje białko kanałowe — strukturę z widocznym porem pośrodku, umożliwiającą przechodzenie substancji przez błonę.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t109-15',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'image',
      diagramId: 'd-t109-blona-komorkowa',
      poziom: 'sredni',
      punkty: 1,
      tresc: 'Który numer na schemacie oznacza hydrofobowy ("unikający wody") fragment cząsteczki fosfolipidu?',
      opcje: ['Numer 1', 'Numer 2', 'Numer 3', 'Numer 5'],
      poprawna: 1,
      wyjasnienie: 'Numer 2 oznacza ogon fosfolipidu — jest hydrofobowy i dlatego skierowany do wnętrza błony, z dala od środowiska wodnego. Numer 1 to hydrofilowa głowa fosfolipidu.',
      umiejetnosci: ['diagram', 'budowa-funkcja'],
    },
    {
      id: 'p-t109-16',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'chart',
      poziom: 'konkursowy',
      punkty: 2,
      tresc: 'Na podstawie wykresu wyjaśnij przyczynę spadku masy paska ziemniaka po 30 minutach w roztworze NaCl o stężeniu 10%.',
      wykres: {
        typ: 'liniowy',
        tytul: 'Zmiana masy paska ziemniaka po 30 min w roztworach NaCl o różnym stężeniu',
        jednostka: '%',
        dane: [
          { etykieta: '0% (woda destylowana)', wartosc: 9 },
          { etykieta: '2%', wartosc: 3 },
          { etykieta: '5%', wartosc: -5 },
          { etykieta: '10%', wartosc: -14 },
        ],
      },
      opcje: [
        'Woda wniknęła do komórek ziemniaka z roztworu, zwiększając ich masę',
        'Woda wypłynęła z komórek ziemniaka do bardziej stężonego roztworu na drodze osmozy, co zmniejszyło ich masę',
        'Sól kuchenna wniknęła do komórek ziemniaka, zwiększając ich masę',
        'Ziemniak w drodze transportu aktywnego wypompował wodę na zewnątrz',
      ],
      poprawna: 1,
      wyjasnienie:
        'W roztworze o wysokim stężeniu soli (10%) stężenie substancji rozpuszczonych na zewnątrz komórek jest wyższe niż wewnątrz nich. Zgodnie z zasadą osmozy woda przemieszcza się z obszaru o niższym do wyższego stężenia roztworu, czyli wypływa z komórek ziemniaka na zewnątrz — masa paska maleje.',
      umiejetnosci: ['wykres', 'analiza', 'przyczynowo-skutkowe'],
    },
    {
      id: 'p-t109-17',
      dzialId: 'd1',
      tematId: 't109',
      typ: 'table',
      poziom: 'sredni',
      punkty: 2,
      tresc: 'Na podstawie tabeli wskaż zdanie prawdziwe.',
      tabela: {
        tytul: 'Porównanie rodzajów transportu przez błonę komórkową',
        kolumny: ['Rodzaj transportu', 'Kierunek względem gradientu stężeń', 'Zużycie energii ATP'],
        wiersze: [
          ['Dyfuzja prosta', 'Zgodnie z gradientem', 'Nie'],
          ['Osmoza (woda)', 'Zgodnie z gradientem', 'Nie'],
          ['Dyfuzja wspomagana', 'Zgodnie z gradientem', 'Nie'],
          ['Transport aktywny', 'Wbrew gradientowi', 'Tak'],
        ],
      },
      opcje: [
        'Wszystkie rodzaje transportu przez błonę wymagają zużycia energii ATP',
        'Transport aktywny jako jedyny zachodzi wbrew gradientowi stężeń i wymaga energii ATP',
        'Dyfuzja wspomagana wymaga więcej energii niż transport aktywny',
        'Osmoza zawsze zachodzi wbrew gradientowi stężeń',
      ],
      poprawna: 1,
      wyjasnienie: 'Z tabeli jasno wynika, że jedynie transport aktywny przebiega wbrew gradientowi stężeń i wymaga zużycia energii ATP — pozostałe rodzaje transportu są bierne.',
      umiejetnosci: ['tabela', 'analiza'],
    },
  ]);
})();
